### ISSUE TITLE
[rdkafka] Create a config setting to not send Kafka headers

### ISSUE THREAD

**Issue by maks-rafalko** [php-enqueue/enqueue-dev#1005]
## Why?

We are using MessagePack as a serializer (instead of standard JSON) and Gzip for compressing to reduce the message size, so basically we do the following:

* `body` value of the Interop message is processed like `gzencode(msgpack_pack($bodyValue));`
* `headers` values - in the same way

When the message is sent from `RdKafkaProducer`, headers are sent as "native" headers using `producev()` method (while still duplicated inside the Interop Message).

https://github.com/php-enqueue/enqueue-dev/blob/8f86cf9feedb5437999f6fa6d990665696a38f2a/pkg/rdkafka/RdKafkaProducer.php#L58

And the whole message looks like:

<img width="1439" alt="headers_sent" src="https://user-images.githubusercontent.com/3725595/71763816-6e417100-2ef1-11ea-9839-3d909a6adb0b.png">

But when the message is read from topic, Gzipped and MessagePacke'd headers are corrupted:

<img width="678" alt="headers_corrupted" src="https://user-images.githubusercontent.com/3725595/71763861-0e979580-2ef2-11ea-84fb-fd0d9528877d.png">

_(note the difference in the headers values in producer and consumer, `b"\x1F‹\x08"` - corrupted messages)_

The issue is those corrupted headers are merged and used as a priority here:

https://github.com/php-enqueue/enqueue-dev/blob/8f86cf9feedb5437999f6fa6d990665696a38f2a/pkg/rdkafka/RdKafkaConsumer.php#L173-L175

## Proposed solution

So, in order to workaround it, we need to not send it (actually, we don't use those native headers so it would be useful to not send extra data), s we need a setting.

## Alternative solution

Alternative solution would be to not serialize native headers at all. But that would be a BC break. So we probably can introduce a setting to leave the headers as is (disabled by default).

---

This is definitely a bug with `php-rdkafka` or `librdkafka` that headers are being corrupted, I will report it separately to corresponded repositories.

**Comment by Steveb-p** [comment]
@maks-rafalko would you mind providing a binary message sample code for php-rdkafka repository? Does this also happen if you forcefully switch to `produce` producer method?

**Comment by maks-rafalko** [comment]
Put as much info as I can to https://github.com/arnaud-lb/php-rdkafka/issues/334

Let's continue discussing there and leave this ticket for the new setting. Do you think this setting is something you would like to see in the lib?

To sum up why it may be useful:

* to not send headers when nobody uses them
* to workaround described issues

**Comment by maks-rafalko** [comment]
> stale bot added the wontfix label 1 minute ago

Any thoughts from maintainers?

FYI: https://github.com/arnaud-lb/php-rdkafka/issues/334 issue reported to php-rdkafka was fixed and merged to master.

However, I still think we need to have a config setting to disable sending headers as those are useless and anyway duplicated inside interop message.

**Comment by maks-rafalko** [comment]
ping @makasim @Steveb-p

**Comment by makasim** [comment]
> However, I still think we need to have a config setting to disable sending headers as those are useless and anyway duplicated inside interop message.

I am fine with it. Could you work on a PR?
