### ISSUE TITLE
[GPS] GpsProducer unable to send to a queue

### ISSUE THREAD

**Issue by biforb4** [php-enqueue/enqueue-dev#1017]
Hi, I'm using Enqueue 0.10 on Symfony 4.4 with symfony bundle. Trying to use the google pub sub transport, Unfortunately consuming messages doesn't seem to work.

Running
> /bin/console enqueue:consume --setup-broker -vvv default

results in
> In InvalidDestinationException.php line 17:
>[Interop\Queue\Exception\InvalidDestinationException]                                      
>The destination must be an instance of Enqueue\Gps\GpsTopic but got Enqueue\Gps\GpsQueue. 

Looking at the GpsProducer indeed it can only handle an instance of the GpsTopic.

I've compared this with AmqpProducer and it can send messages to both - queues and topics. Consuming messages with amqp transport works fine.

Is there a reason for this? Seems like using a amqp transport is impossible at the moment.

**Comment by makasim** [comment]
I am not much into GPS logic. It might be a missing feature. Feel free to send a PR.
