### ISSUE TITLE
[Kafka] The lib could manage the DLQ flow

### ISSUE THREAD

**Issue by thiagovulcao** [php-enqueue/enqueue-dev#1019]
Hi guys, I work in a project with mixed team. We have java and PHP developers, and in ours study time, before do some implementations we found some differences between the two libs. The java team uses Spring Cloud Stream, and we are using php-enqueue, but at the moment we have the same situation, we need to manage the DLQ messages.

Spring Cloud Stream have an abstraction, i was wondering if php-enqueue can have this feature to provide the same experience to developers.

If someone will need some help I'm in! Thank's and if I say something wrong or far from reality sorry! =)

**Comment by Steveb-p** [comment]
Since this is specifically targeted at `enqueue/kafka`, following our discussion on Slack / gitter, I'm renaming the issue. Feel free to adjust it as needed.
