### ISSUE TITLE
Erroneous throwing of Exception in MongoDbProducer

### ISSUE THREAD

**Issue by josefsabl** [php-enqueue/enqueue-dev#1031]
I am writing here as `php-enqueue/mongodb` does not accept issues.

There is a silly bug on this line:

https://github.com/php-enqueue/mongodb/blob/1a8a2da0b866c5c4fee8a6d10a5130a2c7c011b0/MongodbProducer.php#L113

PHP Exception does not accept null as second argument. It is optional, yes, but must be int if provided.

This is an issue and not a cosmetic bug, because the previous exception is lost and doesn't show up in Sentry, logs or whatever.

**Comment by Steveb-p** [comment]
> I am writing here as `php-enqueue/mongodb` does not accept issues.

As is the case for most mono-repos :smile: 

> PHP Exception does not accept null as second argument. It is optional, yes, but must be int if provided.

Do you mind creating a PR? It should be a simple change to use code from the exception that was caught, should be sufficient.

> doesn't show up in Sentry

:beer: for using Sentry :smile:

**Comment by josefsabl** [comment]
> As is the case for most mono-repos 😄

Understood, I just didn't know if I am reporting in correct place ;-)

> Do you mind creating a PR

Yea, will have to do it anyways since [this](https://github.com/php-enqueue/enqueue-dev/issues/1027) did bite us bad as there is one more bug in documentation so I will need to fix it as well.

🍺🍺
