### ISSUE TITLE
DLQ

### ISSUE THREAD

**Issue by renatocosta** [php-enqueue/enqueue-dev#1045]
Does lib support Dead letter queue? Is possible in case of reaching out max attempts and then move the message to another topic?

**Comment by makasim** [comment]
Are you about AMQP\RabbitMQ? The AMQP transports support it.

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-tools/RabbitMqDlxDelayStrategy.php

**Comment by renatocosta** [comment]
> It's about Kafka what I mean
