### ISSUE TITLE
Probleme with AmqpDriver when setup-brocker

### ISSUE THREAD

**Issue by abdelhak-hiit** [php-enqueue/enqueue-dev#1047]
Using Amqp driver with enqueue bundle, i can't setup an exchange with a different type (`topic`, `fanout`, `direct`) and set binding key.

After reading code, i see that the exchange type is set to `fanout` when setup-broker : https://github.com/php-enqueue/enqueue/blob/master/Client/Driver/AmqpDriver.php#L104.

Is there a way to change this to have some flexibility on my config ?

Example : 

```
public static function getSubscribedCommand()
    {
        return [
            'command' => self::QUEUE_NAME,
            'queue' => self::QUEUE_NAME,
            'prefix_queue' => false,
            'exclusive' => true,
            'exchange_name' => self::EXCHANGE_NAME,
            'exchange_type' => AmqpTopic::TYPE_TOPIC,
            'routing_key' => self::ROUTING_KEY,
        ];
    }
```

**Comment by makasim** [comment]
You have some options:

* Implement custom driver
* Use amqp transport directly. That would give you full control over what you can do.
* Work on setup broker feature https://github.com/php-enqueue/enqueue-dev/pull/704.
