### ISSUE TITLE
Multienviroment support

### ISSUE THREAD

**Issue by psociety** [php-enqueue/enqueue-dev#1050]
Hi!
I'm using enqueue-dev in symfony with beanstalk, where i have multiple enviroments (.env).
How should i setup enqueue so jobs from different enviroments don't get mixed in the same queue?

I run the jobs of each enviroment using:
`APP_ENV=qa bin/console messenger:consume beanstalk -vvv`
`APP_ENV=production bin/console messenger:consume beanstalk -vvv`

When i was using pheanstalk i just added a suffix on jobs name, but in symfony jobs are set using classes:
```php
$message = new ReportMessage($reportUrl);
$this->bus->dispatch((new Envelope($message))->with(new DelayStamp(1000)));
```

(my old implementation):
```php
$this->pheanstalk->useTube(JOB_REPORT_MESSAGE . APP_ENV)->put(json_encode($data));
```

**Comment by makasim** [comment]
That's messenger issue, not enqueue. Ask for help there https://github.com/sroze/messenger-enqueue-transport
