### ISSUE TITLE
RedisProducer not respecting custom MessageId property

### ISSUE THREAD

**Issue by ixarlie** [php-enqueue/enqueue-dev#1051]
Hi, I am trying to upgrade from 0.8 to 0.9. I've found an issue in the RedisProducer.

At [this line](https://github.com/php-enqueue/redis/blob/0.9.12/RedisProducer.php#L49) the message id is entirely replaced.
```php
    $message->setMessageId(Uuid::uuid4()->toString());
    $message->setHeader('attempts', 0);
```

Looking at the [Producer](https://github.com/php-enqueue/enqueue-dev/blob/0.9.15/pkg/enqueue/Client/Producer.php#L110-L112) class, the message id is only set if it doesn't exist.
```php
    if (!$message->getMessageId()) {
        $message->setMessageId(UUID::generate());
    }
```

In my code, I set the message id before I send the message. I use the message id property as the Job's owner id, but RedisProducer is not respecting my choice and my consumers are not working properly, because they are not able to find the job by that owner id.

I am using the Job integration a bit different, creating the jobs before sending the messages because my frontend client expects a "promise" resource.

In the meantime I am using another message property as a workaround, but I think the RedisProducer should check if the message id is empty in order to set a value.

Thanks!

**Comment by makasim** [comment]
PR is welcome
