### ISSUE TITLE
[amqp-lib] Delayed messages triggered on worker restart

### ISSUE THREAD

**Issue by nospoon** [php-enqueue/enqueue-dev#1053]
When the queue workers are restarted (using supervisor), all delayed messages are instantly triggered, regardless of the remaining delay.
This happens when using either `rabbitmq_dlx` or `rabbitmq_delay_plugin` delay strategy.

Implemented via laravel-queue with amqp+rabbitmq dsn.

**Comment by makasim** [comment]
It should not happen per my understanding of how RabbitMQ works and I've never experienced such behavior. 


Needs more details.
