### ISSUE TITLE
Messages are not getting consumed in publication order

### ISSUE THREAD

**Issue by kschu91** [php-enqueue/enqueue-dev#1054]
I noticed a very strange behavior. Messages are not getting consumed in their publication order. They are getting consumed in reverse order.

I would expect them to be consumed in order of their publication.

Code to reproduce:
```
$connectionFactory = new FsConnectionFactory(__DIR__ . '/test');
$context = $connectionFactory->createContext();
$queue = $context->createQueue('test');

$context->createProducer()->send($queue, $context->createMessage('1'));
$context->createProducer()->send($queue, $context->createMessage('2'));

$queueConsumer = new QueueConsumer($context);
$queueConsumer->bindCallback($queue, function (Message $message) {
    echo $message->getBody() . "\n";
    return Result::ACK;
});
$queueConsumer->consume();
```

The result will be:
```
2
1
```

But I expect it to be:
```
1
2
```

**Comment by makasim** [comment]
Filesystem queue is not queue but stack. That's by design. I've not found a queue solution that would not require a whole file re-write.
