### ISSUE TITLE
Support ramsey/uuid ^4

### ISSUE THREAD

**Issue by someniatko** [php-enqueue/enqueue-dev#1057]
`composer.json` is currently locked to `ramsey/uuid` 2 and 3. You use this package only for generation of v4 UUIDs, and this API has not changed in the 4th major version of the library, so this should be a trivial change of the `composer.json`.

**Comment by someniatko** [comment]
sorry, did not notice this change already landed onto the `master` branch. I always do mess up your main and dev repos :)

**Comment by atrauzzi** [comment]
Has this been resolved? I went to install enqueue today and wasn't able to because of the pinned version.

**Comment by Gounlaf** [comment]
Fixed (but not merged) in #1057
