### ISSUE TITLE
How to create queue for enqueue:transport:consume

### ISSUE THREAD

**Issue by raph1mm** [php-enqueue/enqueue-dev#1062]
Hello,

I'm trying to consume RabbitMQ message from different application (no Enqueue there) using Symfony Bundle. 

I've implemented processor which implements QueueSubscriberInterface and I'm using console command:

` enqueue:transport:consume
`

Just one piece missing. I don't want to create manualy queue and binding with exchange, I want application do this for me. I cannot use --setup-broker obviously. Any ideas?

**Comment by makasim** [comment]
The feature has never been implemented: https://github.com/php-enqueue/enqueue-dev/issues/589. 

You should write a command in your app that calls declareQueue\declareExchange\bind methods on an AMQP channel.
