### ISSUE TITLE
Creating a delayed message creates a queue with hard coded settings

### ISSUE THREAD

**Issue by ToniHarri** [php-enqueue/enqueue-dev#1063]
I can create a queue that I can set to be auto-deleted when it's not needed. BUT with producer with auto delay strategy the producer creates a new queue with a name and settings I cannot choose. Most importantly, the auto-delete is the one I miss.

Would it be a solution if the [RabbitMqDlxDelayStrategy::delayMessage()](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-tools/RabbitMqDlxDelayStrategy.php) would use the original destinations flags and arguments? Currently it seems that it only takes the queue name or topic name from the original destination. 

In a beautiful world, I would allow to set those arguments and flags the way I want in each case.  Preferably the queue name too. Maybe just new setArguments() function and setFlags() into the [AmqpProducer](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-bunny/AmqpProducer.php) -class?

**Comment by makasim** [comment]
I suspect there was a reason why we did not use auto-delete queues. But I don't remember the details or maybe there was not such a reason at all. 

Anyway. I'd suggest copy-pasting the strategy and adjusting it to solve your cases. 

The current strategy is good enough for most of the users. I doubt it is a good idea to extend delay API as there so many use cases out there we won't be able to cover them all and end up with  bloated API.
