### ISSUE TITLE
Is there any extended documentation for STOMP available?

### ISSUE THREAD

**Issue by atrauzzi** [php-enqueue/enqueue-dev#1066]
I'm looking to configure a STOMP connection and as I'm doing some digging on my options, I was reading [this issue](https://github.com/php-enqueue/enqueue-dev/issues/968) and stumbled on [this](https://github.com/versh23/enqueue-dev/blob/2b8ade32078af551ffc3d57f9b3a1fb1295cfe1b/pkg/stomp/Tests/StompConnectionFactoryConfigTest.php).

Looking at [the docs](https://php-enqueue.github.io/transport/stomp/), it seems fairly minimal.  Is there a better place to get an idea of what my options are when configuring STOMP connections?

**Comment by atrauzzi** [comment]
Not stale.

**Comment by atrauzzi** [comment]
Not stale.

**Comment by makasim** [comment]
That's all we've got for now.
