### ISSUE TITLE
Don't use slashes in and prefix queue name with type in STOMP

### ISSUE THREAD

**Issue by atrauzzi** [php-enqueue/enqueue-dev#1067]
I've been working with publishing to a STOMP queue and I've noticed that all my messages are prefixed with `/queue/`, which is going against my desired scheme for messages.

Looking at [`StompDestination`](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/stomp/StompDestination.php#L68), I see that both the prefix and the slashes are hard-coded.

It comes to mind that it probably shouldn't be coded as such because everyone can and should be allowed to have their own conventions around how they namespace jobs (`using.periods`, `maybe:colons`, `maybe/slashes`, `maybe\backslashes`, etc...).  Indeed, sometimes those conventions might be completely outside of their control! :sweat_smile:

**Comment by makasim** [comment]
We hardcoded them because of RabbitMQ. It needs it this way to properly route messages and that was the only broker we tested STOMP with. 

I guess you use another broker. Which one? 

The current values should stay there because of backward compatibility promise. Though, We should definitely add a way to configure them. 

Another idea is to use scheme like this `stomp+rabbitmq://`, `stom+activemq://` to switch to a property settings.

**Comment by atrauzzi** [comment]
Sounds good, I'm on ActiveMQ Artemis.

Maybe for now you can just detect the scheme `stomp+rabbitmq` and preserve the old behaviour, but a pure `stomp` scheme just bypasses prefixing altogether?

You still get the backwards compat, but that frees up the bare `stomp` scheme from rabbitmq specifics.  Would be easy enough to include a note in the release notes for rabbitmq users to update their connection strings?

**Comment by atrauzzi** [comment]
Not stale.

**Comment by atrauzzi** [comment]
Not stale.

**Comment by makasim** [comment]
> but a pure stomp scheme just bypasses prefixing altogether

I wish we could do it but we cannot as it would break existing projects that use `stomp` and assume there are prefixes. 

What we could do is to introduce new stomp+bare, or stomp-activemq schema that would work differently from current behavior

**Comment by makasim** [comment]
In next version (say 0.11.0) we could do it the way it should be.

**Comment by atrauzzi** [comment]
Hey @makasim, I just wanted to check to see if there's been any progress on this?

If not, is there any way I can fork the current stomp driver and modify it as I need?

**Comment by makasim** [comment]
It's a low priority project for me. So, dont expect much. I can review&merge PRs, do a release. That's it.

**Comment by makasim** [comment]
Feel free to fork this repository https://github.com/php-enqueue/stomp

**Comment by atrauzzi** [comment]
Totally understand, is it okay if I ping here if I have any bizarro questions?  I haven't had a look yet and I can't imagine I'm going to get really stumped.

Either way, thank you for the guidance so far. :heart:

**Comment by makasim** [comment]
Sure thing!

**Comment by atrauzzi** [comment]
Great.  If what I make is deemed worthwhile, it'll obviously be available to incorporate back into enqueue.

**Comment by atrauzzi** [comment]
PR opened!
