### ISSUE TITLE
Missing latest release version in Packagist

### ISSUE THREAD

**Issue by balabis** [php-enqueue/enqueue-dev#1082]
v0.10.2 release is missing in packagist.org.
Is something wrong or I am misunderstanding something?

**Comment by makasim** [comment]
That's most like not a bug. The release is created only if there are [some changes in this particular sub package](https://github.com/php-enqueue/enqueue-dev/blob/master/bin/release#L53).

**Comment by balabis** [comment]
Hm, but with this PR #1034, for example, there were changes in `redis` package, but this `redis` package is still v0.10.1 https://packagist.org/packages/enqueue/redis

**Comment by makasim** [comment]
[v0.10.2](https://github.com/php-enqueue/enqueue-dev/releases/tag/0.10.2) released on Mar 20
#1034 merged on Mar 26

**Comment by balabis** [comment]
Ok, my bad. Got confused because when you click to check the commits here https://github.com/php-enqueue/enqueue-dev/releases/tag/0.10.2, that PR is there. Will make sure to check the dates too now :) 
Thanks

**Comment by makasim** [comment]
https://github.com/php-enqueue/redis/releases/tag/0.10.3
