### ISSUE TITLE
[Symfony] Symfony 3.3 / 4.x compatibility for ProxyEventDispatcher

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#109]
On Symfony 3.3, I'm getting an error:

The "Enqueue\Bundle\Events\ProxyEventDispatcher" class extends "Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher" that is deprecated since 3.3, to be removed in 4.0. Use EventDispatcher with closure factories instead.

**Comment by makasim** [comment]
What can I say? it has to be fixed.

**Comment by dkarlovi** [comment]
Yeah, but seeing Symfony 4 is almost half a year away, it's not really high priority. :)
