### ISSUE TITLE
STOMP: "Was not possible to write frame!" causing zombie connections

### ISSUE THREAD

**Issue by atrauzzi** [php-enqueue/enqueue-dev#1097]
I'm able to somewhat reliably reproduce a situation where my queue worker in Laravel ends up no longer able to successfully connect to a broker.  It takes a few consecutive jobs before it happens, but eventually my one queue gets the exception `"Was not possible to write frame!"`.

Thereafter, any attempt to send messages to the same broker end up reporting the same exception. It seems like [the connection becomes corrupted here](https://github.com/stomp-php/stomp-php/blob/master/src/Network/Connection.php#L487) and no recovery is attempted by enqueue or the stomp-php library itself.

Is there any general advice on how to handle this or is this something that enqueue can catch and recreate its connection?

**Comment by atrauzzi** [comment]
@makasim - Can totally do a screen share with you on this one to get a better understanding if necessary. If the fix is simple enough, I'm always happy to contribute more. :smile:

**Comment by makasim** [comment]
I suspect that the server closes connection due to lack of activity. Do the jobs arrive one after another or is there any pause between them ?

**Comment by makasim** [comment]
There is a message to keep the connection alive https://github.com/stomp-php/stomp-php/blob/master/src/Network/Connection.php#L681

**Comment by atrauzzi** [comment]
I believe the keep alive / heartbeating is working as I'm able to sustain a connection for prolonged periods of time.  Even overnight! :laughing: 

This situation seems to be intermittent. Almost like if I trigger a message, wait a bit and then trigger another, I get the error.  Around 8-10 seconds.

For fun, I tried this in `StompProducer` and enqueue is able to "recover":

```
try {
            $this->stomp->send($destination->getQueueName(), $stompMessage);
        }
        catch (ConnectionException $ex) {
        
            dump("IT BORKED!!!!");
        
            $this->stomp->disconnect(true);
            $this->stomp->connect();
        
            $this->stomp->send($destination->getQueueName(), $stompMessage);
        }
```

**Comment by makasim** [comment]
You can add a consumption extension that calls [keepAlive](https://github.com/stomp-php/stomp-php/blob/master/src/Network/Connection.php#L681) method. Also, set lower receive timeout than connection timeout so the socket gives control back to PHP and consumption extensions are executed. That would do the trick. 

The solution does not solve all the possible cases. If you have a long-running job you might still run into the issue. More on it [here](https://github.com/php-enqueue/enqueue-dev/pull/658)

**Comment by atrauzzi** [comment]
That's for AMQP, does that still apply to STOMP?

Also, it's probably worth noting that this is for dispatching, not for the queue consumer itself.  So it's almost like keeping a connection open that's only used for dispatch is the scenario here...

**Comment by atrauzzi** [comment]
@makasim - Is there any way to apply an extension from Laravel?  I'm only seeing Symfony instructions in the docs.
