### ISSUE TITLE
[Symfony] Wrong registry?

### ISSUE THREAD

**Issue by KDederichs** [php-enqueue/enqueue-dev#1106]
Hey,

I'm trying to write some integration tests atm and I ran into this error:
`TypeError: Argument 1 passed to Enqueue\Doctrine\DoctrineConnectionFactoryFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given`
Not really sure why since I firstly do not even use the doctrine part of enqueue but I also ran this bundle in other Symfony projects without problems.

I'm running Symfony 5.1.7 (PHP 7.4)
Enqueue-Bundle: 0.10.3
Enqueue-AMPQ/Null: 0.10.4
DoctrineORM: 2.7.3
Doctrine-Bundle: 2.1.2

Any idea what might cause this?

**Comment by nivpenso** [comment]
it caused due by the incompatibility of doctrine/persistence package.
A PR (https://github.com/php-enqueue/enqueue-dev/pull/1105) for fixing this issue has already merged to dev repo and now we are waiting for the release to resolve this issue

**Comment by makasim** [comment]
Tagged 0.10.6 with the fix
