### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by markstory** [php-enqueue/enqueue-dev#1108]
With PHP 8 coming out soon, I was wondering if you had started thinking about adding PHP8 to your CI matrix and composer constraint?

I'm happy to help with that process and can get it started, but I'm not familiar with all of the transports that enqueue supports and would likely require assistance to get everything working.

**Comment by martinssipenko** [comment]
This is still relevant. @markstory is this something you are still willing to tackle? If yes then probably the first step should be to run CI on PHP 8.0 to see what happens and work from there.

**Comment by markstory** [comment]
@martinssipenko I can start with a CI bump.

**Comment by nicwortel** [comment]
Bad bot :robot:

**Comment by danilopolani** [comment]
Bad bot again! But, for reference:

- https://github.com/php-enqueue/enqueue-dev/pull/1131
- https://github.com/php-enqueue/enqueue-dev/pull/1132

**Comment by Steveb-p** [comment]
I spanked the bot and now he'll behave and not try to close this issue :police_officer:
