### ISSUE TITLE
[gps] Consuming message from external publisher in non-standard format

### ISSUE THREAD

**Issue by maciejzgadzaj** [php-enqueue/enqueue-dev#1117]
I have a Symfony app with `messenger` using `enqueue/gps` to send/consume Pub/Sub messages. Everything works fine as long as messages are published and consumed by my app - they are in the format expected by `GpsMessage`, with `body`, `properties` and `headers` at the top level. 

But now I need to also consume messages sent by an external publisher, which do not adhere to this format - talking specifically about messages sent by Gmail API Push Notifications, which look like this: `{"emailAddress": "user@example.com", "historyId": "9876543210"}` (https://developers.google.com/gmail/api/guides/push#receiving_notifications) - no `body`, no `properties` and no `headers`. 

Trying to consume a message like this, `GpsMessage` gives me an error `Notice: Undefined index: body`, and fails.

Would appreciate any advice how can I make this work?

**Comment by makasim** [comment]
I guess, the solution would be to make an attempt to parse message body and see weather it has `properties`, `headers`, `body` in it. 

If not, we can fallback and treat the body as body with empty properties and headers.

**Comment by makasim** [comment]
here https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/gps/GpsConsumer.php#L111

**Comment by maciejzgadzaj** [comment]
Ah, ok, thank you. Was hoping that it might be somehow doable with the current version. 

I'll look into necessary modifications.

**Comment by maciejzgadzaj** [comment]
Ok, here's a [first draft](https://github.com/php-enqueue/enqueue-dev/pull/1118). I'm testing it now with my app, and setting up repo env to run tests etc, but so far it seems to work ok. Thoughts?

**Comment by maciejzgadzaj** [comment]
Hi @makasim - is there anything preventing you from merging this?

**Comment by makasim** [comment]
It looks good. Last thing is CI complaing about code style https://travis-ci.org/github/php-enqueue/enqueue-dev/jobs/748125221

**Comment by maciejzgadzaj** [comment]
Yes, I've seen it, and I've chosen to ignore it - as it complains about the section which I haven't changed, and also, running the tests locally doesn't raise this issue at all. I guess we shouldn't really care about it here then?

**Comment by makasim** [comment]
I understand that the CS issue is irrelevant to your change. Some times it happens. 

Could you please make CI happy ? I am happy to merge PR once CI green

**Comment by maciejzgadzaj** [comment]
Sorry, got distracted with work (can you imagine!), and completely forgotten about this (thanks stale bot for the reminder!) Just rebased and repushed, all is nice and green now, into your hands then @makasim !

**Comment by makasim** [comment]
Thanks, merged.
