### ISSUE TITLE
Conflict between symfony/cache and php-enqueue/job-queue

### ISSUE THREAD

**Issue by nepster-web** [php-enqueue/enqueue-dev#1123]
https://github.com/php-enqueue/job-queue/blob/master/composer.json#L14
https://github.com/symfony/cache/blob/5.x/composer.json#L35

![изображение](https://user-images.githubusercontent.com/5681979/103889144-9bb98f80-50ee-11eb-958b-16edb6c81a23.png)

**Comment by ingo-zolar** [comment]
we have the same issue on our projects when upgrading to symfony 5.2 with the symfony cache component.
for 5.1 it is still fine so far.  please fix that!

**Comment by andrewmy** [comment]
Will be fixed with #1132
