### ISSUE TITLE
No installation procedure

### ISSUE THREAD

**Issue by mitmelon** [php-enqueue/enqueue-dev#1142]
Now i got the installation guide but how to set the redis instance

**Comment by Steveb-p** [comment]
Hi @mitmelon.

Installation procedure is available in the documentation as you've probably found.

As far as Redis instance installation goes, please refer to the official Redis documentation. They will always have the most current and up-to-date instructions.

If you're refering to package configuration, it would be easier to help if you could tell which package you're trying to work with.

And last of all, congratulations on your first issue.
Please do not remove / heavily modify the issue description, because it would be easier to follow for anyone who would've found this issue in the future.

**Comment by mitmelon** [comment]
> Hi @mitmelon.
> 
> Installation procedure is available in the documentation as you've probably found.
> 
> As far as Redis instance installation goes, please refer to the official Redis documentation. They will always have the most current and up-to-date instructions.
> 
> If you're refering to package configuration, it would be easier to help if you could tell which package you're trying to work with.
> 
> And last of all, congratulations on your first issue.
> Please do not remove / heavily modify the issue description, because it would be easier to follow for anyone who would've found this issue in the future.

Ok Thanks... On the redis... Do i have to run a cron on the consume class to receive the message sent

**Comment by mitmelon** [comment]
I keep getting this error trying to receive message from redis..

```
Fatal error: Uncaught Predis\Response\ServerException: ERR unknown command 'EVAL
' in C:\xampp\htdocs\IHMS\vendor\predis\predis\src\Client.php:370
Stack trace:
#0 C:\xampp\htdocs\IHMS\vendor\predis\predis\src\Client.php(335): Predis\Client-
>onErrorResponse(Object(Predis\Command\ServerEval), Object(Predis\Response\Error
))
#1 C:\xampp\htdocs\IHMS\vendor\predis\predis\src\Client.php(314): Predis\Client-
>executeCommand(Object(Predis\Command\ServerEval))
#2 [internal function]: Predis\Client->__call('eval', Array)
#3 C:\xampp\htdocs\IHMS\vendor\enqueue\redis\PRedis.php(61): call_user_func_arra
y(Array, Array)
#4 C:\xampp\htdocs\IHMS\vendor\enqueue\redis\RedisConsumerHelperTrait.php(112):
Enqueue\Redis\PRedis->eval('-- Get all of t...', Array, Array)
#5 C:\xampp\htdocs\IHMS\vendor\enqueue\redis\RedisConsumerHelperTrait.php(36): E
nqueue\Redis\RedisConsumer->migrateExpiredMessages(Array)
#6 C:\xampp\htdocs\IHMS\vendor\enqueue\redis\RedisConsumer.php(76): Enqueue\Redi
s\RedisConsumer->receiveMessage(Array, 5, 300)
#7 C:\xampp\htdocs\ in C:\xampp\htdocs\IHMS\vendor\enqueue\redis\PRedis.php on l
ine 63
```

**Comment by Steveb-p** [comment]
> Do i have to run a cron on the consume class to receive the message sent Or how do i setup a worker to constantly receive messages

Ideally you want to run this process via some sort of supervisord or a similar process (docker can be also used for that). In Windows OS I'm not really sure, but you could use solutions like cygwin or more recent WSL (Windows Subsystem for Linux) to run a supervisor process.

This basically causes the process to run all the time, without interruptions or duplicate processes that you would associate with cron / windows scheduler. If the process terminates, supervisord will usually start it up again (depends on supervisord's configuration).

> I keep getting this error trying to receive message from redis..
> ```
> Fatal error: Uncaught Predis\Response\ServerException: ERR unknown command 'EVAL
> ' in C:\xampp\htdocs\IHMS\vendor\predis\predis\src\Client.php:370
> ```

Check you Redis server version. It might be too low.

**Comment by mitmelon** [comment]
I think on windows scheduler will be my best option then
