### ISSUE TITLE
Cannot use amqp with PHP8

### ISSUE THREAD

**Issue by sandyandi** [php-enqueue/enqueue-dev#1144]
I get the following errors when using the bundle in a PHP8 container:
```
[LogicException]
To use given scheme "amqp" a package has to be installed. Run "composer req enqueue/amqp-bunny" to add it.
```
And I get the following errors when trying to install the `enqueue/amqp-bunny` package:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bunny/bunny[v0.4.0, ..., v0.4.4] require php ~7.0 -> your php version (8.0.1) does not satisfy that requirement.
    - enqueue/amqp-bunny 0.10.8 requires bunny/bunny ^0.4 -> satisfiable by bunny/bunny[v0.4.0, ..., v0.4.4].
    - Root composer.json requires enqueue/amqp-bunny 0.10.8 -> satisfiable by enqueue/amqp-bunny[0.10.8].
```
`bunny/bunny` already released `0.5` that adds [PHP8 support](https://github.com/jakubkulhan/bunny/blob/v0.5.0/composer.json#L28). Using that version could be an easy fix if it's compatible.

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/pull/1143

**Comment by nightlinus** [comment]
As of now it is not in any tag. Can we have a release for this changes as 0.10.8 states it support php8, but it is actually not compatible yet?

**Comment by Steveb-p** [comment]
@nightlinus use a forked repository instead. It's the way to go.

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

Tagged releases become public and cannot be easily changed afterwards. Marking something as compatible while it is not will inevitably lead to confusion.

**Comment by nightlinus** [comment]
> @nightlinus use a forked repository instead. It's the way to go.
> 
> https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository
> 
> Tagged releases become public and cannot be easily changed afterwards. Marking something as compatible while it is not will inevitably lead to confusion.

Thank you, i already use it such way, but i consider this as bug that 0.10.8 declare support of php 8, but for amqp it is not supporting it actually.
