### ISSUE TITLE
(Future) support php-amqplib/php-amqplib 3.0

### ISSUE THREAD

**Issue by someniatko** [php-enqueue/enqueue-dev#1145]
Current `php-amqplib/php-amqplib` version 2.x is in fact incompatible with PHP 8, and they actually specifically prohibit installing it on PHP8 [since 2.12.2](https://packagist.org/packages/php-amqplib/php-amqplib#2.12.2). However, a new version, `v3.0.0`, is soon planned for release, and the [release candidate](https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2) already exists.

However, `enqueue/amqp-lib` does only allow installing version `^2.10`, so it is not compatible with the upcoming version.
This means we in fact cannot use this transport in combination with PHP 8, so this issue relates to https://github.com/php-enqueue/enqueue-dev/issues/1108

**Comment by makasim** [comment]
PR is welcome

**Comment by keywinf** [comment]
FIY v3.0.0 has just been released

**Comment by masterjus** [comment]
https://github.com/php-enqueue/enqueue-dev/pull/1146

**Comment by makasim** [comment]
tag https://github.com/php-enqueue/amqp-lib/releases/tag/0.10.9
