### ISSUE TITLE
enqueue/job-queue comppatibility with doctrine/orm 2.8

### ISSUE THREAD

**Issue by GothShoot** [php-enqueue/enqueue-dev#1151]
Hello,

I am interested in using the package enqueue/job-queue in a project, but it is powered by PHP 8 and needs doctrine 2.8 to run on PHP 8.

It is possible to make it compatible with this version of ORM?

Thanks.

**Comment by makasim** [comment]
Lookf for some older versions (prior PHP8).

**Comment by GothShoot** [comment]
I can try for support doctrine 2.8 in a PR ?
Client already in PHP 8 in production.

**Comment by Steveb-p** [comment]
@GothShoot definitely. There should be little or no changes related to PHP8 itself, and especially if you already have a patched version for yourself.

**Comment by GothShoot** [comment]
I try to support 👍

**Comment by GothShoot** [comment]
See #1155 👷‍♂️
