### ISSUE TITLE
EnqueueBundle: ResetServicesExtension needs a new message to perform reset

### ISSUE THREAD

**Issue by djmarland** [php-enqueue/enqueue-dev#1156]
https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/Consumption/Extension/ResetServicesExtension.php

This extension implements `MessageReceivedExtensionInterface` so it runs when a new message is received.
When using the FingersCrossed Monolog handler this means that it requires a second message before logs will be output. If there is a time gap before the next message some important logs could be missed.

Would this extension be better off running _after_ a message is processed, such as implementing `PostMessageReceivedExtensionInterface` instead?

**Comment by makasim** [comment]
yeap, that makes sense to me.

**Comment by djmarland** [comment]
PR opened and linked
