### ISSUE TITLE
Support Connection name

### ISSUE THREAD

**Issue by Webonaute** [php-enqueue/enqueue-dev#1163]
https://github.com/supersmile2009/amqp-tools/commit/0742ee44a5bb118dd656ffc070f686da081f0ffa

is it possible to merge this patch so we can get get rid of this patch in our composer?
We use this since a year now to know which consumer is connected with which version of our api.

**Comment by makasim** [comment]
The patch looks good to me. I'll merge it once someone open PR on enqueue-dev repo.

**Comment by Webonaute** [comment]
here it is
