### ISSUE TITLE
Does enqueue auto removes message once consumed

### ISSUE THREAD

**Issue by mitmelon** [php-enqueue/enqueue-dev#1179]
I have a queue service that user uses to send their report to for processing... my question is this below

1) If Mr A. and Mr B. sends their report to the queue and the queue processes Mr A. report first, will enqueue(Redis) automatically removes Mr. A queue report from redis once its acknowledged using `$consumer->acknowledge($receive);` or i will have to remove it manually.

Initially i was using the `purgeQueue` method to remove consumed mesages but i discovered once i use this method, Once Mr. A report finish processing instead of the queue to move to Mr B. own it wont and when i checked the queue i can see that the queue is empty... So i suspect `purgeQueue` must have been clearing all the entire queue.

What is the best of doing this... Clearing Queue A once consume is completed then moving to B and the rest... Please help me...

**Comment by blondie101010** [comment]
The producer and server config determine when a message is removed, not the worker/consumer.

For your question about purgeQueue, 'purge' does refer to emptying completely.  That doesn't solve your problem and makes it much worse.
