### ISSUE TITLE
RdKafka: "Configuration property group.id is a consumer property..." warning

### ISSUE THREAD

**Issue by nikolaposa** [php-enqueue/enqueue-dev#1204]
`RdKafkaConnectionFactory` sets `group.id` configuration by default at this point: https://github.com/php-enqueue/rdkafka/blob/master/RdKafkaConnectionFactory.php#L106. However, this is a consumer-only config that should not be provided when creating Producer: https://github.com/php-enqueue/rdkafka/blob/master/RdKafkaContext.php#L96. Otherwise, `librdkafka` floods logs with this warning. From https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#configuration:

> It will also emit log warnings for deprecated and problematic configuration properties.

**Comment by MyDigitalLife** [comment]
This default value should be removed or a way to easily override the default config. Right now we are bombarded with waning messages. I'm willing to make a PR to fix this if we come to a better default config/easy way to update this.

At this point I'll need to just copy the factory and fix the issue or accept all the warnings.

**Comment by gam6itko** [comment]
You can write your own implementation of `ConnectionFactory` without `array_replace_recursive` section. Or you can pass the `RdKafkaContext` directly where it possible.
