### ISSUE TITLE
FIFO SNS

### ISSUE THREAD

**Issue by kate-simozhenko** [php-enqueue/enqueue-dev#1212]
Hello!
There are FIFO topics have been realized last year, but sns package doesn't have the ability to set FifoTopic attribute and MessageGroupId.
It would be great to add it

**Comment by makasim** [comment]
Yes, that would be great. Willing to submit a PR ?

**Comment by kate-simozhenko** [comment]
Yes, I would definitely like to submit a PR. I have made updates already. How can I create PR?

**Comment by makasim** [comment]
Fork this repo on github,
than git clone the fork to your computer
create branch
edit files
git commit
git push
go to github and create a PR. 


Something along these steps.

**Comment by kate-simozhenko** [comment]
OK, I see, thank you.
PR is created: https://github.com/php-enqueue/enqueue-dev/pull/1214
