### ISSUE TITLE
Is not possible to specify extra configurations like the timeout for AWS SDK Client

### ISSUE THREAD

**Issue by eortiz-tracktik** [php-enqueue/enqueue-dev#1213]
We are using enqueue with the symfony bundle and `snsqs` as the DSN.

AWS service are very reliable but we don't want to be affected by any possible network issues between our App and SNS, so we want to define some `timeout` and `connection_timeout` to the AWS Sdk client what is possible using the configuration:
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-http 

Right now is impossible to specify those values because even if they are passed down to:
- `\Enqueue\Sns\SnsConnectionFactory::establishConnection()`
- `\Enqueue\Sqs\SqsConnectionFactory::establishConnection()`

because the configuration used to initialise the AWS Sdk is defined on these methods and only takes some specified parameters from `$this->config` ignoring others that may be set.

**Comment by makasim** [comment]
Does adding timeout to the config solve your issue ?

**Comment by eortiz-tracktik** [comment]
@makasim yes, something like this will allow for it https://github.com/php-enqueue/enqueue-dev/pull/1216
