### ISSUE TITLE
RDKafka full support for PHP 8.1

### ISSUE THREAD

**Issue by Wirone** [php-enqueue/enqueue-dev#1234]
In theory, `enqueue/rdkafka` already supports PHP 8.1 (because of require `php: ^7.3|^8.0`), but [RDKafka extension supports PHP 8.1 in 6.0.0](https://pecl.php.net/package-info.php?package=rdkafka&version=6.0.0), which is not supported by the package itself (because of `ext-rdkafka: ^4.0|^5.0` requirement).

Please provide full support for PHP 8.1.

**Comment by makasim** [comment]
Could work on pull request ?

**Comment by Wirone** [comment]
If changing constraint by adding `|^6.0` is enough I can create PR, but I don't have enough knowledge about rdkafka and this package to go deeper 🙂

**Comment by Steveb-p** [comment]
Changing the constraint should be enough: https://github.com/arnaud-lb/php-rdkafka/releases/tag/6.0.0

**Comment by lucasrivoiro** [comment]
Please, when this update will be available for us? I have a new project and I wanna use this lib with rdkafka 6.0

**Comment by makasim** [comment]
This is available as dev version. Could you test it ?

**Comment by lucasrivoiro** [comment]
Here works fine on PHP 7.4 with RDKafka 6 and Kafka 3.1.0.

**Comment by makasim** [comment]
All changes have to be done in `php-enqueue/enqueue-dev`. `enqueue/rdkafka` is read-only mirror which I update from time to time manually.

**Comment by qkdreyer** [comment]
Can we get a release instead of the dev version ?

**Comment by qkdreyer** [comment]
Bump @makasim

**Comment by makasim** [comment]
@qkdreyer what do you expect from me?

**Comment by qkdreyer** [comment]
Wondering if we could get a released version on packagist

**Comment by Wirone** [comment]
@makasim please release [`enqueue/rdkafka`](https://packagist.org/packages/enqueue/rdkafka) 0.10.17 with this change so we can close the issue and use it properly (with a semver constraint, not with commit sha)?

**Comment by qkdreyer** [comment]
@Wirone you can use `enqueue/rdkafka:0.10.16` since it has been released on packagist on may

**Comment by Wirone** [comment]
@makasim sorry for the noise, Packagist tricked me:
![image](https://user-images.githubusercontent.com/600668/175238202-66919210-7508-4bb5-8d0d-706c643b71e0.png)
I did not verify it properly 🙄 

I'll close this now 👍
