### ISSUE TITLE
Release new enqueue/dbal version

### ISSUE THREAD

**Issue by dgafka** [php-enqueue/enqueue-dev#1302]
There was [a fix on master branch](https://github.com/php-enqueue/dbal/commit/4fe8bdd3aed2a79f10452751ffbc39a864b03508) to allows `doctrine/persistence 3.1`, yet it was never tagged.

@makasim @xNarkon can you release new version?

**Comment by xNarkon** [comment]
@makasim I think it would be really great to do it, it will allow to solve some deprecation issues in Symfony.

**Comment by makasim** [comment]
done

**Comment by dgafka** [comment]
thank you @makasim :)
