### ISSUE TITLE
php-enqueue/amqp-ext not support ext-amqp 2.0

### ISSUE THREAD

**Issue by jafaripur** [php-enqueue/enqueue-dev#1313]
amqp ext upgraded to version `2.0` and fix some error for PHP 8.2 and can not use the latest version bacause of `php-enqueue/amqp-ext` add requirement in composer.json `"ext-amqp": "^1.9.3"`.

**Comment by makasim** [comment]
PR is welcome

**Comment by jafaripur** [comment]
[Pull request sent](https://github.com/php-enqueue/amqp-ext/pull/2)

**Comment by AlexOstrovsky** [comment]
any update on this?

**Comment by makasim** [comment]
https://github.com/php-enqueue/amqp-ext/pull/2#issuecomment-1704985745

**Comment by AlexOstrovsky** [comment]
@makasim yeah I saw that but what is needed to get this to the main library?

**Comment by makasim** [comment]
A PR has to be opened in this repo (https://github.com/php-enqueue/enqueue-dev), not amqp-ext (https://github.com/php-enqueue/amqp-ext)

**Comment by AlexOstrovsky** [comment]
@makasim I opened PR #1320 to this repo

**Comment by AlexOstrovsky** [comment]
@makasim when sould we expect new release so we can start using this?
