### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by madmortigan1** [php-enqueue/enqueue-dev#1325]
Hi,

Can you please release a version that support symfony 7.

Thank you,

**Comment by makasim** [comment]
Sorry, I cannot. Someone has to contribute it.

**Comment by madmortigan1** [comment]
Thank you very much for your support up to today,
I will update the code to use Symfony built in messenger.

Happy new year

**Comment by makasim** [comment]
Happy new year
