### ISSUE TITLE
Any plans to support symfony v7 components?

### ISSUE THREAD

**Issue by beeyev** [php-enqueue/enqueue-dev#1354]
Firstly, thank you for the amazing work on this project!

Are there any plans to support Symfony v7 components in this project?

I am asking because this package might be a blocker for other dependencies that require Symfony v7 components, so support for the latest version would be greatly beneficial for projects relying on this package.

For example [php-enqueue/simple-client](https://github.com/php-enqueue/simple-client) still has a dependency for `"symfony/config": "^5.4|^6.0"`

**Comment by igordeveloper** [comment]
Hi everyone. 

Is there a release date for a version for sf7? 
Is there a branch of this work where I can help with contribution?

I'm updating a project since Symfony 6 to 7 and now this point is blocking.

Thank you.
igor.

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/pull/1362

**Comment by makasim** [comment]
MR is more than welcome.
