### ISSUE TITLE
[amqp-ext] Server connection error

### ISSUE THREAD

**Issue by sergeyklay** [php-enqueue/enqueue-dev#157]
Unable to define connection parameters using array notation:

```php
$connectionFactory = new AmqpConnectionFactory([
    'host'      => '********.us-east-1.elb.amazonaws.com',
    'port'      => 5672,
    'vhost'     => '/',
    'login'     => '********',
    'password'  => '********',
    'persisted' => false,
]);
```

```php
$psrContext = $connectionFactory->createContext();

$messageTopic = $psrContext->createTopic('foo');
$messageTopic->addFlag(AmqpTopic::TYPE_TOPIC);
$psrContext->declareTopic($messageTopic);
```

> [AMQPConnectionException]
  Server connection error: 403, message: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile. - Potential login failure.

----

```php
$connectionFactory = new AmqpConnectionFactory(
    'amqp://********:********@********.us-east-1.elb.amazonaws.com:5672/%2f'
);
```

```php
$psrContext = $connectionFactory->createContext();

$messageTopic = $psrContext->createTopic('foo');
$messageTopic->addFlag(AmqpTopic::TYPE_TOPIC);
$psrContext->declareTopic($messageTopic);
```

All ok.

**Comment by makasim** [comment]
Could you please dump what is set to [config property](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-ext/AmqpConnectionFactory.php#L16). The dsn is parsed to array cuz amqp ext only supports it.

**Comment by sergeyklay** [comment]
@makasim I'll try tomorrow

**Comment by ASKozienko** [comment]
@sergeyklay  mistake is in your config - `pass` but not `password`

**Comment by sergeyklay** [comment]
Oh! I'm sorry

**Comment by c0deright** [comment]
For people like me finding this in 2019 or later and wondering why authentication still doesn't work with servers having the 'guest' user deleted:

The config-array has to use 'user' instead of 'login': https://github.com/php-enqueue/amqp-tools/blob/master/ConnectionConfig.php

```
$connectionFactory = new AmqpConnectionFactory([
    'host'      => '********.us-east-1.elb.amazonaws.com',
    'port'      => 5672,
    'vhost'     => '/',
    'user'      => '********',      // not 'login'
    'pass'      => '********',      // not 'password'
    'persisted' => false,
]);
```
