### ISSUE TITLE
Symfony 2.8 compatability issue

### ISSUE THREAD

**Issue by jenkoian** [php-enqueue/enqueue-dev#158]
[Symfony 2.8 doesn't support a maxDepth on `profiler_dump()`](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php#L40) so the profiler fails on Symfony 2.8 (the max depth got added in 3.2 https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/WebProfilerBundle/Twig/WebProfilerExtension.php#L82). We call this from [here](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/Resources/views/Profiler/panel.html.twig#L33) btw.

So think we either need to omit the max depth option for now, or remove 2.8 support (https://github.com/php-enqueue/enqueue-bundle/blob/master/composer.json#L15). Happy to submit a PR if you let me know which approach you'd prefer. 

Personally I think it'd be a shame to lose 2.8 support over such a minor thing so would opt for either removing the max depth option or if there is some way of detecting symfony version from twig switching the function call to include it conditionally.

**Comment by makasim** [comment]
Let's get rid of maxDepth option for now.
