### ISSUE TITLE
Symfony bundle doesn't work when sending commands

### ISSUE THREAD

**Issue by jenkoian** [php-enqueue/enqueue-dev#160]
I'm working with the symfony bundle but can't quite get it to go and think I may have found a bug (but quite possibly a user error!).

Basically I'm wondering if https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/DependencyInjection/Compiler/BuildClientRoutingPass.php#L37 is quite right?
from my understanding it will always only replace eventRoutes when they could actually be commandRoutes https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/RouterProcessor.php#L32

**Comment by makasim** [comment]
The command feature has been introduced recently and before we had only events here and there. 
So the commands works on top of events (for now, it may change in future) and there is a special topic `__command__` where all commands go. 

Could you please provide more info about what is not working?

**Comment by makasim** [comment]
Look at inside $this->extractSubscriptions method you can find there commands extraction code: https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/DependencyInjection/Compiler/ExtractProcessorTagSubscriptionsTrait.php#L49

**Comment by jenkoian** [comment]
@makasim will provide a rough patch which will hopefully better explain what I mean, will add a PR soon

**Comment by jenkoian** [comment]
@makasim rough patch added here: https://github.com/php-enqueue/enqueue-dev/pull/161 basically the command routes weren't being set on the router processor during compilation.

**Comment by makasim** [comment]
I am on it. looks like a bug
