### ISSUE TITLE
[amqp-lib][RabbitMQ] Publisher Confirms

### ISSUE THREAD

**Issue by crzdeveloper** [php-enqueue/enqueue-dev#206]
Would it be possible to implement [Publisher Confirms RabbitMQ Extension](https://www.rabbitmq.com/confirms.html#publisher-confirms)?

Thanks.

**Comment by makasim** [comment]
Sure, but amqp interop has to be extended first. https://github.com/queue-interop/amqp-interop/issues/9

**Comment by makasim** [comment]
Publisher Confirms is a RabbitMQ Extension of AMQP protocol. Going to hold off on this for now as I don't see a clear way to implement it.
