### ISSUE TITLE
[elastica] No response in 180 seconds

### ISSUE THREAD

**Issue by nolonolo** [php-enqueue/enqueue-dev#209]
Hi, I´m want to improve performand for  fos:elastica:populate command in my Symfony 2.8 project.
I´m trying to use enqueue/elastica-bundle but I can not get it to work.
My php version:
        PHP 7.0.16
My composer.json :

        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "aws/aws-sdk-php": "^3.19",
        "friendsofsymfony/elastica-bundle": "^4.0",
        "enqueue/elastica-bundle": "^0.7.3",
        "enqueue/fs": "^0.7.11"

My MicroKernel.php has the bundles registed:

        new Enqueue\Bundle\EnqueueBundle(),
	    new Enqueue\ElasticaBundle\EnqueueElasticaBundle(),
	    new FOS\ElasticaBundle\FOSElasticaBundle(),

And my fos_elastica.yml has the config:

    enqueue:
      transport:
        default: 'file://%kernel.root_dir%/../messages'
      client:
        traceable_producer:   false
        prefix:               enqueue
        app_name:             app
        router_topic:         default
        router_queue:         default
        router_processor:     enqueue.client.router_processor
        default_processor_queue: default
        redelivered_delay_time: 0
      consumption:
        # the time in milliseconds queue consumer waits if no message received
        idle_timeout:         0
        # the time in milliseconds queue consumer waits for a message (100 ms by default)
        receive_timeout:      100
      job:                  false
      async_events:
        enabled:              false
      extensions:
        doctrine_ping_connection_extension: false
        doctrine_clear_identity_map_extension: false
        signal_extension:     true
        reply_extension:      true

    fos_elastica:
      clients:
        default:
          host: "%elastic_host%"
          port: "%elastic_port%" 
    [...]

Previusly this instalation fos:elastica:populate commands works fine, but now I get the next message when run it:

    $ php app/console fos:elastica:populate
    Resetting junglebox
      [LogicException]
      No response in 180 seconds

Does you have any thoughts about what the problem?

**Comment by makasim** [comment]
Have you run `php bin/console enqueue:consume --setup-broker -vvv` command ?

**Comment by makasim** [comment]
or `$ ./bin/console enqueue:transport:consume enqueue_elastica.populate_processor -vvv `

**Comment by makasim** [comment]
@nolonolo have you got it working?

**Comment by nolonolo** [comment]
While I was running:
    php app/console fos:elastica:populate
I run:
 php app/console enqueue:consume --setup-broker -vvv

And the response was:

    [Enqueue\Consumption\Exception\LogicException]
    The pcntl extension is required in order to catch signals.


  Exception trace:
    () at 
    /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/Extension/SignalExtension.php:31
     Enqueue\Consumption\Extension\SignalExtension->onStart() at 
    /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/ChainExtension.php:28
     Enqueue\Consumption\ChainExtension->onStart() at 
    /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/ChainExtension.php:28
     Enqueue\Consumption\ChainExtension->onStart() at 
    /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/QueueConsumer.php:159
     Enqueue\Consumption\QueueConsumer->consume() at 
  
   
  /var/www/junglebox/api/vendor/enqueue/enqueue/Symfony/Client/ConsumeMessagesCommand.php: 
   105
     Enqueue\Symfony\Client\ConsumeMessagesCommand->execute() at 
  
  /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:266
     Symfony\Component\Console\Command\Command->run() at 
  
  /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:893
     Symfony\Component\Console\Application->doRunCommand() at 
  
  /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:204
     Symfony\Component\Console\Application->doRun() at 
  
  /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Ap
    plication.php:93
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at 
  
 /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:
    122
     Symfony\Component\Console\Application->run() at /var/www/junglebox/api/app/console:36

enqueue:consume [--message-limit MESSAGE-LIMIT] [--time-limit TIME-LIMIT] [--memory-limit MEMORY-LIMIT] [--setup-broker] [--idle-timeout IDLE-TIMEOUT] [--receive-timeout RECEIVE-TIMEOUT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<client-queue-names>]...

**Comment by nolonolo** [comment]
I has tried:
   `php app/console enqueue:transport:consume enqueue_elastica.populate_processor -vvv`
And the response was:


```

  [Enqueue\Consumption\Exception\LogicException]
  The pcntl extension is required in order to catch signals.


Exception trace:
 () at /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/Extension/SignalExtension.php:31
 Enqueue\Consumption\Extension\SignalExtension->onStart() at /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/ChainExtension.php:28
 Enqueue\Consumption\ChainExtension->onStart() at /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/ChainExtension.php:28
 Enqueue\Consumption\ChainExtension->onStart() at /var/www/junglebox/api/vendor/enqueue/enqueue/Consumption/QueueConsumer.php:159
 Enqueue\Consumption\QueueConsumer->consume() at /var/www/junglebox/api/vendor/enqueue/enqueue/Symfony/Consumption/ContainerAwareConsumeMessagesCommand.php:98
 Enqueue\Symfony\Consumption\ContainerAwareConsumeMessagesCommand->execute() at /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:893
 Symfony\Component\Console\Application->doRunCommand() at /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:204
 Symfony\Component\Console\Application->doRun() at /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:93
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/junglebox/api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /var/www/junglebox/api/app/console:36

enqueue:transport:consume [--message-limit MESSAGE-LIMIT] [--time-limit TIME-LIMIT] [--memory-limit 
   MEMORY-LIMIT] [--idle-timeout IDLE-TIMEOUT] [--receive-timeout RECEIVE-TIMEOUT] [--queue 
  [QUEUE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-
 interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> <processor-
  service>


```

**Comment by makasim** [comment]
The signal extension could be disabled in [enqueue config](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/config_reference.md) like this:

```yaml
enqueue:
  extensions:
    signal_extension: false
``` 

Though it is possible I would strongly suggest installing pcntl extension.

**Comment by nolonolo** [comment]
I´m going to try install pcntl extension

**Comment by nolonolo** [comment]
With pcntl enabled, commands starts to work. But populing sometimes third, sometimes fourth type, I got the same Exception:
```
[LogicException]
  No response in 180 seconds
```
Outputs are:

```
 php app/console fos:elastica:populate
Resetting indexname
 2500/2500 [============================] 100%
Populating indexname/accesscontrolRefreshing junglebox
 2500/2500 [============================] 100%
Populating indexname/agenciesRefreshing junglebox
 2500/2500 [============================] 100%
Populating indexname/categoriesRefreshing junglebox
 2500/2500 [============================] 100%
Populating indexname/countriesRefreshing junglebox
   2500/785039 [>---------------------------]   0%
Populating indexname/courses

  [LogicException]
  No response in 180 seconds


fos:elastica:populate [--index [INDEX]] [--type [TYPE]] [--no-reset] [--offset OFFSET] [--sleep SLEEP] [--batch-size BATCH-SIZE] [--ignore-errors] [--no-overwrite-format] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

```
  Command Output: php app/console enqueue:transport:consume enqueue_elastica.populate_processor -vvv


```
[debug] Payload: '{"reset":true,"skip_indexable_check":false,"real_populate":true,"batch_size":2500,"clear_object_manager":true,"debug_logging":true,"ignore_errors":false,"offset":707500,"query_builder_method":"getCoursesListQueryBuilder","sleep":0,"indexName":"junglebox","typeName":"courses"}'
[info] Message processed: enqueue.ack
[debug] [ReplyExtension] Send reply to "tmp-q-59d3a01948f698.88390017"
[info] Message received from the queue: fos_elastica_populate
[debug] Headers: array (
  'content_type' => 'application/json',
  'message_id' => 'd1bb4e4d-5de7-4c71-ac7b-30c68d8c882e',
  'timestamp' => 1507041305,
  'reply_to' => 'tmp-q-59d3a019489a97.27818968',
  'correlation_id' => '863f416d-12be-4257-9d2a-ab2ffc0fbffa',
)
[debug] Properties: array (
  'enqueue.topic_name' => '__command__',
  'enqueue.command_name' => 'fos_elastica_populate',
  'enqueue.processor_name' => 'fos_elastica_populate',
  'enqueue.processor_queue_name' => 'fos_elastica_populate',
)
[debug] Payload: '{"reset":true,"skip_indexable_check":false,"real_populate":true,"batch_size":2500,"clear_object_manager":true,"debug_logging":true,"ignore_errors":false,"offset":705000,"query_builder_method":"getCoursesListQueryBuilder","sleep":0,"indexName":"junglebox","typeName":"courses"}'

```

When fos:elastica:populate launch the Exception, the consume command still working some time. But finally launch the next Exception:




```
[debug] Payload: '{"reset":true,"skip_indexable_check":false,"real_populate":true,"batch_size":2500,"clear_object_manager":true,"debug_logging":true,"ignore_errors":false,"offset":675000,"query_builder_method":"getCoursesListQueryBuilder","sleep":0,"indexName":"junglebox","typeName":"courses"}'


  [Symfony\Component\Debug\Exception\OutOfMemoryException]
  Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 1134592 bytes)


Exception trace:
 () at /var/www/junglebox/api/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php:195

enqueue:transport:consume [--message-limit MESSAGE-LIMIT] [--time-limit TIME-LIMIT] [--memory-limit MEMORY-LIMIT] [--idle-timeout IDLE-TIMEOUT] [--receive-timeout RECEIVE-TIMEOUT] [--queue [QUEUE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> <processor-service>
```

**Comment by makasim** [comment]
Consumers are long-running processes and they are supposed to work for a long time. 

* They are not aware of fos populate command. So if it exists they would still wait for messages. That's correct. 
* Make sure you clean memory after a consumer has processed a message. There is an extension for Doctrine. If you use make sure you enabled it.
* Considere adding `--time-limit` or `--memory-limit` options. In prod a consumer has to be restarted once it exits.

**Comment by nolonolo** [comment]
Consumers are working fine in my proyect. I can solve in php.ini PHP memory problems.
But, I have problems when populate command thows: `[LogicException] response in 180 seconds`
Because i need start all popùlate process again.
Now, I am triying launch populate with some modifications in enqueue vendor and Its works:
I have increased an sleep and limitTime in `enqueue/elastica-bundle/Elastica/AsyncDoctrineOrmProvider.php  Line 58` 
```
        $limitTime = time() + 1000;
        while ($promises) {
            foreach ($promises as $index => $promise) {
                if ($message = $promise->receiveNoWait()) {
                    unset($promises[$index]);

                    $errorMessage = null;
                    if (false == $message->getProperty('fos-populate-successful', false)) {
                        $errorMessage = sprintf(
                            '<error>Batch failed: </error> <comment>Failed to process message %s</comment>',
                            $message->getBody()
                        );
                    }

                    if ($loggerClosure) {
                        $loggerClosure($options['batch_size'], $nbObjects, $errorMessage);
                    }

                    $limitTime = time() + 1000;
                }

                sleep(5);

                if (time() > $limitTime) {
                    throw new \LogicException(sprintf('No response in %d seconds', 1000));
                }
            }
        }
```
