### ISSUE TITLE
[Symfony Bundle] Configuration

### ISSUE THREAD

**Issue by sgiusto** [php-enqueue/enqueue-dev#210]
I cannot understand how to have multiple processors for different topics on the same queue
Or how to setup multiple queues and have each one its own processor

**Comment by makasim** [comment]
having several processors on the same is the default behavior. Have you read the doc https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/quick_tour.md ?

**Comment by sgiusto** [comment]
Hello,

I read the docs.

I have this configuration:

 

App\config.yml

 

enqueue:
        transport:
            default: dbal
            dbal:
                connection:
                  driver:   "%database_driver%"
                  host:     "%database_host%"
                  port:     "%database_port%"
                  dbname:   "%database_name%"
                  user:     "%database_user%"
                  password: "%database_password%"
                  charset:  UTF-8

        client:
            prefix: cust_report
            app_name: cust_app
            router_queue: cust
            default_processor_queue: cust
            router_processor: 'mmpoint_cust.report_provvigioni_message_processor'

 

Backoffice\services.yml

mmpoint_cust.report_provvigioni_message_processor:
    class: 'MMPoint\Cust\BackofficeBundle\Processor\ReportProvvigioniProcessor'
    arguments:
        logger: "@logger"
        rpm: "@mmpoint_cust.report_provvigioni_manager"
    tags:
        - { name: 'enqueue.client.processor', topicName: 'ReportProvvigioni' }

 

backoffice\ReportProvvigioniProcessor

public static function getSubscribedTopics()
{
    return [“ReportProvvigioni”];
}

 

 

Main\services.yml

    mmpoint_cust.init_users_processor:
        class: 'MMPoint\Cust\MainBundle\Processor\InitUsersProcessor'
        tags:
            - { name: 'enqueue.client.processor', topicName: 'dummy' }

 

Main\InitUsersProcessor

public static function getSubscribedTopics()
{
    return ['dummy'];
}

 

I consume messages using php app\console enqueue:consume --setup-broker --env=dev -vvv

 

if I enqueue a not managed message (nor ‘dummy’ nor ‘ReportProvvigioni’) the message is acknowledged and disappears….

If I enqueue ReportProvvigioni message it is handled correctly (and is also acknowledged by the phantom processor)

If I enqueue dummy message, it is handled by ReportProvvigioniProcessor (that rejects it) and by the phantom processor

 

Another problem is that the dbal connection parameters are ignored. The default doctrine connection is used…

BR

  Stefano

 

 

Da: Maksim Kotlyar [mailto:notifications@github.com] 
Inviato: lunedì 2 ottobre 2017 10.20
A: php-enqueue/enqueue-dev
Cc: Stefano Giusto - Multimedia Point Srl; Manual
Oggetto: Re: [php-enqueue/enqueue-dev] [Symfony Bundle] Configuration (#210)

 

having several processors on the same is the default behavior. Have you read the doc https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/quick_tour.md ?

**Comment by sgiusto** [comment]
I changed the configuration removing part of the client configuration:
``` yaml
client:
    prefix: mmpoint
    app_name: app
```
and added queue names in processor classes:
``` php
    public static function getSubscribedTopics()
    {
        return ['dummy' => ['queueName' => 'Init']];
    }
```
now queues seem to be ok.
```
php app\console enqueue:queue
Found 3 destinations

+-------------+---------------------+----------------------------------------------------+
| Client Name | Transport Name      | processors                                         |
+-------------+---------------------+----------------------------------------------------+
| Init        | mmpoint.app.init    | mmpoint_app.init_users_processor                  |
+-------------+---------------------+----------------------------------------------------+
 |Report      | mmpoint.app.report  | mmpoint_app.report_provvigioni_message_processor
 |            |                     | mmpoint_app.report_provvigioni_message_processor
 |            |                     | mmpoint_app.report_provvigioni_message_processor
|             |                     | mmpoint_app.report_provvigioni_message_processor  |
+-------------+---------------------+----------------------------------------------------+
| default     | mmpoint.app.default | enqueue.client.router_processor                    |
+-------------+---------------------+----------------------------------------------------+
```

my problem is --> how to submit messages to the queues? all messages are sent to default queue.
how to remove default queue?

**Comment by makasim** [comment]
There is a router which first receives the messages and routes them to all subscribed processors. 

It might be overkill to have our own router for such brokers as RabbitMQ but there are plenty of "brokers" like redis, dbal, fs which don't have built-in routing capabilities. 

There is no way to bypass router for events but commands could do it if properly configured ((example)[https://github.com/php-enqueue/enqueue-elastica-bundle/blob/6793ece0173d22ddd5c16a815ae1dd2d89f8b2c7/Async/ElasticaPopulateProcessor.php#L71]).

**Comment by sgiusto** [comment]
Ok. Got it. but why default router acknowledges unknown messages? if these messages are to be consumed by other app?

How can I submit messages to different queues using client?

**Comment by makasim** [comment]
> Ok. Got it. but why default router acknowledges unknown messages? if these messages are to be consumed by other app?

If you want to make apps talk to each other you need a transport that supports [message bus](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/client/supported_brokers.md) feature. Unfortunately, there is no way to implement it for Doctrine DBAL. Remember it is not real MQ broker.

**Comment by makasim** [comment]
> How can I submit messages to different queues using client?

The client works with topics and commands a high-level abstraction. You cannot send a message to transport queue directly. 


Though. You can still take transport and send a message to whatever queue you want.

**Comment by sgiusto** [comment]
So if you have multiple queues you have to use the transport and not the client
correct?

**Comment by makasim** [comment]
@sgiusto You can have multiple queues inside one app. That's correct and should work right now. 

but in order to talk to other apps a transport must support [message bus](http://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageBus.html) feature and DBAL does not support it and never would.

**Comment by sgiusto** [comment]
Thank you. Got it.

About other apps I was meaning other apps developed by us and using dbal.

For full interoperability with other platform we will go for sure with a real message bus.

 

 

Da: Maksim Kotlyar [mailto:notifications@github.com] 
Inviato: martedì 3 ottobre 2017 16.35
A: php-enqueue/enqueue-dev
Cc: Stefano Giusto - Multimedia Point Srl; Mention
Oggetto: Re: [php-enqueue/enqueue-dev] [Symfony Bundle] Configuration (#210)

 

@sgiusto <https://github.com/sgiusto>  You can have multiple queues inside one app. That's correct and should work right now.

but in order to talk to other apps a transport must support message bus <http://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageBus.html>  feature and DBAL does not support it and never would.

**Comment by makasim** [comment]
feel free to re-open if there is something left

**Comment by tom10271** [comment]
How to tell enqueue to use a standalone topic? I think it is a bad idea to put all messages into the same queue. 

When I handle messages of topic A and it will also push messages of topic B, consider there are millions of topic A's messages, messages of topic B will be pending for a long peroid of time and they need to wait until all topic A messages cleared. 

Another question:
Is enqueue recieve message only but not acknowledging it to MQ?

**Comment by tom10271** [comment]
The documentation for Symfony is unclear, things mentioned in enqueue's document are not mentioned in Symfony bundle's one. All I want is one topic for one queue, it might be mentioned in the doc, but I really cannot find it.
