### ISSUE TITLE
[Symfony Bundle] Queue Symfony Commands (question)

### ISSUE THREAD

**Issue by jverdeyen** [php-enqueue/enqueue-dev#213]
Are there any future plans for an integration of a queue for console command execution?
To run and schedule Symfony console commands as background jobs with enqueue.

Kind of functionality that [JMSJobQueueBundle](https://github.com/schmittjoh/JMSJobQueueBundle) has.

I would like to integrate this into the enqueue Symfony Bundle or create a separate extension bundle for this.

👍🏼 Thanks!

**Comment by makasim** [comment]
I am going to write a blog post that explains how to do it. 

For now, I can only suggest you look at code snippets that I've prepared for the blog post:

* https://github.com/php-enqueue/enqueue-sandbox/blob/cf3fc1bede66bab3bb32702ca9d044cd52db14a5/symfony/src/AppBundle/Controller/DefaultController.php#L134
* https://github.com/php-enqueue/enqueue-sandbox/blob/cf3fc1bede66bab3bb32702ca9d044cd52db14a5/symfony/src/AppBundle/Async/RunCommandProcessor.php#L12

**Comment by makasim** [comment]
It is worth looking at `enqueue/job-queue`. It provides similar features plus some more advanced like sub jobs handling and exclusive job guaranty

**Comment by jverdeyen** [comment]
Thanks! Very helpful!

**Comment by makasim** [comment]
feel free to re-open if there is something left.

**Comment by jverdeyen** [comment]
We could develop some defaults in the bundle? A job producer with an easy/basic interface and a default processor?

**Comment by makasim** [comment]
@jverdeyen  I don't mind

**Comment by Xymanek** [comment]
I would like to switch away from jms job due to very stale development (eg. [this](https://github.com/schmittjoh/JMSJobQueueBundle/issues/178) and [this](https://github.com/schmittjoh/JMSJobQueueBundle/issues/182)). This feature would really nice

**Comment by makasim** [comment]
@Xymanek for this issue https://github.com/schmittjoh/JMSJobQueueBundle/issues/178 we have this extension https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/Consumption/Extension/DoctrinePingConnectionExtension.php. You just have to enable it in the config.

**Comment by Xymanek** [comment]
What I meant is that it wasn't merged there even though I made a PR - that's why I want to switch to this library. But lack of standardized/built-in support for queuing symfony commands is a deal-breaker for me - the app is built around it...

**Comment by Xymanek** [comment]
If @jverdeyen (or anybody) is not working on this PR, I can try to make one at the end of next week

**Comment by makasim** [comment]
I prefer to keep all message processing logic inside a processor, calling a cli command from it is overkill but if people need it I don't mind adding it. 

@Xymanek You are free to go. Have a look at these files: 

* https://github.com/php-enqueue/enqueue-sandbox/blob/cf3fc1bede66bab3bb32702ca9d044cd52db14a5/symfony/src/AppBundle/Controller/DefaultController.php#L134
* https://github.com/php-enqueue/enqueue-sandbox/blob/cf3fc1bede66bab3bb32702ca9d044cd52db14a5/symfony/src/AppBundle/Async/RunCommandProcessor.php#L12

**Comment by Xymanek** [comment]
A big benefit in calling commands is that you get "fresh" container every time. While most of time it doesn't matter there are cases where it's really beneficial.

**Comment by jverdeyen** [comment]
I've implemented this in a project, but I can take some classes out and make them more extendable. 
There is a  `CommandJobCreator`  and `RunCommandProcessor`.
