### ISSUE TITLE
GPSTransportFactory registration is missing from EnqueueBundle

### ISSUE THREAD

**Issue by bwegrzyn** [php-enqueue/enqueue-dev#235]
I've registered the GPSTransportFactory in my own Symfony Bundle class, but it would be nice if it was added to the EnqueueBundle class so it was automatic.

https://github.com/php-enqueue/enqueue-dev/blob/bf31f1a2fca59c1811ae2f0a973de1d83b78e1e8/pkg/enqueue-bundle/EnqueueBundle.php#L88

**Comment by jverdeyen** [comment]
👍  I'm having the same issue, fixes it for me! @makasim any idea when merging?

**Comment by makasim** [comment]
fixed in https://github.com/php-enqueue/enqueue-dev/pull/239
