### ISSUE TITLE
Exception in message processor causes consumer to exit

### ISSUE THREAD

**Issue by bwegrzyn** [php-enqueue/enqueue-dev#240]
According to the [documentation](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/consumption/message_processor.md), it says that usually you do not need to catch exceptions in the message processor.

Currently, if an exception occurs, the consumer process exits completely instead of logging an error.

I can wrap my processors in a try/catch, but it would be a nice improvement to have the consumer automatically catch exceptions and log them.

**Comment by makasim** [comment]
That's expected behavior, a consumer has to [fail fast](https://en.wikipedia.org/wiki/Fail-fast) for various reasons.

We discussed that several times some time ago and came to a conclusion that this is the right behavior.

**Comment by bwegrzyn** [comment]
Ok, that makes sense. Maybe the documentation could be a little clearer on that?
