### ISSUE TITLE
[Symfony][Minor] profiler view when no messages collected during the request

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#243]
This is **really** super-minor, but no reason not to fix it as the fix is super-minor as well. :)

In Symfony profiler, Enqueue will output a header-only table if no messages were sent during the request. What all other profiler views do in this situation is something like this:

```html
<div class="empty">
    <p>No queries were performed.</p>
</div>
```

**Comment by makasim** [comment]
Could you please do a PR?

**Comment by dkarlovi** [comment]
Sure.
