### ISSUE TITLE
[Elastica Bundle] tag 0.8

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#253]
Latest Elastica bundle release requires 0.7, doesn't allow upgrade to 0.8.

Should release Elastica Bundle 0.8.

**Comment by makasim** [comment]
should be ok now (I forgot to tag a release with the change)- https://github.com/php-enqueue/enqueue-elastica-bundle/releases/tag/0.8.0

**Comment by dkarlovi** [comment]
Thank you @makasim.
