### ISSUE TITLE
On exception Context is not set 

### ISSUE THREAD

**Issue by pavkatar** [php-enqueue/enqueue-dev#259]
On exception thrown from one of the consumers, the Context, which is sent to all extensions is not populated with a message, queue, consumer, etc. 

```php
$context = new Context($this->psrContext);
$context->setLogger($logger);
$context->setPsrQueue($consumer->getQueue());
$context->setPsrConsumer($consumer);
$context->setPsrProcessor($currentProcessor);
$context->setPsrMessage($message);
```

This is code is in the callback, but when the callback exit, the context sent to $extension->onInterrupted() is empty. QueueConsumer.php (line: 240+)

**Comment by makasim** [comment]
the message is not set if [this](https://github.com/php-enqueue/enqueue-dev/blob/42443eeacba4408e0333969887f1978e0990834e/pkg/enqueue/Consumption/QueueConsumer.php#L274) condition is true.

it is definitely a bug
