### ISSUE TITLE
SetRouterPropertiesExtension does not work with SQS

### ISSUE THREAD

**Issue by iainmckay** [php-enqueue/enqueue-dev#261]
The [SqsDriver](https://github.com/php-enqueue/enqueue-dev/blob/7d8c3f84c570d4ca71685f8c0179a2d59661e93f/pkg/sqs/Client/SqsDriver.php#L88) creates queue names where dots (.) are replaced with a literal 'dot' string. [SetRouterPropertiesExtension](https://github.com/php-enqueue/enqueue-dev/blob/7d8c3f84c570d4ca71685f8c0179a2d59661e93f/pkg/enqueue/Client/ConsumptionExtension/SetRouterPropertiesExtension.php#L39) is checking that the queue it is being called is the router but [Config::createTransportQueueName](https://github.com/php-enqueue/enqueue-dev/blob/7d8c3f84c570d4ca71685f8c0179a2d59661e93f/pkg/enqueue/Client/Config.php#L118) creates an invalid queue name for SQS as it is not aware of the string replacement.

**Comment by makasim** [comment]
I believe the extension should use the driver's method [createQueue](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/DriverInterface.php#L40).

**Comment by iainmckay** [comment]
That would make sense and easy to implement, although it does seem a bit wasteful to create a `PsrQueue` instance on each invocation.

Possibly the name should be extracted in to a `createQueueName` method which `createQueue` uses. It looks like each driver would need updated for this though.

If you're happy, I can create a PR which updates the extension using `createQueue`.

**Comment by makasim** [comment]
PsrQueue is supposed to be as lightweight as possible. I don't see much problem with creating it.

**Comment by makasim** [comment]
> If you're happy, I can create a PR which updates the extension using createQueue.

That would be great.
