### ISSUE TITLE
Sending message problem with replyNeed argument through Amqp and Redis transports

### ISSUE THREAD

**Issue by imaximius** [php-enqueue/enqueue-dev#267]
Suppose we have two application that have installed php-enqueue. When I try to send a message from one to other application I have to run a send action twice. The steps what I did to reproduce the problem:
1. Run ./app/console enqueue:consume --setup-broker -vvv command for every application
2. Run sending action for the first time and look at console of application that was used to send a message. It returned a description of sent message, but there is nothing in console of application that must receive the message and send the answer. I havent got reply message, but got hanging request in my browser or console. After timeout browser or console writes "Rpc call timeout is reached without receiving a reply message"
3. Run the same action second time and get nothing in first application console (where I got a message description at the first time), but get message description in second application console (where I can see tha message was recieved and answer was sent). And eventualy I get result in thr browser or console. Important! I this step, after sending request second time I get message, that was sent in previous step,

Next I'll show all configurations, producers and processors of both applications. I used Enqueue Symfony bundle for my applications with next configs of both applications
```yml
enqueue:
    transport:
        default: "amqp"
        amqp:
            driver: ext
            host: "%env(RABBIT_HOST)%"
            port: "%env(RABBIT_PORT)%"
            user: "%env(RABBIT_USER)%"
            pass: "%env(RABBIT_PASSWORD)%"
            vhost: "%env(RABBIT_DEFAULT_VHOST)%"
            receive_method: basic_consume
    client:
        app_name: "message-bus"
```

Producer in sending application is
```php
<?php
namespace AcmeBundle\Service\Producer;

use Enqueue\Client\Message;

class RequestProducer {
    /** @var Producer */
    protected $producer;

    /**
     * RequestProducer constructor.
     * @param ProducerInterface $producer
     */
    public function __construct(ProducerInterface $producer)
    {
        $this->producer = $producer;
    }

    /**
     * Sent request and get response from a service
     *
     * @param $content
     * @return object
     */
    public function send($content)
    {
        $message = new Message($content);
        $response = $this->producer->sendCommand('currentAppName', $message, true)->receive(5000)->getBody();

        return $response;
    }
}
```

Processor in receiving application
```php
<?php
namespace AcmeBundle\Service\Processor;

use Interop\Queue\PsrProcessor;
use Interop\Queue\PsrMessage;
use Interop\Queue\PsrContext;
use Enqueue\Consumption\Result;
use Enqueue\Client\CommandSubscriberInterface;

class RequestProcessor implements PsrProcessor, CommandSubscriberInterface
{
    /**
     * {@inheritdoc}
     */
    public function process(PsrMessage $message, PsrContext $context)
    {
        return Result::reply(
            $context->createMessage(
                'This is an answer'
            )
        );
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedCommand()
    {
        return [
            'processorName' => 'currentAppName',
            'queueName' =>  'currentAppName',
            'queueNameHardcoded' => true,
            'exclusive' => true,
        ];
    }
}
```

When I put both processor and producer in one application they work perfect without wasting time and all request get response. If I put they in different applications I'll get situation described above

**Comment by makasim** [comment]
I am not sure but let's sort it out sooner than later: 

1. Where do you send messages from? a web process or cli, or from another consumer (processor)? 
2. Do you have at least two consumers?
3. Is a consumer being run while you send messages?

**Comment by makasim** [comment]
I tagged it as a question, for now, cuz RPC seems quite well at our end. Could be changed in future if we find more evidence that it is a bug.

**Comment by imaximius** [comment]
I've reproduced more interesting details! Both applications have started "consume" cli commands and both application have the same "app_name" parameter, that why reply send every second request. If it'll be three applications It would be reply every third time etc. The problem is that every consumer catch messages and doesn't process them just because has different processor name.

According your questions:
1. I send request from controller (web process)
2. I have one consumer in every application (in this case two processors)
3. Yep, all consumers are run when I send messages

**Comment by makasim** [comment]
Could you post exact configs, processors' code and anything else you may find valuable. 
I'll try to repo it locally.

**Comment by imaximius** [comment]
Take a look at configs, processor and producer I posted above in the first message of this topic. By the way I can describe all steps to reproduce this problem on your side. 
1. Copy and place config to every test application (keep app_name as is)
2. Put processor in first application
3. Put producer in second application  
4. Run "consume" command on both apps with verbosity mode (-vvv) and take a look what will happens when you send the request
5. Send request from second application (where you placed producer on). Try it more than once
6. Watch both consoles and you can see that they start catching messages  one by one

**Comment by makasim** [comment]
Works for me. need more details

**Comment by makasim** [comment]
btw what is your environment: php , rabbitmq, enqueue versions?

**Comment by imaximius** [comment]
Ok, I'll try to account as much details as I can

Supposing we have 2 application (microservices). First is a User cabinet and second one is a Email application. We will try to send an Email message from User cabinet with Email application.

Let's begin from Cabinet application

1. Configuring the User cabinet
```yml
enqueue:
    transport:
        default: "amqp"
        amqp:
            driver: ext
            host: "rabbit"
            port: "5672"
            user: "guest"
            pass: "guest"
            vhost: "/"
            receive_method: basic_consume
    client:
        app_name: "message-bus"
```

2. Create processor Cabinet (The service can send a request to another service)
```php
<?php
namespace AcmeBundle\Service\Processor;

use Interop\Queue\PsrProcessor;
use Interop\Queue\PsrMessage;
use Interop\Queue\PsrContext;
use Enqueue\Consumption\Result;
use Enqueue\Client\CommandSubscriberInterface;

class RequestProcessor implements PsrProcessor, CommandSubscriberInterface
{
    /**
     * {@inheritdoc}
     */
    public function process(PsrMessage $message, PsrContext $context)
    {
        return Result::reply(
            $context->createMessage(
                'This is an answer'
            )
        );
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedCommand()
    {
        return [
            'processorName' => 'cabinetService',
            'queueName' =>  'cabinet.queue',
            'queueNameHardcoded' => true,
            'exclusive' => true,
        ];
    }
}
```
3. Create Controller that will produce a messages
```php
<?php

namespace ServiceBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use ServiceBundle\Entity\Mail;
use ServiceBundle\Form\MailTemplateType;
use ServiceBundle\Service\MailService;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use SwaggerBundle\Swagger\Annotation\Route as swgRoute;

/**
 * Class MailController
 */
class MailController extends Controller
{
    /**
     * @Route("/mail", name="mail-send")
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function mailSendAction(Request $request)
    {
        $producer = $container->get('enqueue.producer');
        $promise = $producer->sendCommand(
            'mailService', 
            'Hello there!', 
            $needReply = true
        );
        return new JsonResponse(
            $promise->getBody(),
             $promise->getStatusCode()
        );
    }
}
```

4. Run consume command
```bash
./app/console enqueue:consume --setup-broker
```
Now lets create Email application

1. Configuring the Email service
```yml
enqueue:
    transport:
        default: "amqp"
        amqp:
            driver: ext
            host: "rabbit"
            port: "5672"
            user: "guest"
            pass: "guest"
            vhost: "/"
            receive_method: basic_consume
    client:
        app_name: "message-bus"
```
2. Create Email processor (The service can send a request to another service)
```php
<?php
namespace AcmeBundle\Service\Processor;

use Interop\Queue\PsrProcessor;
use Interop\Queue\PsrMessage;
use Interop\Queue\PsrContext;
use Enqueue\Consumption\Result;
use Enqueue\Client\CommandSubscriberInterface;

class RequestProcessor implements PsrProcessor, CommandSubscriberInterface
{
    /**
     * {@inheritdoc}
     */
    public function process(PsrMessage $message, PsrContext $context)
    {
        return Result::reply(
            $context->createMessage(
                'This is an answer'
            )
        );
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedCommand()
    {
        return [
            'processorName' => 'mailService',
            'queueName' =>  'mail.queue',
            'queueNameHardcoded' => true,
            'exclusive' => true,
        ];
    }
}
```
3. Run consume command for Mail service
```bash
./app/console enqueue:consume --setup-broker
```

Eventually we try to send a message from User cabinet application to Mail application. Run from browser next route http://usercabinet.com/mail

According yours questions:
1. php version - 7.1
2. rabbitmq - 3.6.10 
3. enqueue - latest version

**Comment by makasim** [comment]
What does happen if you change the `app_name` in one of the apps?

**Comment by makasim** [comment]
Are there any exceptions? 
Have you tried adding `-vvv` to get more info?

**Comment by imaximius** [comment]
I've a bit changed previous message in this topic (just fix small inaccuracy in controller and added Symfony service declaration).

Regarding yours questions 
1. If I change app_name in one application, request didn't got any result and just hanging on
2. There is no any exceptions
3. Result of running command in target application (the application to where we send request)
``` bash
sf3 enqueue:consume --setup-broker -vvv
[debug] Set context's logger Symfony\Component\Console\Logger\ConsoleLogger
[debug] [AmqpDriver] Declare router exchange: enqueue.default
[debug] [AmqpDriver] Declare router queue: enqueue.messageService.default
[debug] [AmqpDriver] Bind router queue to exchange: enqueue.messageService.default -> enqueue.default
[debug] [AmqpDriver] Declare processor queue: enqueue.messageService.default
[debug] [AmqpDriver] Declare processor queue: message.queue
[info] Start consuming
```
4. Result in console of application from where we send request
```bash
[debug] Set context's logger Symfony\Component\Console\Logger\ConsoleLogger
[debug] [AmqpDriver] Declare router exchange: enqueue.default
[debug] [AmqpDriver] Declare router queue: enqueue.cabinetService.default
[debug] [AmqpDriver] Bind router queue to exchange: enqueue.cabinetService.default -> enqueue.default
[debug] [AmqpDriver] Declare processor queue: enqueue.cabinetService.default
[debug] [AmqpDriver] Declare processor queue: cabinet.queue
[info] Start consuming
[info] Message received from the queue: enqueue.cabinetService.default
[debug] Headers: array (
  'message_id' => '58eafe6e-18b2-4ca2-b356-ecdc3fd00215',
  'correlation_id' => '393743d9-01fe-4cce-8817-0226a3d5e6b9',
  'app_id' => '',
  'type' => '',
  'content_encoding' => '',
  'content_type' => 'text/plain',
  'expiration' => '',
  'priority' => 0,
  'reply_to' => 'amq.gen-Bwo17BQb7ahs0_YTm96NCg',
  'timestamp' => 1511351703,
  'user_id' => '',
)
[debug] Properties: array (
  'enqueue.topic_name' => '__command__',
  'enqueue.command_name' => 'messageService',
  'enqueue.processor_name' => 'Enqueue\\Client\\RouterProcessor',
  'enqueue.processor_queue_name' => 'default',
)
[debug] Payload: 'Hello there!'
[info] Message processed: enqueue.ack

```

**Comment by makasim** [comment]
@imaximius amqp ext version?

**Comment by imaximius** [comment]
@makasim amqp 1.9.3 stable

**Comment by makasim** [comment]
I think I've got to the bottom of the issue. First few clarifications:

* Different applications should have different app names.
* Commands are not supposed to be used via a message bus. A message bus is pure eventing technic and commands could be sent within a single app context. Especially, if you are relying on a reply.

Now, regarding the behavior you've experienced: 

In case the app names are the same. Both applications work on the same queue but each app has only one command. A queue has two consumers subscribed to it. Now a router processor of the first app receives the command message but it finds no subscribers and silently drops it. Then you send the second message and now another app consumer takes it (RabbitMQ uses round robin while routing messages to consumers). This router knows where to route it, so in the end, the message hits the right command processor and the reply is sent. 

In case the app names are not the same. The first app router always gets the command message and drops. So you end up seeing a timeout.

Solution:

* Check if it is possible to change a command call to an event call.
* If you still need a command and reply, use transport layer directly to send a message, directly to a queue.

**Comment by imaximius** [comment]
It is sad that I can't use your solution as message bus among microservices. It is very common case for this kind of architecture. I hoped the issue could be fixed and I will use your bundle for our application. Any way thanks for your help! I wish you good luck at working on this solution.

**Comment by makasim** [comment]
It could be used to send events.

**Comment by makasim** [comment]
If you send a command you are supposing there is someone who is responsible to process it. It is not what message bus is for.

**Comment by makasim** [comment]
and still I provided you with a solution.

**Comment by makasim** [comment]
You [should try to avoid synchronous calls in microservice oriented apps](https://martinfowler.com/articles/microservices.html#SynchronousCallsConsideredHarmful).

**Comment by imaximius** [comment]
Thanks a lot. I'll try to use transport layer to send a command and reply

**Comment by makasim** [comment]
@imaximius this service might be of help: https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/Resources/config/services.yml#L41

**Comment by imaximius** [comment]
@makasim Thanks! I'll try it and, I promise, I'll write a report :)

**Comment by kenanduman1988** [comment]
@imaximius please share report, it will very helful for other peoples, thank you
