### ISSUE TITLE
[dbal/symfony] Doctrine migrations (orm) on enqueue table

### ISSUE THREAD

**Issue by jverdeyen** [php-enqueue/enqueue-dev#271]
There is currently no way to use [Doctrine Migrations](https://github.com/doctrine/DoctrineMigrationsBundle) for the dbal enqueue table.
As it is defined in [DbalContext.php](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/dbal/DbalContext.php#L165).

Possible solution(s):
* Define an Entity when using Symfony
* ?

**Comment by makasim** [comment]
What would you like to migrate there?

**Comment by jverdeyen** [comment]
When the `enqueue` table definition has changes (extra fields, etc..)

**Comment by makasim** [comment]
What fields?

**Comment by makasim** [comment]
It is not supposed to be extended.

**Comment by jverdeyen** [comment]
No I understand that, but when the definition changes during versions of this package.

**Comment by makasim** [comment]
It would be fine to document it, providing migration SQL queries or so. Than you can incorporate them into your apps migration tool 

Or just simple sql files in a folder.

**Comment by lostfocus** [comment]
Yeah, it'd be nice to add it to an automated deploy script or something like that in this way. 👍

**Comment by makasim** [comment]
The easiest way would be to drop the table and re-create by calling `DbalContext:: createDataBaseTable()` [link](https://github.com/php-enqueue/enqueue-dev/blob/4cdaf222e8613ba7b16c1b5d4820afd4ccb73a5a/pkg/dbal/DbalContext.php#L165)

**Comment by lostfocus** [comment]
Yes, I know. But the next time someone in the project runs a `doctrine:migrations:diff` it will add a `DROP TABLE enqueue` because there's no entity. ¯\_(ツ)_/¯

**Comment by makasim** [comment]
@lostfocus is it really add a drop table statement, shouldn't Doctrine ignore what it hasn't created.

**Comment by lostfocus** [comment]
One would think so. :) But basically it checks the entities against the database and just drops everything without an entity. (I'm trying to write an entity class right now and for some reason it is really unwilling to take the `id` field as primary key.

**Comment by lostfocus** [comment]
Here, if someone needs it:

```
<?php
namespace AppBundle\Entity\Enqueue;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="enqueue",indexes={@ORM\Index(name="published_at", columns={"published_at"}),@ORM\Index(name="queue", columns={"queue"}),@ORM\Index(name="priority", columns={"priority"}),@ORM\Index(name="delayed_until", columns={"delayed_until"})})
 */
class Enqueue
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     */
    protected $id;

    /**
     * @ORM\Column(name="published_at", type="bigint")
     */
    protected $published_at;

    /**
     * @ORM\Column(name="body", type="text", nullable=true)
     */
    protected $body;
    /**
     * @ORM\Column(name="headers", type="text", nullable=true)
     */
    protected $headers;
    /**
     * @ORM\Column(name="properties", type="text", nullable=true)
     */
    protected $properties;
    /**
     * @ORM\Column(name="redelivered", type="boolean", nullable=true)
     */
    protected $redelivered;
    /**
     * @ORM\Column(name="queue", type="string")
     */
    protected $queue;
    /**
     * @ORM\Column(name="priority", type="smallint")
     */
    protected $priority;
    /**
     * @ORM\Column(name="delayed_until", type="integer", nullable=true)
     */
    protected $delayed_until;
    /**
     * @ORM\Column(name="time_to_live", type="integer", nullable=true)
     */
    protected $time_to_live;
}
```

**Comment by makasim** [comment]
There must be a way to tell Doctrine to ignore it. Maybe a special table comment or something like that...

**Comment by jverdeyen** [comment]
You can: https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#manual-tables

**Comment by makasim** [comment]
Feel free to re-open if there is something to discuss.

**Comment by ryancastle** [comment]
$ app/console enqueue:setup-broker
$ app/console doctrine:migration:diff
# Flip up()/down() methods in migration
# Add "enqueue" to schema_filter
