### ISSUE TITLE
[amqp-ext] Problem with consume messages

### ISSUE THREAD

**Issue by Bukashk0zzz** [php-enqueue/enqueue-dev#274]
When consume with enqueue/amqp-ext get error: "Notice: Undefined index:"
But when install enqueue/amqp-lib all works like expected.

I use RabbitMQ. Messages to it produce from lib and ext correct. Getting error only on consume
All error:

![screen shot 2017-11-21 at 10 25 35](https://user-images.githubusercontent.com/1908342/33061910-5ce1bba2-cea6-11e7-9b62-8ced216c52ab.png)

**Comment by makasim** [comment]
FYI: you need master version of the extension. There is no any stable version that could work (there had been bugs that were fixed in master only).

**Comment by Bukashk0zzz** [comment]
Now I build ext with
ENV RABBITMQ_VERSION v0.8.0
ENV PHP_AMQP_VERSION v1.9.0

So will try with PHP_AMQP_VERSION master and comeback.

**Comment by makasim** [comment]
We use it heavily so it is expected to work.

**Comment by Bukashk0zzz** [comment]
Works correct with PHP_AMQP_VERSION v1.9.3
Maybe add info to Readme that ext must be > 1.9.3 ?

**Comment by makasim** [comment]
Set correct ext version to composer require https://github.com/php-enqueue/enqueue-dev/pull/275/files
