### ISSUE TITLE
Set custom logger

### ISSUE THREAD

**Issue by kaanbasal** [php-enqueue/enqueue-dev#287]
https://github.com/php-enqueue/enqueue-dev/blob/3472424777b39d796ee100fec50e204f0ddcc33c/pkg/enqueue/Symfony/Client/ConsumeMessagesCommand.php#L126

I am trying to set my custom logger which implements and registered for LoggerInterface, using LoggerExtension but because of this line is setting logger it gives me this error:
The logger modification is not allowed

Can you please explain how can I set my custom logger?

**Comment by makasim** [comment]
Honestly, I don't know. We should find out a solution. Feel free to propose

**Comment by makasim** [comment]
@kaanbasal by design it should be possible to change logger Extension::onStart method, which is not at the moment. has to be fixed.

**Comment by kaanbasal** [comment]
I think the problem is hardcoding the 'new ConsoleLogger()' to the command itself. Instead of doing this way, LoggerInterface can be injected and used in the command.

On the other hand, IMO the proper way is adding configuration to support 'logger_extension'. In this case you can check if this extension is enabled and if so you can add it. @makasim wdyt?

**Comment by makasim** [comment]
The LoggerExtension should set a logger only if it was not set. https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Extension/LoggerExtension.php#L34


So you should be able to register your own LoggerExtension with a logger you want before the one created in the command itself. It should just work cuz default loggers are called before runtime ones.

**Comment by kaanbasal** [comment]
I did the same thing, and yes it sets the logger, but after that command is also trying to set the logger and it fires the exception mentioned earlier.

> The logger modification is not allowed

**Comment by makasim** [comment]
> The LoggerExtension should set a logger only if it was not set. https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Extension/LoggerExtension.php#L34

This line has to be fixed
