### ISSUE TITLE
How to track the message status?

### ISSUE THREAD

**Issue by slince** [php-enqueue/enqueue-dev#294]
Hello guys!

If my producer produces a message, then how can I track the status of the message? running, ack or reject.

Taosikai

**Comment by makasim** [comment]
With just message queue you cannot, it is async by nature. Of course, you can request a reply and wait for it, but the consumer side should know about it and send it back. 

You can try Enqueue Job Queue which is built on top of the message queue and provides you with statuses and other stuff.

**Comment by makasim** [comment]
Or implement tracking on the consumer side (in the processor)

**Comment by slince** [comment]
@makasim 
Hi， I'm going to write a cache item to the cache pool when the message is created, and modify the cache value as soon as the message is processed; but is there any events I can subscribe to?

**Comment by makasim** [comment]
You could tell more about what you are going to do. What are you going to write to cache and why it should be removed when a message is processed?

**Comment by slince** [comment]
I want write the status of message  to cache when a message is created. and if the mesage is processed i will change the cache value.   

//When a message is created in producer.
```
Cache::write('_a _message_id_status',  'NEW');
```

//Before processing in processor

```
Cache::write('_a _message_id_status'',  'RUNNING');
```

//After processing  in processor
```
Cache::write('_a _message_id_status'',  ACK/REJECT);
```

**Comment by makasim** [comment]
Instead of cache try using RPC https://github.com/php-enqueue/enqueue-dev/blob/master/docs/quick_tour.md#remote-procedure-call-rpc
