### ISSUE TITLE
[Question] SQS Re-queuing

### ISSUE THREAD

**Issue by rodnaph** [php-enqueue/enqueue-dev#295]
Hi, at the moment when re-queueing a message to SQS, the current message is deleted and a new message is re-posted...

https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/sqs/SqsConsumer.php#L142

This will mean any default visibility timeout on the queue is ignored as the *new* message will be re-read the next time a consumer polls (causing receive/requeue to be iterated on in quick succession).

I suppose a way to get around this would be to always set the visibility timeout on the enqueue consumer, are you able to point me in the direction of how I'd do this with a transport consumer and Symfony?  eg via...

`$> app/console enqueue:transport:consume myapp.consumer --queue my-queue`

Is this functionality intended though, or would it be better to (in the case of SQS) *not* delete the message and let SQS handle the re-receive?

Thanks

**Comment by makasim** [comment]
As for me, visibility timeout is good when a consumer failed without responding to the SQS server and it simply does not know where a message is still being processed or not. 

I don't see a reason why we should wait for a timeout if we already know that we should re-queue it. 

If you want to use visibility timeout simply do not catch an error (let a consumer die) and SQS will re-queue it. If you have to re-queue it immediately: catch an exception and do re-queue.

**Comment by rodnaph** [comment]
Ok thats fine.

I've always used visibility timeout to control rate of retry (and to reduce likelihood of duplicate concurrent processing). I guess you could use delay seconds for the same effect when re-queueing, right? Is there a use-case to re-queue for immediate processing?
