### ISSUE TITLE
Support AMQP 1.0 

### ISSUE THREAD

**Issue by dextervip** [php-enqueue/enqueue-dev#304]
Hey,

I am trying to use this lib with ActiveMQ however I noticed ActiveMQ only supports AMQP 1.0 and looks like the library doesn't supports AMQP 1.0. Any workaround for this?

**Comment by makasim** [comment]
Unfortunately, I cannot offer you anything. Enqueue support AMQP 0.9.1 version and 1.0 is completely different protocol. I haven't found anything matured related to AMQP 1.0 in PHP. So it seems like we have to write it from scratch.

**Comment by makasim** [comment]
added AMQP 1.0 to the list of nice to have transports: https://github.com/php-enqueue/enqueue-dev/issues/284

**Comment by dextervip** [comment]
Thanks @makasim, That would be great to have on radar. AWS just released a fully managed message broker and would be awesome to use it in PHP. Regards.

**Comment by makasim** [comment]
@dextervip yeah agree! That would great to have one.
