### ISSUE TITLE
How to set offset for Kafka?

### ISSUE THREAD

**Issue by magnum-ferox** [php-enqueue/enqueue-dev#305]
Hello.
I want to read the messages not from beginning, but from specified offset.

$consumer->acknowledge($message); and $consumer->reject($message); do not affect anything.

librdkafka-0.11.1-1.el7.x86_64
php-pecl-rdkafka-3.0.5-1.el7.remi.7.1.x86_64
kafka_2.11-0.11.0.2
PHP 7.1.12

queue-interop/queue-interop (0.6.1)
enqueue/rdkafka (0.8.11)

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/kafka.md#change-offset
