### ISSUE TITLE
Unable to populate Elasticsearch when using 2 different transport queues

### ISSUE THREAD

**Issue by kbsali** [php-enqueue/enqueue-dev#308]
I'm trying to speed up our populate command as described here : https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/speed-up-populate-command.md

We are already using the `redis` transport for "regular" queue management through `enqueue`,
I have added the `fs` transport for speeding up the populate process, but the `redis` seems to be the default transport, resulting in a `"Not implemented"` error (through `RedisContext::createTemporaryQueue`).

Anyway around this issue?

Thanks

**Comment by makasim** [comment]
@kbsali could you please try https://github.com/php-enqueue/enqueue-elastica-bundle/pull/8
