### ISSUE TITLE
[amqp-ext] Unrecognized options "login, password, delay_plugin_installed" under "enqueue.transport.rabbitmq_amqp

### ISSUE THREAD

**Issue by magensys** [php-enqueue/enqueue-dev#309]
When send a message with Magento Enqueue module and AMQP-Ext i get this error : 

`Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized options "login, password, delay_plugin_installed" under "enqueue.transport.rabbitmq_amqp" in /var/www/html/vendor/symfony/config/Definition/ArrayNode.php on line 319
`
Send a message with : 
`Mage::helper('enqueue')->send('a_topic', 'aMessage');`

My composer file : 
`{
    "require": {
        "magento-hackathon/magento-composer-installer": "~3.0",
        "enqueue/magento-enqueue": "*@dev",
        "enqueue/amqp-ext": "^0.8.11"
    },
    "extra": {
        "magento-root-dir": "."
    }
}`

php --ri amqp give : 
`amqp

Version => 1.9.3
Revision => release
Compiled => Jan  2 2018 @ 15:19:00
AMQP protocol version => 0-9-1
librabbitmq version => 0.8.0
Default max channels per connection => 256
Default max frame size => 131072
Default heartbeats interval => 0

Directive => Local Value => Master Value
amqp.host => localhost => localhost
amqp.vhost => / => /
amqp.port => 5672 => 5672
amqp.timeout => no value => no value
amqp.read_timeout => 0 => 0
amqp.write_timeout => 0 => 0
amqp.connect_timeout => 0 => 0
amqp.login => guest => guest
amqp.password => guest => guest
amqp.auto_ack => 0 => 0
amqp.prefetch_count => 3 => 3
amqp.channel_max => 256 => 256
amqp.frame_max => 131072 => 131072
amqp.heartbeat => 0 => 0
amqp.cacert => no value => no value
amqp.cert => no value => no value
amqp.key => no value => no value
amqp.verify => 1 => 1`

Stack Trace : 
`#	Time	Memory	Function	Location
1	0.0015	253472	{main}( )	.../test.php:0
2	6.7129	7417072	Enqueue_Enqueue_Helper_Data->send( )	.../test.php:27
3	6.7129	7417120	Enqueue_Enqueue_Helper_Data->getProducer( )	.../Data.php:47
4	6.7129	7417208	Enqueue_Enqueue_Helper_Data->getClient( )	.../Data.php:55
5	6.7655	7479792	Enqueue\SimpleClient\SimpleClient->__construct( )	.../Data.php:64
6	6.7656	7479912	Enqueue\SimpleClient\SimpleClient->buildContainer( )	.../SimpleClient.php:80
7	7.2987	8586736	Symfony\Component\DependencyInjection\ContainerBuilder->compile( )	.../SimpleClient.php:266
8	8.0862	9654336	Symfony\Component\DependencyInjection\Compiler\Compiler->compile( )	.../ContainerBuilder.php:753
`
Thank you,
Cedric.

**Comment by makasim** [comment]
Thanks for reporting it! Could you please try the fix?

**Comment by magensys** [comment]
Same error.
Therefore if we change config node we need to change setting node in
setting.xml
My solution is to adapt array keys in Enqueue/Enqueue/Helper/Data.php line
133

/**
 * @return array
 */
public function getRabbitMqAmqpConfig()
{
    return ['rabbitmq_amqp' => [
        'host' => Mage::getStoreConfig('enqueue/rabbitmq_amqp/host'),
        'port' =>  (int) Mage::getStoreConfig('enqueue/rabbitmq_amqp/port'),
        'user' => Mage::getStoreConfig('enqueue/rabbitmq_amqp/login'),
        'pass' => Mage::getStoreConfig('enqueue/rabbitmq_amqp/password'),
        'vhost' => Mage::getStoreConfig('enqueue/rabbitmq_amqp/vhost'),
        'lazy' => (bool) Mage::getStoreConfig('enqueue/rabbitmq_amqp/lazy'),

    ]];
}

Thanks,

*Cédric MAGNE*
Magento Certified Developer Plus
<http://www.magentocommerce.com/certification/directory/dev/10772/>


38 rue de Paris - 95570 Moisselles
M: c.magne@magensys.com - T: 0634449758 - W: magensys.com
<http://www.magensys.com/>


2018-01-02 17:45 GMT+01:00 Maksim Kotlyar <notifications@github.com>:

**Comment by makasim** [comment]
@magensys Should be fixed.

**Comment by magensys** [comment]
Ok it's looks good.

What is the difference between rabbitmq_amqp and amqp configuration ?

Thanks


*Cédric MAGNE*
Magento Certified Developer Plus
<http://www.magentocommerce.com/certification/directory/dev/10772/>


38 rue de Paris - 95570 Moisselles
M: c.magne@magensys.com - T: 0634449758 - W: magensys.com
<http://www.magensys.com/>


2018-01-03 9:26 GMT+01:00 Maksim Kotlyar <notifications@github.com>:

**Comment by makasim** [comment]
Amqp spec does define how to send prioritized or delayed messages. rabbitmq_amqp uses some RabbitMQ specific things to cover that features.

**Comment by magensys** [comment]
Ok thanks a lot for your work.

Regards

*Cédric MAGNE*
Magento Certified Developer Plus
<http://www.magentocommerce.com/certification/directory/dev/10772/>


38 rue de Paris - 95570 Moisselles
M: c.magne@magensys.com - T: 0634449758 - W: magensys.com
<http://www.magensys.com/>


2018-01-03 11:43 GMT+01:00 Maksim Kotlyar <notifications@github.com>:
