### ISSUE TITLE
Message body serialization other than JSON

### ISSUE THREAD

**Issue by aurimasniekis** [php-enqueue/enqueue-dev#316]
Hi guys, I was looking into `Enqueue\Client\Producer::prepareBody` and realized that there is no way to use custom serializer in this context apart JSON

**Comment by makasim** [comment]
Hi,

It is possible via client extension: https://github.com/php-enqueue/enqueue-dev/blob/master/docs/client/extensions.md

**Comment by aurimasniekis** [comment]
But validation of content type will be done before extensions are called: https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/Producer.php#L54

**Comment by makasim** [comment]
True, so we need an extra extension point, which is called before `prepareBody` method. Something like `prePrepareBody`.

**Comment by aurimasniekis** [comment]
Yep, would be awesome, as I am want to use serialized objects ;)

**Comment by makasim** [comment]
@aurimasniekis would be great if you could open a PR.

**Comment by aurimasniekis** [comment]
If we going to extend ExtensionInterface it will cause breaking changes...

**Comment by makasim** [comment]
@aurimasniekis in 0.9 you can do it by adding an extension with onPreSendEvent or onPreSendCommand method that converts body to a string. 

Take a look at default one https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/Extension/PrepareBodyExtension.php#L15
