### ISSUE TITLE
Redis backed SimpleClient high CPU Usage

### ISSUE THREAD

**Issue by bibstha** [php-enqueue/enqueue-dev#329]
While trying to play around with SimpleClient, I've noticed the CPU usage to get very high:

PHP: 7.1
Redis: 3.2.9

```php
<?php
include __DIR__.'/vendor/autoload.php';

use Interop\Queue\PsrMessage;
use Interop\Queue\PsrProcessor;
use Enqueue\Util\JSON;
use Enqueue\SimpleClient\SimpleClient;

$client = new SimpleClient('redis://127.0.0.1:6379?vendor=predis');

$client->bind('a_bar_topic', 'a_processor_name', function(PsrMessage $psrMessage) {
    var_dump(JSON::decode($psrMessage->getBody()));
    return PsrProcessor::ACK;
});

$client->consume();
```

And redis is running in the background.

When running the above php file, CPU usage for both redis-server and php becomes high:

<img width="359" alt="screen shot 2018-01-17 at 12 29 10 am" src="https://user-images.githubusercontent.com/51671/35027220-7fb2e590-fb1d-11e7-8eac-ca29e200cc99.png">

I noticed that --receive-timeout and --idle-timeout were added in https://github.com/php-enqueue/enqueue-dev/pull/193 but I am not sure how to send these parameters using SimpleClient.

Currently, I'm not able to use SimpleClient at all.

Thanks

**Comment by makasim** [comment]
> I noticed that --receive-timeout and --idle-timeout were added in #193 but I am not sure how to send these parameters using SimpleClient.

```
$client->getQueueConsumer()->setReceiveTimeout(5000); // 5 sec
$client->getQueueConsumer()->setIdleTimeout(1000); // 1 sec
```
