### ISSUE TITLE
Consumer ignores ctrl+c or anything else apart SIGKILL

### ISSUE THREAD

**Issue by aurimasniekis** [php-enqueue/enqueue-dev#332]
I am running simple consumer and then I try to close it ctrl+c it does nothing not shows in verbose mode that SignalExtension registered signal. Then I try to debug it then it works fine...

**Comment by aurimasniekis** [comment]
```sf enqueue:consume --setup-broker -vvv
2018-01-17T12:25:47+00:00 [debug] Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
2018-01-17T12:25:47+00:00 [debug] Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DumpListener::configure".
[debug] Set context's logger "Symfony\Component\Console\Logger\ConsoleLogger"
[debug] [AmqpDriver] Declare router exchange: enqueue.default
[debug] [AmqpDriver] Declare router queue: enqueue.app.default
[debug] [AmqpDriver] Bind router queue to exchange: enqueue.app.default -> enqueue.default
[debug] [AmqpDriver] Declare processor queue: enqueue.app.metadata.print_client_id
[debug] [AmqpDriver] Declare processor queue: enqueue.app.default
[info] Start consuming
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C[1]    65596 killed     `_symfony_console` enqueue:consume --setup-broker -vvv
➜  data git:(master) ✗```

**Comment by makasim** [comment]
Do you have pcntl extension installed?

**Comment by aurimasniekis** [comment]
Yes, otherwise this will throw exception

https://github.com/php-enqueue/enqueue-dev/blob/72b51c421b0387d8e9b0cb015eba6ae1a5884844/pkg/enqueue/Consumption/Extension/SignalExtension.php#L31

**Comment by makasim** [comment]
on linux?

**Comment by aurimasniekis** [comment]
```Darwin Aurimass-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64```

**Comment by makasim** [comment]
I've never run them on Mac directly. In a docker container (ubuntu) it works fine for me.

**Comment by makasim** [comment]
There wont be an exception, the extension is not registered if pcnt extension is not available https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/DependencyInjection/Configuration.php#L74

**Comment by aurimasniekis** [comment]
It tried to debug it and it register pcntl_signal and everything but never gets called handleSignal

**Comment by aurimasniekis** [comment]
If I debug slowly and call signal in the breakpoint then it works.

**Comment by aurimasniekis** [comment]
I figured if I disable "pcntl_async_signals" then it works fine. Will try to see why it does not work with async signals

**Comment by aurimasniekis** [comment]
Btw I am using rabbitmq with extension, and so far figured out that consume blocks signals for some reason.

**Comment by aurimasniekis** [comment]
OK so figured out that php-aqmp consume somehow blocks signals

**Comment by makasim** [comment]
That might be of help https://github.com/pdezwart/php-amqp#keeping-track-of-the-workers

I've never tried it myself though

**Comment by aurimasniekis** [comment]
So this issue affects all people who uses php-amqp extension with this component.

**Comment by makasim** [comment]
true,

**Comment by makasim** [comment]
Closing as there is nothing we can do with it.
