### ISSUE TITLE
Unrecognized option "amqp" under "enqueue.transport"

### ISSUE THREAD

**Issue by codreanulaurentiu** [php-enqueue/enqueue-dev#333]
The following configuration doesn't work (i've tried changing them but to no avail). Any ideas?

`enqueue:

    transport:

        default: amqp

        amqp:

            host: 'localhost'

            port: '5672'`

 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "amqp" under "enqueue.transport"

**Comment by makasim** [comment]
Do you have amqp transport installed, one of enqueue/amqp-ext, enqueue/amqp-lib, enqueue/amqp-bunny ?
