### ISSUE TITLE
[dbal] Consumer never fetches messages ordered by published time

### ISSUE THREAD

**Issue by f7h** [php-enqueue/enqueue-dev#340]
The database column "priority" is defined as NOT NULL if you use the DbalContext class to generate the schema.

The default priority of a DbalMessage is 0.

The fetchPrioritizedMessage() method from the DbalConsumer class fetches messages where the priority IS NOT NULL, so all of them.

Consequently, fetchMessage(), which fetches the oldest message first, is never called as long as there are any messages left in the queue.

The priority column should be nullable and the default priority should also be null in my opinion.

**Comment by makasim** [comment]
@f7h would you like to send us a PR?
