### ISSUE TITLE
[SQS] Allow custom aws endpoint configuration

### ISSUE THREAD

**Issue by gitis** [php-enqueue/enqueue-dev#352]
SqsConnectionFactory does not allow to provide custom endpoint configuration even though SqsClient supports it. Therefore there is no way to test other than aws implementations.

Ability to configure endpoint would provide the ability to consume messages locally using localstack or other similar services.

**Comment by makasim** [comment]
PR is very welcome.

**Comment by gitis** [comment]
it's open https://github.com/php-enqueue/enqueue-dev/pull/353
