### ISSUE TITLE
[DbalConsumer] Issue with id type

### ISSUE THREAD

**Issue by olix21** [php-enqueue/enqueue-dev#360]
Hi,

Trying to use a dbal connector from enqueue, we are facing some issues.

Migrating the `id` field definition from `int` to `guid` (https://github.com/php-enqueue/dbal/commit/256639177728e54925f8ee1026c0a353bf755d64#diff-2a7e2cb4e82b05f236840421016f498cR178) is great, but breaks this: https://github.com/php-enqueue/dbal/blob/master/DbalConsumer.php#L158

`'id' => Type::INTEGER`

should become

`'id' => Type::GUID`

**Comment by makasim** [comment]
Thanks for reporting. Could you work on PR that fixes it?

**Comment by makasim** [comment]
What database are you using?

**Comment by olix21** [comment]
Sure I can do a PR.

I'm using Mysql 5.6.34

**Comment by olix21** [comment]
Done: https://github.com/php-enqueue/enqueue-dev/pull/361
