### ISSUE TITLE
[Feature Request] Closure message body.

### ISSUE THREAD

**Issue by liverbool** [php-enqueue/enqueue-dev#366]
Hi, It very good if we can produce message (body) as `\Closure` 👍 .

Scenario: I need to produce message any where in my application flow. No limit place even that message contains `entity id` that need to persist to database before. For now i MUST to produce message that contains entity's id after it was persisted in db.

Unfortunately The `ExtensionInterface::onPreSend` can not solve my requirement case of it called after `Producer:prepareBody`.

Now i have done with this.

```php
class ClosureMessage extends Message
{
    public function getBody()
    {
        $body = parent::getBody();

        if ($body instanceof \Closure) {
            return call_user_func($body);
        }

        return $body;
    }

    /**
     * @param \Closure $closure
     *
     * @return Message
     */
    public static function create(\Closure $closure): Message
    {
        return new self($closure);
    }
}
```

PS> Only make sense when use `SpoolProducer`.

Thanks.

**Comment by makasim** [comment]
I am not sure we should support closure, but the ability to prepare message at a later stages is indeed a good idea and will be addressed while fixing https://github.com/php-enqueue/enqueue-dev/issues/316
