### ISSUE TITLE
How to prevent the creation of the `enqueue.app.default` queue?

### ISSUE THREAD

**Issue by ruudk** [php-enqueue/enqueue-dev#370]
Hi,

We are using EnqueueBundle for Symfony and love it 🙌 

One thing that I noticed, is that it automatically creates `enqueue.app.default`. Even when I manually remove the queue from the RabbitMQ admin it comes back.

Where is this done and how can I prevent it?

**Comment by makasim** [comment]
Do you have `--setup-broker` option?

**Comment by ruudk** [comment]
Yes, is that the issue 🙈 ?

**Comment by makasim** [comment]
The option adds SetupBrokerExtension which configures the broker, the info is taken from queue meta registry and topic meta registry.

**Comment by makasim** [comment]
You shouldn't avoid creating the queue because Enqueue Client heavily relies on it. You can turn the client off and use the transport that's the possible way.

**Comment by elazar** [comment]
> You can turn the client off and use the transport that's the possible way.

@makasim Can you provide or point to an example of doing it this way?

**Comment by makasim** [comment]
@elazar Use `enqueue.transport.context` service to send messages, and `enqueue:transport:consume` to consume them
