### ISSUE TITLE
Runtime exception "__construct()" references interface "Enqueue\Client\ProducerInterface" but no such service exists

### ISSUE THREAD

**Issue by AlexBBBril** [php-enqueue/enqueue-dev#376]
I using enqueue/enqueue-bundle in symfony 4

I'm trying to get a producer in the controller, for further work with him. By passing Producer class to the constructor, i get a type error, since in the test environment, the traceable_producer: true is set in the config, and in the standard traceable_producer: false.
If i pass ProducerInterface, i get a RuntimeException.

**Full exception text** "_Cannot autowire service "App\Controller\TestController": argument "$producer" of method "__construct()" references interface "Enqueue\Client\ProducerInterface" but no such service exists. It cannot be auto-registered because it is from a different root namespace. Did you create a class that implements this interface?_"

This behavior is fixed by adding to the services.yml the line 
`Enqueue \ Client \ ProducerInterface: '@ enqueue.producer`
 but it seems to me that this is not the best way to work out of the box.

Thanks!

**Comment by makasim** [comment]
There must be an alias with the producer interface as id to [this service](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/Resources/config/client.yml#L6)

**Comment by AlexBBBril** [comment]
@makasim, tnanks for your answer. But what if I need TraceableProducer in a test environment?

**Comment by makasim** [comment]
As for `TraceableProducer ` there must be a separate alias, which is present only in testing env.
