### ISSUE TITLE
Original populate do it again after queue jobs

### ISSUE THREAD

**Issue by Gu3** [php-enqueue/enqueue-dev#377]
Hi ! 
_first this is my conf :_ 

**composer :** 
` 
"symfony/symfony": "2.8.*",
 "friendsofsymfony/elastica-bundle": "^3.2",
 "enqueue/elastica-bundle": "^0.8.0",
"enqueue/fs": "^0.8.21",
`
**config.yml**
`enqueue:
    transport:
        default: 'fs'
        fs:
            path: /tmp/elastica
    client: ~`

**CLI command :** 
`app/console enqueue:transport:consume enqueue_elastica.populate_processor -vvv`  => terminal 1
`time app/console fos:elastica:populate --index search --type organization` => terminal 2

_Second, my problem :_ 
I ran my CLI command inside 2 distinct terminal.
In terminal 1 => the populate inside the consumer works like a charm (verbose OK)
In terminal 2 => during the populate in the consumer, the progress bar does'nt appears and  when my consumer are finaly done (all data are OK inside elastica), the progress bar show itself and the original populate start...  

Hope my explanations are clear enough and someone can help me ... 
Thanks !

**Comment by makasim** [comment]
Last time I played with it worked fine, the progress bar was progressively updated. I dont think it is related to enqueue directly, most like an issue with a terminal you are using or Symfony version (I tried it with Symfony 3\4).

The `enqueue/elastica-bundle` does not support  `friendsofsymfony/elastica-bundle ^3.2` version, only 4 or higher.

**Comment by Gu3** [comment]
Thank for the awser ! 
The progress bar is not really an issue to me : If I told about it, it's just to illustrate my problem...

stuck in this state during the consumer populate 
![image](https://user-images.githubusercontent.com/5227741/36489205-b36e5972-1725-11e8-91a4-f8b42cfd7bb9.png)

And after the populate are done 
![image](https://user-images.githubusercontent.com/5227741/36489226-c38e89c6-1725-11e8-9d0e-999139b55bb6.png)

I used the 0.8.0 of enqueu-elastica-bundle, the composer file says 
```
"require": {
        "php": ">=5.6",
        "friendsofsymfony/elastica-bundle": "^3|^4|^5",
        "enqueue/enqueue-bundle": "^0.6|^0.7|^0.8",
        "enqueue/enqueue": "^0.6|^0.7|^0.8"
},
```
mayby I need to used an older version... 
I let you know if I find something...

**Comment by Gu3** [comment]
Hey, It's me, again :) 
so I work with fos elastica bundle 4.x.
When I try to launch
`app/console fos:elastica:populate --index search2 --pager-persister=queue`
I've got an error : ` No pager persister was registered for the give name "queue"`

It's work with 
`app/console fos:elastica:populate --index search2 --pager-persister=in_place`

What is the difference between queue and in place ? 

By the way, the original issue is still here : the consumers make theirs jobs and when the populate is finish, It's start again but without consumers helps this time... 

thanks

**Comment by makasim** [comment]
> What is the difference between queue and in place ?

in_place does not send anything anywhere and all the job in that same process.

**Comment by makasim** [comment]
> I've got an error : No pager persister was registered for the give name "queue"

it means that the [queue pager populate service](https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Resources/config/services.yml#L29) has not been registered. Please, double check you registered the EnqueueElasticaBundle properly.

**Comment by Gu3** [comment]
the 0.8.1 can work with SF 2.8 ? Or I need to upgrade in 3.0 ?

**Comment by Gu3** [comment]
It's ok ! I forgot to put 

`parameters:
    fos_elastica.use_v5_api: true`
and 
`provider:
     pager_provider: true`

thanks for your help
