### ISSUE TITLE
[RFC] Throttle/debounce

### ISSUE THREAD

**Issue by Koc** [php-enqueue/enqueue-dev#378]
Not sure, if it good idea, but what about adding support of the throttling/debounce in the library?

Our use case: we should update ES index when user is online (products from online users has bigger priority in output). But we wan't recude updates count, for example do not create more than 1 update per 5 minutes.

**Comment by makasim** [comment]
Do you have an idea how to implement it?

**Comment by Koc** [comment]
No any for now.

Maybe create layer of producer extensions, create `ThrottlingExtension`, tag some messages with `ThrottlableMessageInterface` and ...

![](https://cs4.pikabu.ru/images/previews_comm/2015-08_6/144057129514268762.jpg)

Or we should do this on consumers side.

**Comment by makasim** [comment]
> Or we should do this on consumers side.

That's the preferred way IMO.
