### ISSUE TITLE
The connection timed out after 3 sec while awaiting incoming data

### ISSUE THREAD

**Issue by intergalactisch** [php-enqueue/enqueue-dev#379]
Hi, 
I am trying to use the amqp_lib transport version and have set up RabbitMQ and the bundle in my Symfony app. However, when I keep getting a connection timeout after 3 seconds because no data was send or no connection was made. For this I am using the following inside my config.yml:

```
enqueue:
transport:
default: amqp
amqp: "amqp://username:password@127.0.0.1:15672/%2F"
client: ~
```
Username being my RabbitMQ username, and password being my password.

What am I doing wrong?

**Comment by makasim** [comment]
* producer or consuming side?
* how do you exactly run conumse command?
* Did you set `--recieve-timeout`?

**Comment by intergalactisch** [comment]
Woops, thanks for your reply but for anyone bumping into this issue, I made a rookie mistake: use port :5672 instead of :15672 when connecting.

My bad!

**Comment by antishov** [comment]
> Woops, thanks for your reply but for anyone bumping into this issue, I made a rookie mistake: use port :5672 instead of :15672 when connecting.
> 
> My bad!

Thanks a lot, man
