### ISSUE TITLE
Problem registering SQS transport using DSN string

### ISSUE THREAD

**Issue by a2xchip** [php-enqueue/enqueue-dev#380]
The SQS config using DSN return 403 error during broker setup. Same credentials used in `config.yml` does not.

**Comment by makasim** [comment]
Could you please debug it [here](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/sqs/SqsConnectionFactory.php#L41).

**Comment by a2xchip** [comment]
@makasim sure! will check it

**Comment by makasim** [comment]
I tried it with transport and basic setup, it works. 

[The tests](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php) are there too. 

Feel free to repone if you find something
