### ISSUE TITLE
Close Connection

### ISSUE THREAD

**Issue by neandher** [php-enqueue/enqueue-dev#384]
Hello, how i can close connection after the work done?
I run: bin/console enqueue:consume --setup-broker
And: php bin/console fos:elastica:populate --pager-persister=queue
Everthing works fine, but after populate is done, the connection still open and console waiting...

"enqueue/amqp-ext": "^0.8.21"

**Comment by neandher** [comment]
**Or you can send a signal from populate command to the consume to stop it.**

How?

**Comment by makasim** [comment]
Basically, you have a pull of consumers that are working all the time, waiting for messages. So there is no need to stop them.

The other way is to start some consumers before population (by subscribing to pre populate event) using Symfony Process component. and stop them after the job is done. I strictly suggest using the first approach. This one is tricker and therefore more room for bugs.
