### ISSUE TITLE
[JobRunner] Uncaught exceptions leave jobs in "running" state

### ISSUE THREAD

**Issue by msheakoski** [php-enqueue/enqueue-dev#385]
The [docs](https://github.com/php-enqueue/enqueue-dev/blob/e2a950c98c1d13a12b88b526345b69bf56dd4edd/docs/consumption/message_processor.md#on-exceptions) say to not catch exceptions and fail fast when processing messages, however, if an exception occurs within a running job, things do not properly clean up and jobs are left in a "enqueue.job_queue.status.running" state. You are also no longer able to execute a job with the same name again because it is stuck in the "enqueue_job_unique" table (DBAL transport).

I think in https://github.com/php-enqueue/enqueue-dev/blob/e2a950c98c1d13a12b88b526345b69bf56dd4edd/pkg/job-queue/JobRunner.php#L49 this line should be wrapped in a try/catch block, failed, and then re-throw the exception so it bubbles up to the message processor. Something similar to:

```php
try {
    $result = call_user_func($runCallback, $jobRunner, $childJob);
} catch (Exception $e) { // for PHP 5
    $this->jobProcessor->failChildJob($childJob);
    throw $e;
} catch (Throwable $e) { // for PHP 7+
    $this->jobProcessor->failChildJob($childJob);
    throw $e;
}
```

I am not entirely familiar with the codebase so I may be missing something, but hopefully you get the right idea from my example.

**Comment by makasim** [comment]
It makes sense to me. @ASKozienko what do you think about this?
