### ISSUE TITLE
[FsBroker] This message breaks the queue

### ISSUE THREAD

**Issue by cbonnissent** [php-enqueue/enqueue-dev#387]
```
$message = $psrContext->createMessage('                             |{"body":"aMessageData","properties":{"enqueue.topic_name":"user_updated"},"headers":{"content_type":"text\/plain","message_id":"90979b6c-d9ff-4b39-9938-878b83a95360","timestamp":1519899428,"reply_to":null,"co
rrelation_id":""}}');
```

When I consume the message I have this error 

`PHP Fatal error:  Uncaught LogicException: The frame could start from either " " or "|". The malformed frame starts with """. in XXXX/enqueue/vendor/enqueue/fs/FsConsumer.php:125
Stack trace:
#0 [internal function]: Enqueue\Fs\FsConsumer->Enqueue\Fs\{closure}(Object(Enqueue\Fs\FsDestination), Resource id #29)
#1 XXXX/enqueue/vendor/enqueue/fs/FsContext.php(121): call_user_func(Object(Closure), Object(Enqueue\Fs\FsDestination), Resource id #29)
#2 XXXX/enqueue/vendor/enqueue/fs/FsConsumer.php(155): Enqueue\Fs\FsContext->workWithFile(Object(Enqueue\Fs\FsDestination), 'c+', Object(Closure))
#3 XXXX/enqueue/vendor/enqueue/fs/FsConsumer.php(91): Enqueue\Fs\FsConsumer->receiveNoWait()
#4 XXXX/enqueue/consumer.php(16): Enqueue\Fs\FsConsumer->receive()
#5 {main}
  thrown in XXXX/enqueue/vendor/enqueue/fs/FsConsumer.php on line 125`

**Comment by makasim** [comment]
Any reason why you send such a message? why does it start with '('                             |{'. Looks like an internal format of fs transport.

**Comment by cbonnissent** [comment]
Hello, I test the FsBroker and I want to see if the message are isolated in the file or if I need to avoid some messages beginning.
I agree that in production there is a very low probability to see messages like this one.

**Comment by makasim** [comment]
I don't suggest you use fs transport in production, it is blocking, provides very basic features.

**Comment by makasim** [comment]
I think fs transport should throw an exception if it finds a special char sequence. wdyt?

**Comment by cbonnissent** [comment]
You should write this advice on the doc of the transport (that is build only for dev purpose, not for production), no ? 
The usage of the Doctrine transport can be envisaged in production ? (I don't want to install another components like rabbitMQ)
Yes, you should throw an exception, or you could escape the special char sequence

**Comment by makasim** [comment]
I am going to add an exception, as for escaping it is not that easy to do. 

DBAL is meant to be used in prod.

**Comment by cbonnissent** [comment]
Thank you for your advice !

**Comment by makasim** [comment]
escaping has been implemented.

**Comment by cbonnissent** [comment]
Thank you !
