### ISSUE TITLE
[DbalDriver] does not convert Message::$expire to DbalMessage::$timeToLive

### ISSUE THREAD

**Issue by msheakoski** [php-enqueue/enqueue-dev#391]
The following methods are missing code to handle expire/timeToLive conversion between Message and DbalMessage objects:
https://github.com/php-enqueue/enqueue-dev/blob/bc611861bf0ae458e5278b4925c32227986511ea/pkg/dbal/Client/DbalDriver.php#L61
https://github.com/php-enqueue/enqueue-dev/blob/bc611861bf0ae458e5278b4925c32227986511ea/pkg/dbal/Client/DbalDriver.php#L89
which results in the "enqueue" table having a null value for "time_to_live" even though it was set on the Message object prior to sending the event/command.

**Comment by makasim** [comment]
The discussion continues in PR: https://github.com/php-enqueue/enqueue-dev/pull/396
