### ISSUE TITLE
[Symfony] AsyncListener does not use TraceableProducer

### ISSUE THREAD

**Issue by wizbit** [php-enqueue/enqueue-dev#392]
When writing a test it would be useful to know that the AsyncListener is sending messages to the queue.
The documentation on testing states I should use the NullTransport and TraceableProducer to check the message was sent.
However, the AsyncListener create a new producer instead of using the producer defined in the container.

**Comment by makasim** [comment]
The AsyncListener works on transport level. The TraceableProducer is the feature of Enqueue Client which is higher level. 

The solution could be: Develop a listener that accepts Enqueue Client Producer and you can configure which one you'd like to use.

**Comment by makasim** [comment]
@wizbit why do you close this? There is something we can do: Add a Client Listener that works with traceable producer.

**Comment by wizbit** [comment]
Sorry, I thought you answered my query.

In Symfony, I created a test context that decorated the default context, and have that return a traceable producer so I could check the async messages would be sent.
