### ISSUE TITLE
Use the auto-tagging feature for e.g. processors

### ISSUE THREAD

**Issue by daften** [php-enqueue/enqueue-dev#405]
Similar to how twig does it: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L154

This line in the load function of EnqueueExtension.php should do it, but this is just one example:
```
$container->registerForAutoconfiguration(\PsrProcessor::class)->addTag('enqueue.client.processor');
```

It'd seem like a convenience for symfony4, with autowiring and autoconfigure.

**Comment by makasim** [comment]
@daften That's indeed would be great to fix. Could you work on a PR?

**Comment by mnavarrocarter** [comment]
What is the status of this? I use Symony's autowiring/autoconfigure feature a lot, and for the processors this cloud be a great improvement. I can definetely work on a PR for this.

**Comment by makasim** [comment]
A PR is very welcome

**Comment by mnavarrocarter** [comment]
Cool, I'll work in one. Where is the bundle repo though? Because the one on Github says "Read Only".

**Comment by mnavarrocarter** [comment]
Done! https://github.com/php-enqueue/enqueue-bundle/pull/3
