### ISSUE TITLE
Add documentation the processor services need to be public

### ISSUE THREAD

**Issue by daften** [php-enqueue/enqueue-dev#406]
By default, the symfony4 services with autoconfigure aren't public. I've noticed however that processors need to be declared publicly to work.

If the service isn't public, this is the error message I receive:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The "App\Service\Queue\Processor\RunCommandProcessor" service or alias has been removed or inlined when the container was compiled. You should either make it public, or s
  top using the container directly and use dependency injection instead.
```

**Comment by makasim** [comment]
@daften That's indeed would be great to fix. Could you work on a PR?
