### ISSUE TITLE
Laravel Usage

### ISSUE THREAD

**Issue by seivad** [php-enqueue/enqueue-dev#408]
Hey @makasim 

The docs for Laravel aren't very detailed unfortunately I don't know where you put the consumer code? I can't see where/how it finds the list of processor classes or where to put those classes for them to be run in the background listening for event topics. 

Can you please give a run down on how this works with Laravel? I can push messages into the RabbitMQ queue, they get auto acknowledged by the looks of it and then no idea how to consume it from different laravel apps or even the same one. 

It wasn't very clear on how to get this working out of the box. Very familiar with Laravel Events / Listeners but not this stuff.

**Comment by makasim** [comment]
There is a driver for Laravel's native Queue system. You can read here how to use it https://laravel.com/docs/5.6/queues.

It also exposes Enqueue's Simple Client which you can use too. Here's the doc https://github.com/php-enqueue/enqueue-dev/blob/master/docs/laravel/quick_tour.md#enqueue-simple-client
