### ISSUE TITLE
[Bundle] Enqueue\Symfony\Client\ContainerAwareProcessorRegistry expects processors to be public

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#410]
With Symfony 4, all services are private by default. But `Enqueue\Symfony\Client\ContainerAwareProcessorRegistry` keeps them as a set of names which it tries to `get()` from the container.

A better approach might be to inject tagged services or alternatively use a [service locator](https://symfony.com/doc/current/service_container/service_locators.html).

**Comment by makasim** [comment]
A PR that fixes it would be great

**Comment by dkarlovi** [comment]
We should probably fix this first, then #409 since that one will make services private by default.
