### ISSUE TITLE
object not found error

### ISSUE THREAD

**Issue by kricha** [php-enqueue/enqueue-dev#420]
Hello, i'm getting a lot of errors with not found object (after creating object)

error:
```
[info] Message received from the queue: fos_elastica_doctrine_orm_sync_index_with_object_change
[debug] Headers: array (
)
[debug] Properties: array (
)
[debug] Payload: '{"action":"insert","model_class":"AppBundle\\\\Entity\\\\Order","model_id":"id","id":1744210,"index_name":"app","type_name":"order"}'
[debug] [ExclusiveCommandExtension] This is a exclusive command queue and client's properties are not set. Setting them
[info] Message processed: enqueue.ack
[info] The object "AppBundle\Entity\Order" with id "1744210" could not be found.
```

also, when i'm trying update entity, i'm getting not latest object, but previous. Seems like it caches somewhere

maybe we need to have delay? Or i've missed something in configuration?

**Comment by aLkRicha** [comment]
ping @makasim

**Comment by makasim** [comment]
I am aware of the issue, haven't had a chance to look into it.

**Comment by makasim** [comment]
Could you please debug this IF statement https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Doctrine/Queue/SyncIndexWithObjectChangeProcessor.php#L95

**Comment by aLkRicha** [comment]
@makasim what exactly to debug? If doctrine could find object?

**Comment by aLkRicha** [comment]
@makasim hello again. It comes into this cycle: 
```
if (false == $object = $repository->find($id)) {
                    dump($object);
                    $persister->deleteById($id);

                    return Result::ack(sprintf('The object "%s" with id "%s" could not be found.', $modelClass, $id));
                }
```
with null value.

**Comment by aLkRicha** [comment]
@makasim queue transport is redis

also there is a problem with update entities. After first update all indexed fields are right, but if i'll change something in entity and save it, it will index old version of entity

**Comment by makasim** [comment]
@aLkRicha try to enable [doctrine clear identity map extension](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue-bundle/DependencyInjection/Configuration.php#L77)

**Comment by aLkRicha** [comment]
@makasim better, but i still can catch old version in index (in db is new). And its all in dev env, i think in prod, with huge load there will be more variances

**Comment by kricha** [comment]
@makasim also i make some research:
if i'll place on line https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Doctrine/Queue/SyncIndexWithObjectChangeProcessor.php#L104
code like: 
```php
                dump($object->getStatus(), $object->getTotal());
                $this->doctrine->getManager()->refresh($object);
                dump($object->getStatus(), $object->getTotal());
```
i'll get:
```bash
[info] Message received from the queue: fos_elastica_doctrine_orm_sync_index_with_object_change
[debug] Headers: array (
)
[debug] Properties: array (
)
[debug] Payload: '{"action":"update","model_class":"AppBundle\\\\Entity\\\\Order","model_id":"id","id":1423071,"index_name":"app","type_name":"order"}'
[debug] [ExclusiveCommandExtension] This is a exclusive command queue and client's properties are not set. Setting them
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "default"
[debug] [DoctrineClearIdentityMapExtension] Clear identity map for manager "custom"
3
"54.45"
10
"54.45"
[info] Message processed: enqueue.ack```

`status` and `total` - just entity fields. as you can see, before refresh status = 3, total = "54.45" (old data), but after refresh status = 10, total = "54.45" (new data, changed status).  🧐

**Comment by kricha** [comment]
@makasim ping

**Comment by kricha** [comment]
@makasim one more thing..
if i insert on line https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Doctrine/Queue/SyncIndexWithObjectChangeProcessor.php#L97 code:
```php
/* test code */
$connection = $this->doctrine->getConnection();
$stmt = $connection->prepare("select * from order where id = :id;");
$stmt->bindValue('id', $id, 'integer');
$stmt->execute();
dump($object, $stmt->fetch());
/* test code */
```
it will find result (dump):
```
null
array:17 [
  "id" => "1425718"
  "status" => "14"
  "comment" => null
  "created_at" => "2018-06-02 12:30:05"
  "updated_at" => "2018-06-02 12:30:05"...
```

**Comment by kricha** [comment]
@makasim i've created pr for fix this issue
https://github.com/php-enqueue/enqueue-elastica-bundle/pull/13

**Comment by makasim** [comment]
@kricha do you do flush inside transaction?

**Comment by kricha** [comment]
@makasim i have a listener, for related to order entity:
```
class OrderMetaListener
{
    public function postUpdate(OrderMeta $orderMeta, LifecycleEventArgs $eventArgs): void
    {
        $order = $orderMeta->getOrder();
        $order->refreshEsIndex();
        $eventArgs->getEntityManager()->persist($order);
        $eventArgs->getEntityManager()->flush();
    }
}
```

**Comment by makasim** [comment]
The event is dispatched from within a transaction or not?

**Comment by kricha** [comment]
@makasim it's simple doctrine entity listener

**Comment by makasim** [comment]
yes, I see. show me please the code from where the event is dispatched

**Comment by kricha** [comment]
@makasim maybe i don't understand the question, i didn't change events. It's all provided by your bundle.
Insert is here:
```
                $orderDTO->setDelivery(min($deliveries));
                $orderDTO->setTotal($orderDTO->getTotal() + $orderDTO->getDelivery());

                $order->fillFromApiOrderDTO(
                    $orderDTO,
                    $source,
                    $this->getDoctrine()->getRepository('AppBundle:Customer')
                );

                $this->getDoctrine()->getManager()->persist($order);
                $this->getDoctrine()->getManager()->flush();
```

**Comment by makasim** [comment]
does the code wrapped  by beingTransaction\commit\rollback code. ?

**Comment by kricha** [comment]
@makasim no

**Comment by makasim** [comment]
okay, then it is something different.

**Comment by makasim** [comment]
wont fix
