### ISSUE TITLE
[Symfony][Documentation] Migrate from JMSJobQueueBundle

### ISSUE THREAD

**Issue by stephanvierkant** [php-enqueue/enqueue-dev#421]
I think this bundle/library is the perfect replacement for the [JMSJobQueueBundle](https://github.com/schmittjoh/JMSJobQueueBundle), especially with the [Message Component](https://symfony.com/blog/new-in-symfony-4-1-messenger-component) in Symfony 4.1.

A migration guide would be great. I'm trying to migrate. Feel free to share your thoughts about the difference between JMSJobQueueBundle and EnqueueBundle, maybe I'll write an article one day.

I found http://tech.yappa.be/enqueue-symfony-console-commands, but that doesn't explain async commands, so it makes no sense IMHO.

**Comment by makasim** [comment]
We don't work with the JMSJobQueueBundle so no chance for us to add the doc. A pull request is very welcome though.

**Comment by VincentClair** [comment]
Hi @stephanvierkant,
Do you have news on a migration guide ? Do you succeed in migration ?
