### ISSUE TITLE
RouterProcessor "acknowledges" commands and events without a registered processor

### ISSUE THREAD

**Issue by barros001** [php-enqueue/enqueue-dev#423]
If you send a command (or event) to the queue without a registered processor to process it, RouterProcessor will simply ACK the message and it will be removed from the queue. This could potentially cause bugs to go unnoticed. I believe it would be better if the router would simply do nothing, neither ACK nor REJECT so the message gets back to the queue to be re-delivered. This would give developers a clue that something's not right and potentially important messages wouldn't get lost.

I just run into this issue myself where during deployment (AWS Container Service) I had two consumers running (old and new code) for a minute or so and during that time I had a new command sent to the queue and picked up by the old consumer, which simply discarded the message. It took me a few minutes to realize what was happening.

**Comment by makasim** [comment]
That's expected behavior. What will happen if you send a message to non-existent RabbitMQ exchange? 

> I just run into this issue myself where during deployment (AWS Container Service) I had two consumers running (old and new code) for a minute or so and during that time I had a new command sent to the queue and picked up by the old consumer, which simply discarded the message. It took me a few minutes to realize what was happening.

That's also a completely valid case. You can either stop all consumers before deploy or develop the way the old and new code could work at the same time.
