### ISSUE TITLE
Why no packagist support

### ISSUE THREAD

**Issue by stevleibelt** [php-enqueue/enqueue-dev#424]
Hey, I am wondering why I can not install it via packagist.
Any reason for that?

**Comment by makasim** [comment]
It is just for development and not meant or adapted to be used in apps. As for that use subtree split repos (read-only). they are published on packagist.

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/docs/contribution.md

**Comment by stevleibelt** [comment]
Thanks for the quick response @makasim.

**Comment by aarangara** [comment]
@makasim Just curious on your above comment - If you are saying it's just for development, then why do I see " production ready" on the home page? Am I missing something - that it won't be usable for production environments?

**Comment by makasim** [comment]
The `enqueue-dev` is used for development purposes and its subtree splits for production. 

The code is production ready and used in many applications.
