### ISSUE TITLE
[sqs] Messages should not allow empty bodies

### ISSUE THREAD

**Issue by elazar** [php-enqueue/enqueue-dev#435]
From the [SQS documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html#message-attribute-components):

> The `Name`, `Type`, `Value`, and the message body must not be empty or null.

Passing an empty string as the message body to the AWS SDK results in an exception being thrown that resembles the following.

```
class: Aws\Sqs\Exception\SqsException

code: 0

file: vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:192

message: Error executing "SendMessage" on
"https://sqs.us-east-1.amazonaws.com/1234567890/queue-name";
AWS HTTP error: Client error:
`POST https://sqs.us-east-1.amazonaws.com/1234567890/queue-name`
resulted in a `400 Bad Request` response:

MissingParameter (client): The request must contain the parameter MessageBody. - 
<?xml version="1.0"?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
  <Error>
    <Type>Sender</Type>
    <Code>MissingParameter</Code>
    <Message>The request must contain the parameter MessageBody.</Message>
    <Detail/>
  </Error>
  <RequestId>0cdc8fab-dde9-5c5d-a7fd-dccfd24acec4</RequestId>
</ErrorResponse>
```

There are a few areas in which the Enqueue SQS transport implementation seems to overlook this requirement.

* `SqsProducer->send()` does not check if the body is empty, only that it is a scalar or strictly equal to `null`. [source](https://github.com/php-enqueue/sqs/blob/8e7bb49704e0e8d18134ba7aa55d25db3e1b0ba4/SqsProducer.php#L45-L46)
* `SqsMessage->__construct()` assigns a default value of the empty string to its `$body` parameter. [source](https://github.com/php-enqueue/sqs/blob/8e7bb49704e0e8d18134ba7aa55d25db3e1b0ba4/SqsMessage.php#L54)
* `SqsMessage->setBody()` implements no type or value checks against its `$body` parameter. [source](https://github.com/php-enqueue/sqs/blob/8e7bb49704e0e8d18134ba7aa55d25db3e1b0ba4/SqsMessage.php#L68)
* `SqsContext->createMessage()` assigns a default value of the empty string to its `$body` parameter. [source](https://github.com/php-enqueue/sqs/blob/8e7bb49704e0e8d18134ba7aa55d25db3e1b0ba4/SqsContext.php#L52)

**Comment by makasim** [comment]
I think we should catch the internal exception wrap it to enqueue's one in the producer. wdyt?

**Comment by makasim** [comment]
The queue interop allows empty string body, that's way SqsMessage->__construct(), SqsMessage->setBody(), and  SqsContext->createMessage() do what they do

**Comment by elazar** [comment]
> I think we should catch the internal exception wrap it to enqueue's one in the producer. wdyt?

My only reservation about this is that it requires a network call to SQS for something that we can easily figure out on the client side. It goes against the "fail fast, fail early" principle.

> The queue interop allows empty string body, that's way SqsMessage->__construct(), SqsMessage->setBody(), and SqsContext->createMessage() do what they do

Fair enough, but there's nothing preventing their behavior from being changed (e.g. throwing an exception) even if they have to maintain compatibility with the interface.

**Comment by elazar** [comment]
Works for me. :+1: I'm willing to submit a PR with this change myself, if it'd help.

**Comment by elazar** [comment]
@makasim I've filed #478, which addresses this issue by throwing an exception when `SqsProducer->send()` is called with a message containing an empty body.

The cited issue with `SqsContext->create()` is unfortunately unavoidable due to its required adherence to the method signature of `PsrContext->create()`, which assigns a default value of the empty string to its `$body` parameter.

There is one further change that could be made to help catch this issue earlier, though it would likely be considered a BC break. Specifically, it would involve modifying `SqsMessage->__construct()` to call `setBody()` and modifying `setBody()` to perform a check on the `$body` parameter it receives similar to the check that `SqsProducer->send()` performs in #478. This would also make the issue with `SqsContext->create()` moot, as it just proxies to `SqsMessage->__construct()`. I would suggest considering this change for a future major point release.
