### ISSUE TITLE
[sqs] Support for multi-region client

### ISSUE THREAD

**Issue by Lidbetter** [php-enqueue/enqueue-dev#439]
Hi,

I need to support queue interaction from multiple aws regions.

If I were to implement this and contribute back - is that something the project would be interested in?
If so, in broad strokes, do you have a preference for how to do this: changing existing sqs package to support multi region, or a new one specifically for multi region?

**Comment by makasim** [comment]
Hi,

Sorry, I am not sure I have enough knowledge. Could you please post a link to something regarding the topic or tell more about it?

**Comment by Lidbetter** [comment]
This references the S3 client, but the same conventions apply to the sqs calls
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multiregion-client.html

We came to need to use a the multi region client because fifo queues are only available in some regions - when we first needed a fifo queue, there were not available in the same region as the rest of our queues.
https://aws.amazon.com/sqs/faqs/#service-access-regions


Example usage:
```
$sdk = new Aws\Sdk([
    'Sqs' => [
        'region' => 'us-east-1',
        'version' => '2012-11-05',
        'credentials' => [
            'key' => env('SQS_KEY'),
            'secret' => env('SQS_SECRET'),
        ],
    ],
]);

/** @var \Aws\Sqs\SqsClient $sqsClient */
$sqsClient = $sdk->createSqs();
// $sqsClient can only make queries to queues in 'us-east-1' region

/** @var \Aws\MultiRegionClient $sqsMultiRegionClient */
$sqsMultiRegionClient = $sdk->createMultiRegionSqs();
// $sqsMultiRegionClient needs an '@region' key in each calls input args 

$sqsClient->createQueueAsync([
    'QueueName' => 'email-onboarding.fifo',
    'Attributes' => [
        'FifoQueue' => 'true',
    ],
]);

$sqsMultiRegionClient->createQueueAsync([
    '@region' => 'us-east-2',
    'QueueName' => 'email-onboarding.fifo',
    'Attributes' => [
        'FifoQueue' => 'true',
    ],
]);
```

For all the calls the enqueue would need to make, everything is the same + the addition of the region to each sqs api call

**Comment by makasim** [comment]
supported since 0.9.3
