### ISSUE TITLE
Gracefull shutdown?

### ISSUE THREAD

**Issue by zsolt-szilagyi** [php-enqueue/enqueue-dev#440]
I implemented enqueue in plain PHP using SimpleClient.
ctrl+c could kill the process after taking a message, so I'm looking for a way of a graceful shutdown.
My initial idea is

```
        while (!$bStopped) {
            
            $timeLimit = new DateTime('now');
            $timeLimit->modify('+3 second');
            $oExtension = new \Enqueue\Consumption\Extension\LimitConsumptionTimeExtension($timeLimit);
            
            $this->_client->consume($oExtension);

            if (php_sapi_name() === 'cli') {
                pcntl_signal_dispatch();
            }

        }
```

Unfortunately, after the first call of  consume() every consecutive consume() leads to LogicException:The queue was already bound. Queue: enqueue.app.default.
**How can I gracefully stop a consumption, in a restartable way?** 
Thanks!

**Comment by makasim** [comment]
You could add your own extension. The extension can call https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Context.php#L185 method to stop consumption. 

As for signals, you'd better try https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Extension/SignalExtension.php extension.
