### ISSUE TITLE
[sqs] Support using a pre-configured SqsClient

### ISSUE THREAD

**Issue by elazar** [php-enqueue/enqueue-dev#443]
Currently, `SqsConnectionFactory` [handles instantiating `SqsClient`](https://github.com/php-enqueue/sqs/blob/0.8.24/SqsConnectionFactory.php#L112) and [limits what settings are allowed](https://github.com/php-enqueue/sqs/blob/0.8.24/SqsConnectionFactory.php#L91-L110).

For example, it doesn't presently support the [`http_handler` setting](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#http-handler), which is useful for logging the Guzzle requests and responses comprising communication between Enqueue and SQS.

I suspect that the easiest way to support more complex configurations would be to support having `SqsConnectionFactory` accept a pre-configured `SqsClient` instance for its `$config` parameter.

It looks like it may be possible to add this support using a custom connection factory implementation, but it would be nice to see it natively supported in the core SQS driver.

**Comment by makasim** [comment]
That would be great. By the way, it is something we did for redis transport.
