### ISSUE TITLE
[consumption] process niceness extension

### ISSUE THREAD

**Issue by ramunasd** [php-enqueue/enqueue-dev#449]
With PHP it is doable with just one line:
```
proc_nice($priority);
```
Where priority is integer from -20 to 19, but only values from 0 onwards is allowed without root permissions. Default is 0.

http://php.net/manual/en/function.proc-nice.php

Would be very usefull for environments with limited CPU power and where (in terms of CPU time) some consumers must overcome other not so important processes.

**Comment by makasim** [comment]
Would you like to submit PR?

**Comment by ramunasd** [comment]
it's on my todo list :)
