### ISSUE TITLE
[question] PsrMessage interface

### ISSUE THREAD

**Issue by ubermuda** [php-enqueue/enqueue-dev#450]
Hi all,

Is there a reason why `Enqueue\Client\Message` does not implement the `Interop\Queue\PsrMessage` interface?

I might be missing here, but in the consumption ExtensionInterface, the Context is supposed to return a `Interop\Queue\PsrMessage` (I know it's not explicitely typed, but the name and the doc block suggests it strongly), while the client's ExtensionInterface uses `Message` which is incoherent.

Ideally, the client's ExtensionInterface would type hint arguments as `Interop\Queue\PsrMessage`

**Comment by makasim** [comment]
The client and consumption are two different layers. Client is higher one and consumption is lower. 

The client adds an opinionated way of sending events\commands. The goal is to make the process as simple and transparent as possible. Where consumption and queue interop is a general purpose solution. 

There is another limitation that is connected to PsrMessage. It has to be created by an abstract factory, we cannot simply instantiate a message object. No transport would accept it.

**Comment by makasim** [comment]
> Ideally, the client's ExtensionInterface would type hint arguments as Interop\Queue\PsrMessage

The client extension could indeed be improved.

**Comment by ubermuda** [comment]
@makasim would it make sense to make the `Enqueue\Client\Message` implement the `Interop\Queue\PsrMessage` interface?

**Comment by makasim** [comment]
> would it make sense to make the Enqueue\Client\Message implement the Interop\Queue\PsrMessage interface?

What problem would it solve? None of the transports would able to use it

**Comment by makasim** [comment]
I'd prefer to keep them separately to stress that these messages are completely different things, from different layers, libraries.

**Comment by ubermuda** [comment]
Here is my use case: I am writing an extension that signs message on the client side, and validates them on the consumption side. To do this I have a piece of code that I use in both extensions and that accepts a "message". Problem is I can't easily type hint my code because of the difference of message types in client et consumption extension.

I think I am missing something important, isn't the `Interop\Queue\PsrMessage` goal to represent a queue message, whenever in the lifecycle of this message we are?

**Comment by makasim** [comment]
I don't think your code should depend on either message.

**Comment by makasim** [comment]
We would need one more extension point on publish side, that gives access to psr message.
