### ISSUE TITLE
Bugs in RabbitMqDelayPluginDelayStrategy

### ISSUE THREAD

**Issue by scarbo87** [php-enqueue/enqueue-dev#455]
Hi, i tried to use RabbitMqDelayPluginDelayStrategy and found few bugs:

1. For RabbitMQ 3.7.5 version `RabbitMqDelayPluginDelayStrategy`:  options `x-delay` must be header, not the property

**Comment by 31vi5** [comment]
This is actually fixed in https://github.com/php-enqueue/enqueue-dev/pull/824
