### ISSUE TITLE
problematic uuid generation with postgres

### ISSUE THREAD

**Issue by kermorgant** [php-enqueue/enqueue-dev#457]
Hi,

I just started using a message queue, using dbal (with postgres), and stumbled very soon on an error saying function "uuid_generate_v4" was not available. 

I could solve this by installing an extension on the server (CREATE EXTENSION IF NOT EXISTS "uuid-ossp";) but that was possible because I had the permissions to do so. I tested on another cpanel managed postgres server and that was impossible there.

Thus, I wonder if you would see any drawback with [app generated uuid(https://github.com/ramsey/uuid), either replacing the current logic or adding it as an option ?

**Comment by makasim** [comment]
This is how it is in 0.9, uuid is generated in php code.
