### ISSUE TITLE
Simply

### ISSUE THREAD

**Issue by hpatoio** [php-enqueue/enqueue-dev#459]
I'm trying to use this library with SQS driver. Some things are not clear to me.

1) Why you change the queue name adding a prefix and the app name ? 
2) Why you always search for a queue named `default` ? 

Where can I find an example where I send a message to a queue where the name of the queue is *EXACTLY* the name I specify in the code ?

**Comment by makasim** [comment]
You are using the Enqueue CLient which is a high level abstraction library, it makes queue use as simple as possible, for that you should accept some of its decisions.

IF you need a very custom solution you should use transport directly. 

> Where can I find an example where I send a message to a queue where the name of the queue is EXACTLY the name I specify in the code ?

https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/sqs.md
