### ISSUE TITLE
populating, missing messages and supervisor

### ISSUE THREAD

**Issue by kricha** [php-enqueue/enqueue-dev#460]
I ran into the problem of losing messages in the queue.

The consumer is run by the supervisor, they have a memory limit of 200mb. Naturally, when this limit is reached, the current process is killed and a new one is launched. At the same time, if for some fraction of a second the attendant read the message from the queue, it is lost and not processed. When the elasticsearch index is filled up, large gaps are obtained (the same ones that were missed during interrupting, messages). Are there any options for such messages to be back in the queue?

i'm using rabbitmq and ampq-lib

**Comment by makasim** [comment]
RabbitMQ returns messages back to queue by default (if no_ack set). It should work.

**Comment by makasim** [comment]
Create an extension that send a message back to queue on reject 
https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Queue/PopulateProcessor.php#L80

**Comment by kricha** [comment]
@makasim where it(no_ack) could be set for populating?

**Comment by kricha** [comment]
@makasim also, it's blocked by
```
if ($message->isRedelivered()) {
            $replyMessage = $this->createReplyMessage($context, $message, 0,'The message was redelivered. Chances are that something has gone wrong.');

            return Result::reply($replyMessage, Result::REJECT);
        }
```

**Comment by makasim** [comment]
@kricha the solution with the extension should work for redelivery too

**Comment by kricha** [comment]
@makasim like this:
```
class RequeueInterruptedPopulatingExtension implements ExtensionInterface
{
    use EmptyExtensionTrait;

    /**
     * @param Context $context
     */
    public function onInterrupted(Context $context): void
    {
        $message = $context->getPsrMessage();
        if (null !== $message) {
            // Get message properties
            $props = $message->getProperties();
            // Get existing reDelivering counter or create new
            $reDel = $props['rd'] ?? 0;
            // Allow only two delivery attempts
            if ($reDel < 2) {
                $props['rd']   = $reDel + 1;
                $messageToSend = $context->getPsrContext()->createMessage($message->getBody());
                $messageToSend->setProperties($props);
                $requeueQueue = $context->getPsrContext()->createQueue($context->getPsrQueue()->getQueueName());
                $context->getPsrContext()->createProducer()->send($requeueQueue, $messageToSend);
            }
        }
    }
}
```
?
