### ISSUE TITLE
[consumption] reconnect on connection issues

### ISSUE THREAD

**Issue by ramunasd** [php-enqueue/enqueue-dev#461]
At the moment consumer just stops working after exception:
```
  [PhpAmqpLib\Exception\AMQPRuntimeException]
  Broken pipe or closed connection
```

Maybe it's worth to implement some connection retry logic instead of relying on supervisors?

**Comment by makasim** [comment]
It could be implemented as an extension, though I am addicted to fail fast ideology.

**Comment by ramunasd** [comment]
Actually extensions cannot catch and stop exception propagation to CLI executor.
\Enqueue\Consumption\QueueConsumer::onInterruptionByException throws exception regardless of it's type or extension behaviour.
So it must be either custom PsrContext or custom CLI command.

**Comment by makasim** [comment]
There is a fix for it https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/amqp_lib.md#long-running-task-and-heartbeat-and-timeouts
