### ISSUE TITLE
[rpc] multi message RPC calls & handler

### ISSUE THREAD

**Issue by ramunasd** [php-enqueue/enqueue-dev#462]
At the moment this nice library supports only single message(task) per RPC call. And everything looks ok.
But let's say You need perform more than one task simultaneously and wait for results, i.e. render 5 images per request and return all of them to user. In such case, You need to create 5 RPC calls(promises, 5 different rabbitmq temp queues), iterate over them again and again while not all replied and collect ready replies if any. That does not look as nice and efficient solution.

It really would be nice to have a tool which could handle such cases more nicelly and efficiently:
* instead of several temp queues it could create only one and bind to it
* methods like waitAll(), waitAny(), waitSome() would be very helpfull
* multi message rpc handler could act as promise itself

Currently Enqueue\Rpc\RpcFactory and Enqueue\Rpc\Promise are compatible only with single temp queue, single reply scenarios.

**Comment by makasim** [comment]
It is possible to use one reply queue, see [enqueue elastica bundle as example](https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Persister/QueuePagerPersister.php#L69)

**Comment by ramunasd** [comment]
Right, I know that, but the idea is about tool/helper/handler, but not the concept itself :)
