### ISSUE TITLE
Batch publishing

### ISSUE THREAD

**Issue by kolyadin** [php-enqueue/enqueue-dev#463]
Where i can found some info about batch publishing?

I need to produce thousands of messages in such way:
```
<?php

$producer = $this->context->createProducer();

foreach ($items as $item) {
    $message = $this->context->createMessage(json_encode([
        'id' => $item
    ]));

    $producer->send($this->itemQueue, $message);
}

```
But it seems to be a not good solution.

Is there such feature like here:
https://github.com/php-amqplib/php-amqplib#batch-publishing
?

**Comment by makasim** [comment]
@kolyadin this is something we could add if it is part of AMQP 0.9.1 spec

**Comment by kolyadin** [comment]
@makasim okay, thanks
