### ISSUE TITLE
[rdkafka] Configuration properties in PHP constants

### ISSUE THREAD

**Issue by MortalFlesh** [php-enqueue/enqueue-dev#464]
Hello,

I've parsed all properties from kafka configuration here https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md into PHP classes with constants and proper description.

So for example

Property                                 | C/P | Range           |       Default | Description              
-----------------------------------------|-----|-----------------|--------------:|--------------------------
client.id                                |  *  |                 |       rdkafka | Client identifier. <br>*Type: string*
message.max.bytes                        |  *  | 1000 .. 1000000000 |       1000000 | Maximum Kafka protocol request message size. <br>*Type: integer*

Will be
```php
class GlobalConfig
{
    /**
     * Client identifier.
     *
     * Type: string
     * Default: rdkafka
     */
    public const CLIENT_ID = 'client.id';

    /**
     * Maximum Kafka protocol request message size.
     *
     * Type: integer
     * Range: 1000 .. 1000000000
     * Default: 1000000
     */
    public const MESSAGE_MAX_BYTES = 'message.max.bytes';
}
```

### So I have classes
| PHP class | Description | Consumer/Producer | Note |
|---|---|---|---|
| `GlobalConfig.php` | Global configuration properties | Both |  |
| `GlobalConsumer.php` | Global configuration properties | Consumer | extends GlobalConfig |
| `GlobalProducer.php` | Global configuration properties | Producer | extends GlobalConfig |
| `Topic.php` | Topic configuration properties | Both | |
| `TopicConsumer.php` | Topic configuration properties | Consumer | extends Topic |
| `TopicProducer.php` | Topic configuration properties | Producer | extends Topic |

I'll be happy to send PR with all these constants, but I'm not sure where to put them.
Can you point me?

**Comment by makasim** [comment]
Open PR here https://github.com/arnaud-lb/php-rdkafka. enqueue/rdkafka is just a wrapper around that extension
