### ISSUE TITLE
[dbal] unable to requeue with delay

### ISSUE THREAD

**Issue by dogawaf** [php-enqueue/enqueue-dev#474]
Hello

I'm trying to requeue a message with delay, but I can't make it works.

The message processor return `self::REQUEUE`, and the clone of the message is correctly back in the queue.
But it seems that the message never gets flagged as "redelivered", so the DelayRedeliveredMessageExtension ignores it.

Is there a bug or am I missing something?

Regards

**Comment by makasim** [comment]
You could set redelivered to true on cloned messaged manually.  https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/dbal/DbalMessage.php#L159

**Comment by dogawaf** [comment]
Hello

Thanks for the hint.
It sounds a bit weird for me to alter the original message before the clone being done when rejecting it.
But it works.

For the record, here is the working code:

```php
public function process(PsrMessage $message, PsrContext $context)
{
    /* @var DbalMessage $message */

    // Set a delay to 5 seconds.
    $message->setDeliveryDelay(5000);
    
    // This message will be cloned and queued. Original message is deleted.
    return self::REQUEUE;
}
```
