### ISSUE TITLE
[sqs] Dead Letter Queue Adoption

### ISSUE THREAD

**Issue by w3evolutions** [php-enqueue/enqueue-dev#475]
When the `QueueConsumer` receives a `self::REJECT` and calls `$consumer->reject($message, false);` on the `SqsConsumer` the message is deleted. This doesn't allow for the SQS Queue to force it's Dead Letter Maximum Receives, as the message is deleted.

Shouldn't there be a way to reject a message but leave it in SQS so the next iteration of `QueueConsumer->consume()` will pull the same message and it's received count will rise and eventually hit the Maximum Receives?

Or am I doing something wrong?

**Comment by makasim** [comment]
> Shouldn't there be a way to reject a message but leave it in SQS so the next iteration of QueueConsumer->consume() will pull the same message and it's received count will rise and eventually hit the Maximum Receives?

I am not aware of such feature. Could you please post a link or code example (maybe with SQS SDK) on how to do that?

**Comment by w3evolutions** [comment]
in enqueue\sqs\SqsConsumer.php line 133+. No matter what the SqsConsumer receives it always calls $this->context->deleteMessage(). Because a message is always deleted SQS will never hit it's dead letter queue. One would need to call:

```php
public function getQueueAttributes()
{
	$this->context->getQueueAttributesAsync([
		'QueueUrl' => $this->queueUrl,
		'AttributeNames' => ['RedrivePolicy']
	])
	->then(function (Result $queueAttributesResult) {
		// Do work here to know if there is a redrive policy
	});
}
```
**enqueue\sqs\SqsConsumer.php**
```php
public function acknowledge(PsrMessage $message)
{
	InvalidMessageException::assertMessageInstanceOf($message, SqsMessage::class);

	$this->context->getClient()->deleteMessage([
		'QueueUrl' => $this->context->getQueueUrl($this->queue),
		'ReceiptHandle' => $message->getReceiptHandle(),
	]);
}

public function reject(PsrMessage $message, $requeue = false)
{
	InvalidMessageException::assertMessageInstanceOf($message, SqsMessage::class);

	$this->context->getClient()->deleteMessage([
		'QueueUrl' => $this->context->getQueueUrl($this->queue),
		'ReceiptHandle' => $message->getReceiptHandle(),
	]);

	if ($requeue) {
		$this->context->createProducer()->send($this->queue, $message);
	}
}
```

**Comment by makasim** [comment]
I think it will work for exceptions when nothing is changed back to SQS server, the counter is incremented and the message returned back to the queue and up to max. then moved to a dead letter queue. 

When you explicitly reject a message it should not be moved to dead letter queue IMO.

**Comment by bendavies** [comment]
We've experienced this issue too.
@makasim is there a specific exception you are referring to?

**Comment by makasim** [comment]
@bendavies any exception, the idea that the reject method is not called, the connection is closed, sqs keeps a message till visibility timeout and returns message back to queue (incrementing the counter). 

I've not tested it, but it should be that way
