### ISSUE TITLE
Monitoring interface

### ISSUE THREAD

**Issue by RVN-BR** [php-enqueue/enqueue-dev#476]
Hi,

We use php-resque and are looking to migrate possibly to enqueue.  I'm wondering if there is any mointoring tools available to see/follow failed jos, running workers etc, similar to what is available for resque?

Also are there any plugins for scheduled jobs, and recurring jobs?

thanks!! (sorry for posting as an issue I didnt see a forum or discussion group).

**Comment by makasim** [comment]
Take a look at 

* https://github.com/php-enqueue/job-queue - simple (no UI for now)
* https://github.com/php-comrade/comrade-dev. - job manager as a service.

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/docs/monitoring.md
