### ISSUE TITLE
Memory question about private or shared.

### ISSUE THREAD

**Issue by lpj145** [php-enqueue/enqueue-dev#482]
Hi guys, thanks a lot for project, i'm using on symfony with bundle, and when i'm coding... thinking about memory, memory is shared or private on processor ? i ask this because my code going to complete and deploy in hours..

sorry for my english.

Att. Marcos

**Comment by makasim** [comment]
The memory is shared within one process, so if you consume several messages they can potentially interfere with each other. you have to develop your app to be stateless as much as possible. And limit the time a consumer works.

**Comment by lpj145** [comment]
have option to execute multiple works ? or, always command sent he need wait end of ack to run another message ?

**Comment by makasim** [comment]
a command can consume from several queues, though messages a processed one by one. 

you can run as many consumers as you want. that's how you get scalability.
