### ISSUE TITLE
Adding a signal handler to the consumer

### ISSUE THREAD

**Issue by MaxandreOgeret** [php-enqueue/enqueue-dev#485]
It's just a question, why don't you install a signal handler in the consumer?
I think it would be great to catch ctrl+c SIGINT signal and maybe not interrupting an ongoing process. 

What do you think ?

**Comment by makasim** [comment]
There is an extension for that https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Extension/SignalExtension.php

**Comment by MaxandreOgeret** [comment]
Nice i'll check this out.
Thanks ! :)
