### ISSUE TITLE
Compatibility with other langages

### ISSUE THREAD

**Issue by Gnucki** [php-enqueue/enqueue-dev#490]
Imagine I have a PHP producer using enqueue and a Node.js consumer.

1. Will I have a wrapper around my message in Node.js?
2. If yes, is there a way to throw that wrapper away?
3. If no, how can I extract my payload in Node.js?

Thanks for your help.

**Comment by makasim** [comment]
You don't need any wrappers as long as you use queue interop directly.
If you use Enqueue Client you might need some message headers to be available.

**Comment by Gnucki** [comment]
Thanks @makasim  for your quick answer.

I use the new symfony messenger component with that kind of code:
```php
$this->bus->dispatch(
    (new Envelope($message))->with(new TransportConfiguration([
        'topic' => $topic
    ]))
);
```
In that case, it seems to me there is a wrapper used especially for message serialization.
Is it possible to continue using that abstraction in any way if I want to get rid of this wrapper?

**Comment by makasim** [comment]
@Gnucki sorry, what wrapper are you talking about?

**Comment by Gnucki** [comment]
Ok, I have just looked at an example of message in RabbitMQ management tool.
The type of the message class (e.g. `App\Bundle\MyMessage`) is in RabbitMQ message properties whereas the payload is in RabbitMQ message payload.
I thought that this kind of metadata was sent in a wrapped payload like this one in JSON (or worse: a PHP serialization which would have been hard to handle using another language for the consumer):
```json
{
  "type": "App\Bundle\MyMessage",
  "realPayload": {
    "foo": 'bar"
  }
}
```
But this is not the case. I could not check it before but I should have waited before asking.
Thanks for your replies anyway.

**Comment by makasim** [comment]
No problem. Closing
