### ISSUE TITLE
[Question] Multiple queues/clients per environment in the Symfony Bundle

### ISSUE THREAD

**Issue by Gabb1995** [php-enqueue/enqueue-dev#491]
Following this [article](https://blog.forma-pro.com/the-how-and-why-of-the-migration-from-rabbitmqbundle-to-enqueuebundle-6c4054135e2b), I decided to migrate from the RabbitMQBundle to this bundle, but I have a couple of questions after reading the documentation and trying to implement.

With rabbitmq bundle I could have multiple queues which are then linked to multiple consumers. I could also define these queues per environment (in config_dev.yml and config_prod.yml), therefore I would have a 3 dev queues and 3 prod queues separately.

Is it possible to do the same inside the config files using this bundle?

My setup is that I'm injecting the ProducerInterface and using sendCommand('queue_name', message) where the queue_name already exists on SQS. Then I have a Processor which is subscribed to that queue name.

From what I saw you can add a prefix to the client in config.yml but this only applies to the RouterProcesser, which is never used in the article I linked, can you link me some documentation about the RouterProcessor and how it's used maybe?

Thanks.

**Comment by makasim** [comment]
The article you linked takes the most BC approach, which requires minimal changes to migrate. 
Once you've done with it, you can change pretty much everything in the setup. 

For example, yo can remove `queueName` and `queueNameHardcoded` so Enqueue Client generate queue names and use prefixe as you want.
