### ISSUE TITLE
[Symfony][Flex][enqueue/fs] Invalid ENQUEUE_DSN value after recipe execution

### ISSUE THREAD

**Issue by watari** [php-enqueue/enqueue-dev#520]
After execution of recipe `ENQUEUE_DSN` variable in `.env` file  have invalid value - `file://var/enqueue` (missing third slash). This is causing exception from FsConnectionFactory - ` Failed to parse DSN path "var/enqueue". The path must start with "/" `.
This is not a big problem since recipe is executed once, but anyway it by some reason broken (at least in my case). Can someone explain this behavior of recipe?
In recipe manifest just one line - `"ENQUEUE_DSN": "file://%VAR_DIR%/enqueue"`

**Comment by makasim** [comment]
this line has to be fixed 

https://github.com/symfony/recipes-contrib/blob/master/enqueue/fs/0.4/manifest.json#L3
