### ISSUE TITLE
[Redis] default timeout setting makes connection impossible

### ISSUE THREAD

**Issue by jeff1985** [php-enqueue/enqueue-dev#525]
With [this commit ](https://github.com/php-enqueue/redis/blob/64d907a97b9e5a64db800384ed594696c516ef6f/RedisConnectionFactory.php#L166) you've added a default value of `.0`for the timeout. For [predis](https://github.com/nrk/predis/wiki/Connection-Parameters) this actually means "zero seconds" which prevents any connections to be established in my case.  I always get "Connection timed out" unless I actually set a non-zero timeout in my DSN string.

The default setting in predis is `5.0`, so I guess you should set this default setting or leave it at `null`.

Also see diff here: https://github.com/php-enqueue/redis/commit/64d907a97b9e5a64db800384ed594696c516ef6f#diff-f12a3e81838b8c1f6057268e5b96bb3fR166

**Comment by makasim** [comment]
@jeff1985 I'll fix it asap.
