### ISSUE TITLE
[Redis] Implementing RPC?

### ISSUE THREAD

**Issue by jeff1985** [php-enqueue/enqueue-dev#532]
Hi @makasim,

I tried to implement RPC over enqueue-redis, but this seems right now not possible because RedisContext does not implement createTemporaryQueue() in RedisContext.php 

However I've found other libraries implementing RPC over Redis by opening a new queue with a random string as topic name. Are there any known problems about this approach? What would be needed to implement a temporary queue creation in [RedisContext.php](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/redis/RedisContext.php#L96) and are you open to accepting a PR?

**Comment by jeff1985** [comment]
Thanks for clarifications @makasim 

I have implemented first attempt in my symfony application. One thing that was unexpected, is that the commands sent into the queue are simply ignored with no notice, if there is no corresponding processor:
https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/RouterProcessor.php#L111-L117

After some debugging I was able to find out, that I need to provide the classname of the processor as command. I ended with the following syntax for sending RPC:

    $request = new \Enqueue\Client\Message($request);
    $request->setReplyTo("rpc-reply:".date("Y-m-d-H-i").":".bin2hex(random_bytes(16)));

    $promise = $this->producer->sendCommand("App\Processor\ServiceQueueProcessor", $request, true);
    if ($replyMessage = $promise->receive(7500)) {
            dump($replyMessage);
    }
    else dump("timeout exceeded!");

Could you please comment on any possible drawbacks of using that solution? Do I need to somehow take care of clearing the outdated reply queue's?

**Comment by makasim** [comment]
you could set `$promise->setDeleteReplyQueue(true)` and once a message is received the queue deleted.

**Comment by jeff1985** [comment]
Yes thanks for that hint @makasim . however this will only be effective if the consumer will not get a timeout while waiting for response. this means I still might be accumulating outdated response queues if the processor is not fast enough to respond in time, right? Is there any fix for that?

**Comment by makasim** [comment]
Wrap the code to try-finally block, and remove the queue manually. Or use a broker that supports a feature natively.

**Comment by jeff1985** [comment]
Thank you for your help!
