### ISSUE TITLE
[Elastica]Slow processing

### ISSUE THREAD

**Issue by intergalactisch** [php-enqueue/enqueue-dev#537]
Hi, 
I want to populate around 20 million records to ES as fast as possible. 
When I use the default "bin/console fos:elastica:populate" I can process about 200.000 records in 4 mins, but when I setup 10 consumers in Supervisor with the extended "bin/console enqueue:transport:consume enqueue_elastica.populate_processor", and initiate with "bin/console fos:elastica:populate --pager-persister=queue" the processing gets really slow: around 200 records in 5 minutes. It looks like something is off, but I can't seem to find the culprit. 

For context, I'm using Symfony 4 with the RabbitMQ broker and have the regular "bin/console enqueue:consume --setup-broker" running for another messaging queue.  
Also, adding -vvv to the populate_processors creates the following output:
`[info] Message received from the queue: fos_elastica_populate
[debug] Headers: array (
'reply_to' => 'amq.gen-INohHsxKRCzdIO7o-2q5_g',
)
[debug] Properties: array (
)
[debug] Payload: '{"options":{"max_per_page":100,"delete":true,"reset":true,"ignore_errors":false,"sleep":0,"indexName":"products","typeName":"product"},"page":10}'
[debug] [ExclusiveCommandExtension] This is a exclusive command queue and client's properties are not set. Setting them
[info] Message processed: enqueue.ack
[debug] [ReplyExtension] Send reply to "amq.gen-INohHsxKRCzdIO7o-2q5_g"`

Any ideas on where it might be going wrong?

Update: Even when setting just 1 consumer it still processes really slow

**Comment by makasim** [comment]
> Could it be that the pages count used in the PagerInterface is having a hard time due to the many records?

It should be slow in both cases

**Comment by makasim** [comment]
It would be great if you could profile it. I've not run into such issue. Dont have an idea why it happens.

**Comment by intergalactisch** [comment]
I've tested it a bit more, and it looks like it's happening because of the high amount of records. When I decrease the amount to 3 million it all seems to work.
