### ISSUE TITLE
[bundle] enqueue-bundle repository is not up-to-date

### ISSUE THREAD

**Issue by tseho** [php-enqueue/enqueue-dev#539]
When installing enqueue/enqueue-bundle with composer this morning, I found out the documentation for 0.8.37 does not match the code in 0.8.37. 

I can see that code in the directory [enqueue-dev/pkg/enqueue-bundle](https://github.com/php-enqueue/enqueue-dev/tree/master/pkg/enqueue-bundle) is not same as in the package [php-enqueue/enqueue-bundle](https://github.com/php-enqueue/enqueue-bundle).

Problem is, the outdated code in https://github.com/php-enqueue/enqueue-bundle is the one referenced by packagist.

**Comment by makasim** [comment]
Make sure you are on 0.8 branch while browsing code and docs in `php-enqueue/enqueue-dev`.

**Comment by tseho** [comment]
Thanks !

**Comment by makasim** [comment]
master is 0.9

**Comment by tseho** [comment]
Yeah, I totally missed that, seeing that all the releases were 8.x. I will be more careful :)
