### ISSUE TITLE
[consumption] FatalError after AmqpContext->close()

### ISSUE THREAD

**Issue by ramunasd** [php-enqueue/enqueue-dev#540]
PsrContext->close() isn't documented at all. Looks like it should close connection and reset bindings. This method is only for testing purposes?

```
Call to a member function wait_channel() on null
vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:225
```

**Comment by ramunasd** [comment]
In case of AMQP it should unset channel because it is unusable anymore. It would be recreated on call to getLibChannel().
But then comes next question. Once we close and recreate channel, it is subscribed to existing queues?

**Comment by makasim** [comment]
It should not subscribe to anything as long as you call basic_consume again.

**Comment by ramunasd** [comment]
Ok, clear. Looks like there should be ability to reopen connection and channel, but that's another story.

**Comment by vigneshpr87** [comment]
Hi,

i am facing the same above issue.. can you please provide the solution?
 Uncaught Error: Call to a member function wait_channel() on null in php-amqplib-2.7.2/PhpAmqpLib/Channel/AbstractChannel.php:225 

where exactly need to change

thanks
