### ISSUE TITLE
[Elastica]  Expected to be an alias but it is an index

### ISSUE THREAD

**Issue by intergalactisch** [php-enqueue/enqueue-dev#542]
Hi, 

I'm using the enqueue bundle to populate elastica in batches with the following commands:
- php bin/console enqueue:transport:consume enqueue_elastica.populate_processor --no-debug --env=prod (numprocs 4 in supervisor)
- php bin/console fos:elastica:populate --pager-persister=queue --no-debug --env=prod --ignore-errors -q --max-per-page=5000
After a while I keep bumping into the following error:
"Expected products_index to be an alias but it is an index."

Any idea on why this is happening? Could it be due to a timeout, since I'm working with a big collection of records?

**Comment by makasim** [comment]
A stack trace would be great. Add `-vvv` and catch trace then post it here.

**Comment by intergalactisch** [comment]
Okido, here is the stack trace; I keep bumping into it even after I've deleted all the indices.
Also, I've removed my sitepath + name with SITENAME.COM

`Exception trace:
 FOS\ElasticaBundle\Index\AliasProcessor->getAliasedIndex() at /SITENAME.COM/public_html/vendor/friendsofsymfony/elastica-bundle/src/Index/AliasProcessor.php:70
 FOS\ElasticaBundle\Index\AliasProcessor->switchIndexAlias() at /SITENAME.COM/public_html/vendor/friendsofsymfony/elastica-bundle/src/Index/Resetter.php:175
 FOS\ElasticaBundle\Index\Resetter->switchIndexAlias() at /SITENAME.COM/public_html/vendor/friendsofsymfony/elastica-bundle/src/EventListener/PopulateListener.php:47
 FOS\ElasticaBundle\EventListener\PopulateListener->onPostIndexPopulate() at /SITENAME.COM/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /SITENAME.COM/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php:44
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /SITENAME.COM/public_html/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:192
 FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() at /SITENAME.COM/public_html/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php:164
 FOS\ElasticaBundle\Command\PopulateCommand->execute() at /SITENAME.COM/public_html/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /SITENAME.COM/public_html/vendor/symfony/console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /SITENAME.COM/public_html/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /SITENAME.COM/public_html/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /SITENAME.COM/public_html/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /SITENAME.COM/public_html/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /SITENAME.COM/public_html/bin/console:39`

**Comment by makasim** [comment]
Not sure it has any relation to EnqueueElastica or Enqueue. Do you have that issue only when you use queue pager persister or always?

**Comment by intergalactisch** [comment]
Hmmm, my bad; it happens because of a mariaDB crash, and the moment supervisor + rabbitmq start up again to do their job again I get the error because of an unfinished and unclean process. Time for me to fix my server configs...
