### ISSUE TITLE
Stomp heartbeat

### ISSUE THREAD

**Issue by versh23** [php-enqueue/enqueue-dev#549]
Hi

Sometimes activeMQ close connection with my consumer. i would to check a connection status but how? 
Connection instance **private** https://github.com/php-enqueue/stomp/blob/master/StompContext.php#L189 and there are now heartbeat config 
https://github.com/php-enqueue/stomp/blob/master/StompConnectionFactory.php#L122

so, is it possible to send isAlive package or check connection ?

**Comment by makasim** [comment]
That could be made public.

**Comment by versh23** [comment]
@makasim so, what can i do ? 
stomp repo is [READ-ONLY], i cant make PR ?

**Comment by makasim** [comment]
You are supposed to do a PR on this repository, It will go to read only repo once is merged

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/stomp/StompContext.php
