### ISSUE TITLE
[Symfony] Processor autoconfigured twice

### ISSUE THREAD

**Issue by intergalactisch** [php-enqueue/enqueue-dev#550]
Hi, 
I have a processor setup that is listening to importCountTopic via getSubscribedTopics. With this I am using the default SF4 services.yaml setup and am using the autoconfiguration: 
```
services:
    _defaults:
        autowire: true 
        autoconfigure: true
        public: false
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
```         
It looks like the Processor is configured twice, because when I consume a queue the message is being processed twice. When I check "php bin/console debug:container ImportCountProcessor" I get the following result:

Select one of the following services to display its information:
  [0] App\Processors\ImportCountProcessor
  [1] .instanceof.Enqueue\Client\TopicSubscriberInterface.0.App\Processors\ImportCountProcessor
  [2] .abstract.instanceof.App\Processors\ImportCountProcessor

This is the output when I get more info on them:
```
**[0] App\Processors\ImportCountProcessor**
Service ID       App\Processors\ImportCountProcessor
  Class            App\Processors\ImportCountProcessor
  Tags             enqueue.client.processor
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes

**[1] .instanceof.Enqueue\Client\TopicSubscriberInterface.0.App\Processors\ImportCountProcessor**
Service ID       .instanceof.Enqueue\Client\TopicSubscriberInterface.0.App\Processors\ImportCountProcessor
  Class            App\Processors\ImportCountProcessor
  Tags             -
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         yes
  Autowired        yes
  Autoconfigured   no

**[2] .abstract.instanceof.App\Processors\ImportCountProcessor**
Service ID       .abstract.instanceof.App\Processors\ImportCountProcessor
  Class            App\Processors\ImportCountProcessor
  Tags             -
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         yes
  Autowired        yes
  Autoconfigured   yes
```
Any idea on why this is happening? 
Edit: formatting

**Comment by intergalactisch** [comment]
update: in my local environment I've had the same issue, but currently I can't reproduce the duplication of the messages. Also, I am getting the same result when I use "php bin/console debug:container ImportCountProcessor", so that isn't the thing that is going wrong. However, the bug is still here on production. I have no idea how to start debugging this, since I am using an almost clean services.yaml...

**Comment by makasim** [comment]
Do you have a service definition for ImportCountProcessor class? Or is it completly autoconfigured by Symfony?

**Comment by intergalactisch** [comment]
It is completely autoconfigured by Symfony

**Comment by makasim** [comment]
Cannot reproduce the issue with 0.9 version. Feel free to reopen if there is any addition info
