### ISSUE TITLE
Move some dependencies to dev section

### ISSUE THREAD

**Issue by Koc** [php-enqueue/enqueue-dev#57]
Some dependencies like `phpunit/phpunit` not required for each env. It is better move them to `require-dev` section.

**Comment by makasim** [comment]
This a development repository and is not intended to be used directly.

**Comment by Koc** [comment]
Ah, sorry.  Can you add in quick tour https://github.com/php-enqueue/enqueue-dev/blob/master/docs/quick_tour.md what dependency should I unclude in my project for working with this library?

**Comment by makasim** [comment]
@Koc sure.

**Comment by makasim** [comment]
basically it is already there:

Plain php: https://github.com/php-enqueue/enqueue-dev/blob/master/docs/amqp_transport.md#installation
Symfony: https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/quick_tour.md#install

**Comment by Koc** [comment]
thank you!
