### ISSUE TITLE
Handel failed jobs

### ISSUE THREAD

**Issue by aminvoly** [php-enqueue/enqueue-dev#579]
Hi, I'm not sure about my question, maybe it's ridiculous
I just wanted to know, when you are using a job, there is a record for each job in queue.enqueue_job ,is there any way to rerun the jobs with failed status?! or these records are just for extra information?
Thanks in advanced.

**Comment by makasim** [comment]
Are you talking about `enqueue/job-queue` extension?

**Comment by makasim** [comment]
The event should be dispatched here https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/job-queue/CalculateRootJobStatusProcessor.php#L66 and you can subscribe on it to handle failed case.
