### ISSUE TITLE
what is the default timeout for createProducer()->send?

### ISSUE THREAD

**Issue by Kifah** [php-enqueue/enqueue-dev#583]
Hi,
I want to  ` createProducer()->send ` , and throw an exception, if that call runs for longer than 200 ms. (for example, in case the SQS-Endpoint is not reachable)...can that be done in the settings? I could not find a parameter for that.

**Comment by makasim** [comment]
I dont know how to do it, I guess it should be possible by setting a socket timeout or something similar. 
If you find a solution feel free to submit a PR.
