### ISSUE TITLE
Make SQSContext configurable

### ISSUE THREAD

**Issue by ghostika** [php-enqueue/enqueue-dev#596]
I have access to an SQS queue on AWS, but I'm not the owner of it.
Given this setup, I can't access this queue with the use of enqueue/sqs library.

The problem, in SqsContext.php, at getQueryUrl I would need to pass an additional parameter for the `$this->getClient()->getQueueUrl()`, namely `QueueOwnerAWSAccountId`.

**Comment by makasim** [comment]
@ghostika could you work on a pull request that address the issue?
