### ISSUE TITLE
Multiple consumer handling one message

### ISSUE THREAD

**Issue by kayue** [php-enqueue/enqueue-dev#62]
Hi

I have a usage like this: after a blog post is published, I need to submit it to multiple places such as Apple News, ElasticSearch etc
In RabbitMQ I used to use one exchange and multiple queue / consumer to do this. 

I wondering is this still possible with the Enqueue library.

To goal is to publish the message once, and consume by unknown amount of consumer. 

Thanks
Kayue

**Comment by kayue** [comment]
Oh never mind it works out of the box. Thanks.

**Comment by makasim** [comment]
That's possible and there are a lot of options:

1. The amqp\stomp transport (the lowest abstraction) allows to publish to queue as well as to the exchange. Of course you have to create queue and exchange and bind them.

2. There is  client library which is working on top of transport. It simplifies a lot of things and provide extra features. One of those feature: You send a message to the "topic" (In terms of client) and it makes sure it is delivered to every processor subscribed to that topic. It works even on those transport which does not support pub\sub natively (fs, dbal, redis). 

3. The client also support a message bus. You can connect\discount applications to a shared bus easily.

**Comment by kayue** [comment]
@makasim Thanks for the explanation. 

I like how your library abstracted a lot of concepts. However, when I am trying to connect to another application, I found it not possible to connect EnqueueBundle to an existing exchange / queue. I am forced to use `enqueue.router` and the default queue. Is it not possible to do with the bundle?

**Comment by makasim** [comment]
@kayue  You can connect a processor to the needed queue. There are several options (:.

* [Client] If you use the client you can tell it to use the queue you want without any adjustments. Here's an example ((source)[https://github.com/php-enqueue/enqueue-sandbox/blob/master/symfony/src/AppBundle/Async/ResolveAllProcessor.php#L66]):

```php
<?php
   /**
     * {@inheritdoc}
     */
    public static function getSubscribedTopics()
    {
        return [
            Topics::RESOLVE_ALL => [
                'queueName' => Topics::RESOLVE_ALL,
                'queueNameHardcoded' => true
            ]
        ];
    }
```

If you do not use `TopicSubscriberInterface` you can set same options as tag attributes (Symfony container tag). 

* [Transport] Consume from any queue using a transport consume command: 

```
$ bin/console enqueue:transport:consume processorServiceId --queue=a_queue_to_consume_from
```

* [Transport] Implement QueueSubscriberInterface return a desired queue from it. Than run consume like this:

```
$ bin/console enqueue:transport:consume processorServiceId
```

P.S You cannot get rid of router exchange. It is there to support message bus pattern.

**Comment by makasim** [comment]
I am going to blog on "How to migrate from RabbitMQBundle to EnqueueBundle"in near future. 

I did it personally on one of the projects. So I can admit it is possible and is not that hard.

**Comment by kayue** [comment]
Amazing! Thanks @makasim!

**Comment by Koc** [comment]
@makasim can you add some example with multiple handlers for single message to docs? Also how it possible order handlers (do not call `handler-b` until `handler-a` not done)?

**Comment by nikolay-nikitin** [comment]
> Oh never mind it works out of the box. Thanks.

And which solution did you choose?
