### ISSUE TITLE
[AMQP] Auto-recovery connection

### ISSUE THREAD

**Issue by Kolesar** [php-enqueue/enqueue-dev#620]
I cannot find anywhere in the php-enqueue something like:
https://github.com/php-amqplib/php-amqplib/blob/master/demo/connection_recovery_consume.php

Does anybody use an auto-recovery connection with enqueue?

Any suggestion is welcome.

**Comment by makasim** [comment]
The feature is not supported yet.

**Comment by makasim** [comment]
close in favor https://github.com/php-enqueue/enqueue-dev/issues/624
