### ISSUE TITLE
[amqp] Get message count

### ISSUE THREAD

**Issue by J7mbo** [php-enqueue/enqueue-dev#64]
In `AMQPContext::declareQueue()`, calling [`$extQueue->declareQueue()`](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-ext/AmqpContext.php#L130) returns an integer which is the message count. But this isn't returned anywhere by the initial method.

Is my only option to override this context with my own, and copy / paste the `declareQueue()` method code, adding a return for the call through to `AMQP::declareQueue()`? Can I provide a PR? Or is there another way to get a message count from a queue? Thanks!

**Comment by makasim** [comment]
>  Can I provide a PR?

Yes sure. 

Just out of curiosity what is your usecase? Why do you need a number of messages and how do you use that?

**Comment by J7mbo** [comment]
I'm limiting the amount of jobs a given user in my application can add to a queue at any one time. Thanks! Will add a PR soon.

**Comment by grekpg** [comment]
Im not understatnd, how i can get messages queue -  i use symfony bundle. I try 
```

    $factory = new AmqpConnectionFactory('amqp+ext://rabbitmq:rabbitmq@rabit_net:5672/%2f');

        $context = $factory->createContext();

        $fooTopic = $context->createTopic(EnqueueProducer::TOPIC_CREATE_PRODUCT);

        $count = $context->declareTopic($fooTopic);

        $queue = $context->createQueue('aQueue');

        $consumer = $context->createConsumer($fooTopic);
```

where i can count messages ?

**Comment by makasim** [comment]
```
$queue = $context->createQueue('aQueue');
$count = $context->declareQueue($queue);
```

topic (or in terms of rabbitmq -exchange) does not store messages

**Comment by grekpg** [comment]
```
$factory = new AmqpConnectionFactory('amqp+ext://rabbitmq:rabbitmq@rabit_net:5672/%2f');

        $context = $factory->createContext();

       $queue = $context->createQueue('enqueue.app.default');
```

error:

`Server channel error: 406, message: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'enqueue.app.default' in vhost '/': received 'false' but current is 'true'
`
```
  $queue = $context->createQueue('enqueue.app.default');

        $queue->setArgument('durable',true);

        $count = $context->declareQueue($queue);
```

same error. 
Can i get queue from some Symfony service ? or how set durable true (this is default settting from symfony) i just need count messages .. 


![image](https://user-images.githubusercontent.com/2538271/57647922-85c79480-75c4-11e9-988d-f017fcc32fb7.png)

For publish i just use constructor 

`public function __construct(ProducerInterface $producer)`

then 

` $this->producer->sendEvent($topic, $message);`
