### ISSUE TITLE
[RabbitMQ] support for wildcard topics ("topic exchange")

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#65]
RabbitMQ supports specifying an exchange supporting wildcard topics, named a [topic exchange](https://www.rabbitmq.com/tutorials/tutorial-five-php.html).

I'm looking into implementing converting Doctrine events to Enqueue messages (idea is, Doctrine persist and by which triggers async job which was waiting for some precondition). I'd like to be able convert Doctrine events to messages of topic `doctrine.<entity>.<event type>` (for example, `doctrine.image.postPersist`). This could be used for all sorts of things, for example converting Symfony events and listening for `*.ERROR` (which is also on my TODO list).

Having wildcard topic support means processors might subscribe to:
- `doctrine.image.*` - only interested in images
- `doctrine.*.postPersist` - interested in persisting any entity
- `doctrine.image.postPersist` - interested in persiting an Image entity

You can clump all of this together where each processor rejects messages it's not interested in, but in high throughput environments having your processors trigger on each message just to reject them, with RabbitMQ supporting it natively is a wasted opportunity IMO.

**Comment by makasim** [comment]
This feature is supported by amqp transport itself but the semantics will not be supported for client's topics. Though there is always a possibility to overwrite the router processor and put such logic there.
