### ISSUE TITLE
Files still exported

### ISSUE THREAD

**Issue by webmake** [php-enqueue/enqueue-dev#653]
Hello,

recently I made a change https://github.com/php-enqueue/enqueue-dev/pull/588 but it seems with 0.8.41 version doesn't work. For example you can see https://github.com/sebastianbergmann/phpunit/blob/master/.gitattributes nothing differs, but in `vendor` directory there is no `/build`.

I suspect that scripts doing split doesn't respect somehow mentioned `.gitattributes` file, or maybe splitted repos have custom settings, can it be?

**Comment by makasim** [comment]
@webmake it went to master which is 0.9 version

**Comment by makasim** [comment]
You could backport it to 0.8 branch

**Comment by makasim** [comment]
@webmake 0.8.42 should be good. could you please?
