### ISSUE TITLE
v0.9.0 packages have wrong constraints

### ISSUE THREAD

**Issue by enumag** [php-enqueue/enqueue-dev#659]
The version constraints used in 0.9.0 for example [here](https://github.com/php-enqueue/enqueue-bundle/blob/0.9.0/composer.json?ts=4#L13-L14) don't allow installation of stable versions of those packages. `composer require enqueue/enqueue-bundle` simply fails unless `minimum-stability` is set to `dev` in which case all other enqueue packages are installed as `dev-master` instead of `0.9.0` even if `prefer-stable` is set to true.

For example:

```
{
    "require": {
        "enqueue/enqueue-bundle": "^0.9.0"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Run `composer install` with this composer.json and see the installed versions. Expected result is for all packages to be installed in stable versions.

By the way `enqueue/dsn` doesn't even have a 0.9.0 tag which is most likely a bug too.

**Comment by Steveb-p** [comment]
According to https://getcomposer.org/doc/articles/versions.md#stability-constraints `-dev` implies dev stability only. It isn't explicitly stated that it prevents installation of stable packages, but this does seem to occur:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for enqueue/enqueue-bundle ^0.9 -> satisfiable by enqueue/enqueue-bundle[0.9.0].
    - enqueue/enqueue-bundle 0.9.0 requires enqueue/enqueue 0.9.x-dev -> satisfiable by enqueue/enqueue[0.9.x-dev] but these conflict with your requirements or minimum-stability.

xxx@xxx:~/xxx$ composer require enqueue/enqueue
Using version ^0.9.0 for enqueue/enqueue
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for enqueue/enqueue-bundle ^0.9 -> satisfiable by enqueue/enqueue-bundle[0.9.0].
    - enqueue/enqueue-bundle 0.9.0 requires enqueue/enqueue 0.9.x-dev -> satisfiable by enqueue/enqueue[0.9.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for enqueue/enqueue ^0.9.0 -> satisfiable by enqueue/enqueue[0.9.0].
    - enqueue/enqueue 0.9.0 requires enqueue/null 0.9.x-dev -> satisfiable by enqueue/null[0.9.x-dev] but these conflict with your requirements or minimum-stability.
```

Removal of `-dev` in composer files should do the trick?

**Comment by enumag** [comment]
> Removal of `-dev` in composer files should do the trick?

Yeah it would do the trick but `0.9.x` is equivalent to `^0.9` which is more common syntax so I'd suggest using that instead.

**Comment by Steveb-p** [comment]
@makasim already pushed a PR with it. It should be out soon. (#660)

**Comment by enumag** [comment]
Great, thank you guys!

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/CHANGELOG.md#091-2018-11-27
