### ISSUE TITLE
How to add route?

### ISSUE THREAD

**Issue by AndriySvirin** [php-enqueue/enqueue-dev#663]
Please point me how to add route? Version 0.9.1. Symfony 4.

**Comment by makasim** [comment]
Right now you can do it by registering a processor and tagging it (enqueue.command_subscriber, enqueue.topic_subscriber or enqueue.processor). You could also write a compiler pass that adds a route to route collection service directly. 

In future, it would be possible to add routes in bundle config https://github.com/php-enqueue/enqueue-dev/issues/593
