### ISSUE TITLE
Deprecation notices

### ISSUE THREAD

**Issue by chalasr** [php-enqueue/enqueue-dev#667]
While upgrading to Symfony 4.2, I have the following unexpected deprecation notices:

>The "Enqueue\Null\NullConnectionFactory" class implements "Interop\Queue\PsrConnectionFactory" that is deprecated will be removed in later versions. use one without Psr prefix.
--
The "Enqueue\Redis\RedisConnectionFactory" class implements "Interop\Queue\PsrConnectionFactory" that is deprecated will be removed in later versions. use one without Psr prefix.
--
The "Enqueue\Consumption\QueueConsumer::bindCallback()" method will require a new "string\|InteropQueue $queueName" argument in the next major version of its parent class "Enqueue\Consumption\QueueConsumerInterface"
--
The "Enqueue\Client\RouterProcessor" class implements "Interop\Queue\PsrProcessor" that is deprecated will be removed in later versions. use one without Psr prefix.
--
The "Enqueue\Client\DelegateProcessor" class implements "Interop\Queue\PsrProcessor" that is deprecated will be removed in later versions. use one without Psr prefix.

It looks like some enqueue packages rely on deprecated features/classes of other enqueue packages, nothing I can fix on my side. 
I'll give it a try, please stop me if you see a wontfix in the list.

**Comment by PaulRouss3l** [comment]
You can add the `0.7.x-dev` version of `queue-interop/queue-interop` to your composer.json to avoid this issue for now

**Comment by makasim** [comment]
fyi there is a stable 0.7 version of queue-interop

**Comment by chalasr** [comment]
Well, I don't require `queue-interop/queue-interop` explicitly and the version I have is `0.7.1`. Here are my requirements:

```
enqueue/enqueue-bundle  v0.9.1
enqueue/messenger-adapter v0.2.0
enqueue/redis  v0.9.1
```

And I get the deprecation notices mentioned above.
I still think this is not a dependency issue on my side but a bug in enqueue (broken BC layers).

**Comment by chalasr** [comment]
The deprecated interfaces still exist in enqueue-interop v0.7.1, hence the notices. We probably need a new release.

**Comment by makasim** [comment]
Unfortunately, the deprecation notices are in 0.7 branch. There is no way to avoid it. 

I am going to release queue interop 0.8 version which would be completely compatible with 0.7 releases except old interfaces are removed.

**Comment by chalasr** [comment]
Fine for me, please close this issue once it is released.

**Comment by chalasr** [comment]
Thanks @makasim

**Comment by makasim** [comment]
To get rid of the deprecated interface make sure you `composer req queue-interop/queue-interop:^0.8`
