### ISSUE TITLE
Enqueue 0.9 migration

### ISSUE THREAD

**Issue by enumag** [php-enqueue/enqueue-dev#668]
Hi. I'm trying to migrate my application to enqueue 0.9 but there are some BC breaks I don't know how to solve.

I was using a custom client processor based on [this](https://github.com/prooph/psb-enqueue-producer/blob/master/src/EnqueueMessageProcessor.php) and configured like this:

```
    App\Library\Prooph\Enqueue\EnqueueMessageProcessor:
        tags:
            - { name: 'enqueue.client.processor', topicName: '__command__', processorName: 'prooph' }
```

In Enqueue 0.9 the `enqueue.client.processor` tag is no longer used and I'm unsure what to use instead. I found a `enqueue.command_subscriber` which should be used with `Enqueue\Client\CommandSubscriberInterface` but that's not a good way for me because I want to keep the `processorName: 'prooph'` in yaml config and not move it to the processor class.

Can you help me with this please? Is there some migration guide? (Could not find any.)

**Comment by makasim** [comment]
[enqueue.processor](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Symfony/Client/DependencyInjection/BuildProcessorRoutesPass.php#L29) tag should be used.

**Comment by enumag** [comment]
Thanks, that helped.

For anyone reading this, here is the fixed configuration:

```
    App\Library\Prooph\Enqueue\EnqueueMessageProcessor:
        tags:
            - { name: 'enqueue.processor', command: 'prooph' }
```

**Comment by makasim** [comment]
https://twitter.com/maksim_ka2/status/1040199957452664832
