### ISSUE TITLE
JobQueue/Job shouldn't be required when Doctrine schema update

### ISSUE THREAD

**Issue by kayue** [php-enqueue/enqueue-dev#67]
When I run `./bin/console do:sc:up --force` I encounter the following error:

```
PHP Fatal error:  Class 'Enqueue\JobQueue\Job' not found in /home/ubuntu/HypebeastEditorial/vendor/enqueue/enqueue-bundle/Entity/Job.php on line 13
```

JobQueue shouldn't be needed because it is default off.

**Comment by kayue** [comment]
Actually the real problem is `Enqueue\JobQueue\Job` doesn't exist

**Comment by kayue** [comment]
Had to add `enqueue/job-queue` to require-dev, not sure is there a way to avoid adding this library because it is never really used.

**Comment by makasim** [comment]
Yeah, that's a bug. I am thinking about moving job entity from the bundle to job-queue package.
