### ISSUE TITLE
[Doctrine] add support to convert Doctrine events to Enqueue messages

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#68]
[Doctrine2 has lifecycle events](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events) which trigger on create, update, delete. We can hook into those events and push a new message with enough information a processor might do something with it (for example, clear cache, run webhooks, run long running jobs which waited for that entity to reach that state in the attached state machine, etc).

I've created [a sample implementation](https://gist.github.com/dkarlovi/b2a9109972852eaa7c31249f09006291) with usage example from Symfony container (disregard the `userToken` stuff in the processor, that's a hacky implementation for which I'll open another issue).

It works like this (C/P from gitter):
1) you create an entity, persist it
2) Doctrine triggers a postPersist, passing the entity
3) DoctrineEventConverter creates a new DoctrineEventMessage from the Doctrine event  
(passing event type, entity class and entity PK)
4) TestProcessor attaches a user token to the message before sending it  
(this is temporary, need a better way to do it, maybe an extension of some sort?)
5) DoctrineEventConverter sends the message via the producer
6) \<transport\>
7) worker running enqueue:consume picks up the message, passes it back to DoctrineEventConverter
8) DoctrineEventConverter creates a new DoctrineEventMessage from the PSR message
9) TestProcessor pulls the user token from the message, stores it to its own tokenStorage and also to gedmo (temporary, also)
10) DoctrineEventConverter fetches the entity by class+ID, stores it to DoctrineEventMessage and passes it to TestProcessor
11) TestProcessor appends the string " processed" to the entity name
12) Doctrine triggers a postUpdate, passing the entity
13) we start from 3) again, but this time the origin is the worker, not ourselves
14) if anybody was listening for postUpdate, it would trigger here again (so you can chain events)
15) it stops once all processors decline to do an entity change

**Comment by dkarlovi** [comment]
Just a reminder for myself: this approach does NOT work. If you attach two listeners to postPersist, seeing as the RabbitMQ exchange is "fanout", there will be a Cartesian amount of messages (N = number of listeners).

Doctrine events need to be converted to Enqueue messages from a **single** service which triggers all the events (for all listeners).

**Comment by makasim** [comment]
This could be implemented as a standalone package. but I prefer not to add such stuff directly in this repo

**Comment by dkarlovi** [comment]
@makasim fair enough, but I don't think it's any more involved than [Doctrine extensions in the bundle](https://github.com/php-enqueue/enqueue-dev/tree/master/pkg/enqueue-bundle/Consumption/Extension).
