### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by gnumoksha** [php-enqueue/enqueue-dev#681]
It seems the snippet for cli commands in SimpleClient is outdated since the constructor signature is wrong.

https://github.com/php-enqueue/enqueue-dev/blob/master/docs/client/quick_tour.md#cli-commands

**Comment by gnumoksha** [comment]
This documentation is affected to https://github.com/php-enqueue/enqueue-dev/blob/master/docs/quick_tour.md#cli-commands

**Comment by makasim** [comment]
the doc is updated
