### ISSUE TITLE
Interface mismatch on the documentation

### ISSUE THREAD

**Issue by gnumoksha** [php-enqueue/enqueue-dev#684]
## Issue
There is some mismatch between php-enqueue documentation and the https://github.com/queue-interop/queue-interop interfaces since the documentation says to use `Interop\Queue\Processor` but the code for this interface is outdated and only extends PsrProcessor, which uses `PsrMessage` and `PsrContext`.

## Steps to reproduce
* `composer require enqueue/simple-client enqueue/amqp-ext`

Maybe is related to https://github.com/php-enqueue/enqueue-dev/issues/667

**Comment by makasim** [comment]
Which Enqueue version do you use?

**Comment by makasim** [comment]
queue-interop 0.7 is designed the way it supports old psr prefixed interfaces as well as new ones. Prefixed and not prefixed interface are the same things and should simply work.

**Comment by makasim** [comment]
To get rid of the deprecated interface make sure you `composer req queue-interop/queue-interop:^0.8`
