### ISSUE TITLE
[Symfony] add support to transfer tokenStorage (user info) to the worker

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#69]
Implementing #68, I've found the processor needs to have information which user ran the query (I'm using the Blameable Doctrine2 extension).

I've added this as [a temporary hack](https://gist.github.com/dkarlovi/b2a9109972852eaa7c31249f09006291#file-testprocessor-php-L96-L120) in the implementation, but the real solution would be to have an extension which would transfer the current `tokenStorage` from the message origin to the processor. This way we could use other Symfony features (like `authorizationChecker` for example) in our processors as naturally as we would in the web app.

We coul probably also trigger some core Symfony event (like `kernel.request`?) to make [other listeners](https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/EventListener/BlameListener.php#L54-L68) run, but that would be a nice bonus: after having the user token in place, it's easy doing some of the stuff yourself.

**Comment by makasim** [comment]
PR is welcome
