### ISSUE TITLE
[Bug] AsyncListener recieve wrong eventQueue

### ISSUE THREAD

**Issue by grachevko** [php-enqueue/enqueue-dev#690]
[AsyncListener](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/AsyncListener.php#L36) recieve only [symfony_events](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/Resources/config/services.yml#L2) in $eventQueue, without `prefix` and `app_name`

**Comment by grachevko** [comment]
@makasim okey, but documentation has no information about this behaviour. Moreover async-event-dispatcher not working out of the box with default parameters from docs.

After hours of debugging, to start it working i had to write this
```php
$container->getDefinition('enqueue.events.async_listener')
    ->replaceArgument(2, 'enqueue.app.symfony_events');
```

Because consumer listening `enqueue.app.symfony_events`, while `AsyncListener` push events to `symfony_events` queue.

**Comment by makasim** [comment]
There is a bug, this command subscriber options should be adjusted here 

https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/AsyncProcessor.php#L57

**Comment by makasim** [comment]
like here https://gist.github.com/OskarStark/129e9c8cb493d0c91c3ce479357147dc#gistcomment-2785563

**Comment by grachevko** [comment]
@makasim yes tried, it crash client, because it publish to `enqueue.app.enqueue.app.symfony_events`

**Comment by GCalmels** [comment]
Hello, I have the same issue but I have the last changed files... If I change `enqueue_events_queue` to `enqueue.app.symfony_events`, I have : `enqueue.app.enqueue.app.symfony_events`... 
I don't know how to set the right queue name
