### ISSUE TITLE
Improved error handling DbalProducer when no table enqueue

### ISSUE THREAD

**Issue by rbaarsma** [php-enqueue/enqueue-dev#695]
In `DbalProducer` an Exception is thrown when the `enqueue` table does not yet exist, because `enqueue:setup-broker` has not been run yet. The resulting message is very unclear and has absolutely no information: `The transport fails to send the message due to some internal error.`

It's even better to simply NOT catch the exception here, as it will directly show that the `INSERT` failed on the `enqueue` table and most devs will know what to do then.

But maybe even better is to write in this exception that the most likely cause is that the `enqueue:setup-broker` has not been run yet, but also add the Doctrine error.

For example:
```
catch (DBALException $exception) {
    throw new Exception("The Dbal transport failed to create the message due to a database error. Most likely you have not run the `enqueue:setup-broker` command. Doctrine error: $exception");|
}
```

In my opinion you should always try to avoid catching generic exceptions, as it will not help to catch them and throw them again with less info

**Comment by makasim** [comment]
The previous exception contains more details on the cause, [there is the third argument](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/dbal/DbalProducer.php#L142).

setup-broker is a feature of a higher level library called Enqueue Client and dbal transport could be used directly or in a context where is another abstraction is used. So. mentioning it in the transport directly is not accurate.
