### ISSUE TITLE
Add support for production extensions

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#70]
Much like consumption extensions, it would be great to have a production extension. If possible, method names should not overlap as you might like to have the same extension class be both a production and consumption extension.

It would allow for implementing #69 like a extension in which the same extension would sent itself the user token, receive and store it at the other end.

**Comment by makasim** [comment]
This one is in our list.

**Comment by dkarlovi** [comment]
That was crazy fast, you guys rock. I'll try to do #69 with this.
