### ISSUE TITLE
[Symfony][RabbitMQ] Impossible to consume message from queue

### ISSUE THREAD

**Issue by Jonathan-Lathiere** [php-enqueue/enqueue-dev#700]
Hello,

When running `enqueue:consume <queue_name>`, I get this error `Got message without required parameter: "enqueue.processor"`

The message was inserted directly (produced) in RabbitMQ queue with the RabbitMQ management interface (without using enqueue:produce command).

Using following versions :
```
enqueue/amqp-bunny                    0.9.2              Message Queue Amqp Transport
enqueue/enqueue                       0.9.3              Message Queue Library
enqueue/enqueue-bundle                0.9.3              Message Queue Bundle
```

**Comment by makasim** [comment]
Use `enqueue:transport:consume` instead. The command you are referring is a Enqueue Client one and it expects some additional message attributes to be set

**Comment by makasim** [comment]
Dont forget to tag a processor with `enqueue.transport.processor` 

more here https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/message_processor.md#register-a-transport-processor

**Comment by Jonathan-Lathiere** [comment]
Thanks ! It Works :)
