### ISSUE TITLE
Question: Execution interrupted and normal behaviour

### ISSUE THREAD

**Issue by Kolesar** [php-enqueue/enqueue-dev#708]
I tried to use Consumption Time Extension in my code, but once when the interrupted trigger is set my PHP program except with error: `PRECONDITION_FAILED - unknown delivery tag 1`

And I don't know if this normal behavior or not.

**Comment by makasim** [comment]
I don't have an answer.

**Comment by makasim** [comment]
Try to ask in a chat https://gitter.im/php-enqueue/Lobby. Maybe someone there has the answer. 

Feel free to reopen if it turns out to be doable bug or feature
