### ISSUE TITLE
Queue named `run_command` created by enqueue

### ISSUE THREAD

**Issue by Cicatrice** [php-enqueue/enqueue-dev#710]
Hello,

Since last update, I noticed that a queue named `run_command` is created by enqueue. The issue is that I'm using SQS with several different instances of enqueue workers running in the same AWS account and I don't want my workers to conflict with each other.

I noticed this code has recently been added : https://github.com/php-enqueue/enqueue-dev/commit/f7bbf55fe9fa9c30a49780ffaf8cbbfd888ab89f#diff-b6fe49b31ab2f605ee812379d959ef3eR21

Maybe we could have the `run_command` queue available as a parameters in `enqueue.yaml` config file ?

Many thanks,
Kind regards

**Comment by makasim** [comment]
1. You could disable async commands: 

```
enqueue:
        async_commands:
            enabled:              false
```

2. or overwrite a processor service and change the tag attributes

3. contribute a way to configure using enqueue config.
