### ISSUE TITLE
[monitoring] Add support of DataDog

### ISSUE THREAD

**Issue by uro** [php-enqueue/enqueue-dev#714]
I would like to be able to display the enqueue statistics in [DataDog](https://datadoghq.com). 

Should I add the support of datadog to your monitoring package as is the wamp and influxdb?
Or should I solve it externally?

If you like to see DataDog as a new monitoring provider, I'll be happy to implement it. 

https://github.com/DataDog/php-datadogstatsd

@makasim

**Comment by makasim** [comment]
That would be a great addition.

**Comment by makasim** [comment]
There is a PR, closing
