### ISSUE TITLE
Different amqp handle props in different manner.

### ISSUE THREAD

**Issue by marhub** [php-enqueue/enqueue-dev#719]
Actual result:
in amqp bunny transport props are put into **headers.application_headers**
in ampq-lib transport, props are put into **headers**

Expected result:
I can see props next to headers, not injected into headers key.

If that's expected result - then someone can please explain me why?

**Comment by makasim** [comment]
This behavior is expected. AMQP sends properties as a special header called "application_headers".

**Comment by marhub** [comment]
Sorry, but you do not get me.

considering following code: 

```php 
$headers = [
       'reply_to' => $replyToQueue->getQueueName(),
       'correlation_id' => Uuid::uuid4()->toString()
];
$message = $this->context->createMessage(
       json_encode($data),
       [], // props
       $headers 
);
```
 when using E**nqueue\AmqpBunny\AmqpConnectionFactory** => message ( seems to be not ok ):

![image](https://user-images.githubusercontent.com/2960432/52218965-feb7a180-289b-11e9-8e66-1e82de78610c.png)

when using  **Enqueue\AmqpLib\AmqpConnectionFactory** => message is different ( seems to be ok )

![image](https://user-images.githubusercontent.com/2960432/52219065-36264e00-289c-11e9-9121-98e11ff74dd5.png)


**I expect them to be same in all implementations!**

**Comment by makasim** [comment]
Agree, have you found out why this happens?

**Comment by marhub** [comment]
I belive it's due to internal implementation of bunny lib

**Comment by makasim** [comment]
> I belive it's due to internal implementation of bunny lib

closing than, should be addressed in bunny repo.
