### ISSUE TITLE
[client] Add app name prefix to async events queue

### ISSUE THREAD

**Issue by dextervip** [php-enqueue/enqueue-dev#727]
Hey,

It would be nice to add app name in client config to setup a queue name like myapp.symfony_events instead of symfony_events when using async events feature. So that I wont need to create new virtual host for each new app.

**Comment by makasim** [comment]
Pull request is very welcome.

**Comment by makasim** [comment]
you could redefine async events processor service (one in Symfony DI) and adjust tag parameters accoding to your needs. For example you could set `prefix_queue: true` so Enqueue Client prefixes it.

**Comment by dextervip** [comment]
Yeah, I am using enqueue bundle so I ended up overriding the parameter enqueue_events_queue in my app, looks okay!
