### ISSUE TITLE
[job-queue] CalculateRootJobStatusProcessor subscribed to command instead of topic

### ISSUE THREAD

**Issue by you-ser** [php-enqueue/enqueue-dev#729]
Problem:
CalculateRootJobStatusProcessor stop wotking after commit [https://github.com/php-enqueue/job-queue/commit/1362b4d0732fab5d474b0bd6c1fc649f4044e579](https://github.com/php-enqueue/job-queue/commit/1362b4d0732fab5d474b0bd6c1fc649f4044e579)

Description:
Class `Enqueue\JobQueue\CalculateRootJobStatusProcessor` now implementing `CommandSubscriberInterface` and  subscribed to **command** :

```php
Enqueue\JobQueue\Commands::CALCULATE_ROOT_JOB_STATUS
```

But, class `Enqueue\JobQueue\JobProcessor` at method `sendCalculateRootJobStatusEvent` sending an **event** by producer, not **command**, so root job status is never updates.

```php
//JobProcessor.php
/**
     * @see https://github.com/php-enqueue/enqueue-dev/pull/222#issuecomment-336102749 See for rationale
     *
     * @param Job $job
     */
    protected function sendCalculateRootJobStatusEvent(Job $job)
    {
        $this->producer->sendEvent(Commands::CALCULATE_ROOT_JOB_STATUS, [
            'jobId' => $job->getId(),
        ]);
    }
```
       

Possible solution:
1 - `CalculateRootJobStatusProcessor` should implement `TopicSubscriberInterface` again.
2 - `JobProcessor` should sent **command** instead of **event** at method `sendCalculateRootJobStatusEvent`

**Comment by makasim** [comment]
sendEvent should be replaced with sendCommand
