### ISSUE TITLE
[client] GenericDriver changing queue name to lowercase

### ISSUE THREAD

**Issue by gquiles-perez911** [php-enqueue/enqueue-dev#730]
Can I use uppercase queues with SQS? I have a SQS queue name "Test" and when I use `console enqueue:consume Test` I get the following error "The specified queue does not exist for this wsdl version". After investigation I noticed that GenericDriver has `strtolower` in createTransportQueueName. Is there a way to keep the uppercases for Queue names?

**Comment by makasim** [comment]
strtolower should be removed but there is BC that we must preserve among all 0.9.x version. So, it should be possible to disable strtolower via driver option (enabled by default).

**Comment by makasim** [comment]
For now, you can overwrite this method:

https://github.com/php-enqueue/enqueue-dev/blob/516acfa3e5c283ce8195e6696d3af3e0e6dc7dfc/pkg/enqueue/Client/Driver/GenericDriver.php#L245-L251

**Comment by makasim** [comment]
needs pr
