### ISSUE TITLE
[dbal] message is not added to the queue

### ISSUE THREAD

**Issue by otzy** [php-enqueue/enqueue-dev#731]
I use dbal package 0.9.6 with mysql.
producer->send() does not add a record to the queue.

$this->context->getDbalConnection()->insert() in DbalProducer.php:118 returns 0 but no any exception thrown.

But if I comment out the third parameter with types, the message is added successfully.
The problem seems to be in the parameter `'redelivered' => Type::BOOLEAN,`
When it's changed to `'redelivered' => Type::SMALLINT,` everything works

**Comment by otzy** [comment]
I think it's also worth to check that insert() returned 1 and throw an exception otherwise.

And btw. it will be nice if you inherited all your exceptions from RuntimeException. Most of them I think caused by the wrong usage of library and there is no need to catch them in the app

**Comment by makasim** [comment]
that strange since there are some functional tests which pass. 

Would you like to submit a PR?
