### ISSUE TITLE
[dbal] How to pass redeliver config to the DbalContext

### ISSUE THREAD

**Issue by j-schumann** [php-enqueue/enqueue-dev#734]
Hello,
I'm using: enqueue/messenger-adapter:0.2.0 with enqueue/dbal:0.9.5 in Symfony 4.2 and I see no way to pass config to the context etc.:

Enqueue\Dbal\DbalConsumer defaults to a redelivery delay of 20 minutes. Enqueue\Dbal\DbalContext passes its config 'redelivery_delay' on when it creates a new consumer but how can I pass this option to the context? I tried appending it to the database DSN, adding it directly as option in enqueue\ in the enqueue.yaml, in enqueue\client and enqueue\client\driver_options with no success

Enqueue\Bundle\DependencyInjection\Configuration has no code for this option, nor does Enqueue\Symfony\Client\DependencyInjection\ClientFactory::getConfiguration.
Same for 'polling_interval'.

I also tried to add ?redelivery_delay=2400 to the MESSENGER_TRANSPORT_DSN but there too it is no supported option

How do we configure this options?
Optimum would be if we could create an envelope with the symfony messenger which contained a custom redelivery delay so we could overwrite the default for individual messages.

Thanks in advance,
JS

**Comment by makasim** [comment]
Please open the issue on enqueue messenger adapter repository.

**Comment by j-schumann** [comment]
Shouldn't these options be also configurable when only using enqueue-bundle without the messenger?

**Comment by makasim** [comment]
The ability to configure it should be implemented, right now it is not possible at all in messenger and possible with queue consumer extension if you enqueue bundle

**Comment by j-schumann** [comment]
Was anything changed? Where do I find the documentation for passing the config?

**Comment by es-cologne** [comment]
I'll call `redeliverAfter` a _feature bug_ of enqueue

**Comment by jav974** [comment]
This can be achieved like this:

enqueue.yaml:
`enqueue:
    default:
        transport:
            dsn: '%env(resolve:DATABASE_URL)%'
            redelivery_delay: 86400000
`
