### ISSUE TITLE
[Elastica Bundle] New release

### ISSUE THREAD

**Issue by mbabic131** [php-enqueue/enqueue-dev#742]
Hello, 

I was trying to update `enqueue/enqueue-bundle` to `^0.9` but was unable to do so because of constraints in `enqueue/elastica-bundle`.  Last version of this bundle requires `"enqueue/enqueue-bundle": "^0.8"`.  

Releasing a new version of `enqueue/elastica-bundle` will fix this problem.

**Comment by makasim** [comment]
done - https://github.com/php-enqueue/enqueue-elastica-bundle/releases/tag/0.9.0

please test it
