### ISSUE TITLE
Add ability to process message in parallel

### ISSUE THREAD

**Issue by symfu** [php-enqueue/enqueue-dev#746]
Currently, messages are processed one by one, that's inefficient, maybe we can utils other async frameworks to process messages in parallel.

I've looked into frameworks like amphp, it seems fit this quest, any idea?

**Comment by makasim** [comment]
If you want to process messages in parallel you should run more consumers. It is not possible to process them in parallel in one process. PHP interpreter executes one command at a time. amphp would help if there is non-blocking IO, the time spent there could be used to do some other stuff. But complexity would be to high

**Comment by Fgruntjes** [comment]
@makasim the complexity is definitely higher but the complexity could be left up to the user. All it needs to do is let the `\Interop\Queue\Processor::process` method to allow to return `null` and another way of sending that ACK, REJECT and REQUEUE response.

For example:
```php
<?php

use Interop\Queue\Context;
use Interop\Queue\Message;
use Interop\Queue\Processor;
use Symfony\Component\Process\Process;

class AsyncProcessor implements Processor
{
    private $messages = [];
    private $processes = [];

    public function process(Message $message, Context $context)
    {
        $this->start($message);
        $this->cleanOldMessages();
    }

    private function start(Message $message): void
    {
        // do some async action like a symfony process
        $index = count($this->messages);
        $process = Process::fromShellCommandline('some sleepy command');
        $process->start();
        $process->isRunning();

        $this->messages[$index] = $message;
        $this->processes[$index] = $process;
    }

    private function cleanOldMessages(): void
    {
        foreach ($this->processes as $index => $process) {
            if (!$process->isRunning()) {
                $this->ackMessage($this->messages[$index], $process);
                unset($this->processes[$index], $this->messages[$index]);
            }
        }
    }

    private function ackMessage(Message $message, Process $process): void
    {
        if ($process->isSuccessful()) {
            // send Processor::REJECT;
        } else {
            // send Processor::ACK;
        }
    }
}
```

Since PHP has a relatively high memory footprint and for us the problem is that we would need to run about 5000 concurrent ssh command's that would execute something on a remote server. With the symfony framework, php etc the memory footprint would be too high. The above example however would be no problem at all.

Please concider reopening the issue.

**Comment by makasim** [comment]
the status https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Result.php#L25 could be used to achieve what you want

**Comment by Fgruntjes** [comment]
Thank you for your response, the only problem left is sending the actual ACK / REJECT. I have now used a `PostMessageReceivedExtensionInterface` extension to remember the consumer for a message. This seems very hacky to me but could not figure out another way to manage. Do you have any suggestions?

**Comment by makasim** [comment]
You can use context (you get it as the second argument, you can use it to ack\reject messages accumulated. 

https://github.com/queue-interop/queue-interop/blob/master/src/Processor.php#L36
