### ISSUE TITLE
Symfony async_events. Custom transformer never used

### ISSUE THREAD

**Issue by GCalmels** [php-enqueue/enqueue-dev#747]
When I add a custom transformer with a regex eventName : `'/app\.text\..*?/'`, the transformer is never used.
I think it is because `eventsMap` in Registry is an array with the first element : `'/.*/'` so it is always `true` for regex eventName, right ?

I don't know how to add custom transformers before the standard transformer ... but maybe I could add `array_reverse` to `eventsMap` ?

**Comment by makasim** [comment]
I think that the default one should be added here https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/DependencyInjection/AsyncTransformersPass.php#L32 as the last one.

**Comment by makasim** [comment]
fixed
