### ISSUE TITLE
[Redis] messages lost and non-atomic operations

### ISSUE THREAD

**Issue by cshum** [php-enqueue/enqueue-dev#750]
During our usage of Enqueue Redis on a  possibly unstable connections with lots of retries, we occurred ~3-5 message lost out of ~50000 messages. 

Having looked into source the [receiveMessage/processResult](https://github.com/php-enqueue/redis/blob/master/RedisConsumerHelperTrait.php#L23) [acknowledge/requeue](https://github.com/php-enqueue/redis/blob/master/RedisConsumer.php#L114) are indeed non-atomic operations like brpop + zadd, zrem + lpush etc.

Do you think if implementations of atomic operations, like [RPOPLPUSH](https://redis.io/commands/rpoplpush), [BRPOPLPUSH](https://redis.io/commands/brpoplpush), or any kind of multi or lua scripts would be feasible?

**Comment by makasim** [comment]
That should be addressed indeed, not sure what would be the best approach to fix it though.

**Comment by cshum** [comment]
Atomic ones are probably harder to implement.

What about setting add operations _before_ the remove ones? There may be duplicated messages but still better than message lost.

**Comment by makasim** [comment]
If you need strict message delivery guarantee than I'd suggest you to use a real broker such as RabbitMQ or AmazonSQS.

We've investigated the issue at our end looking for a solution to fix it. Unfortunately, we've not come with any better approach. The current one is not ideal but it remains the best one
