### ISSUE TITLE
[amqp] Add setDeliveryMode method to Producer for persistent messages

### ISSUE THREAD

**Issue by tkocjan** [php-enqueue/enqueue-dev#753]
I need to have persistent messages with RabbitMQ. I would really like to set the DeliveryMode on the producer instead of on every message.

JMS has the setDeliveryMode() method on MessageProducer and it seems like enqueue should as well. \Interop\Queue\Producer has the setDeliveryDelay, setPriority and setTimeToLive methods from JMS MessageProducer but not setDeliveryMode. Is there any reason why there is not a setDeliveryMode method?

**Comment by makasim** [comment]
I would add it to amqp only as I've not aware of any other transport that uses the option

https://github.com/queue-interop/amqp-interop/blob/master/src/AmqpProducer.php#L8

**Comment by tkocjan** [comment]
@makasim Is a seperate AmqpDeliveryModeProducer interface necessary if all three amqp transports implement setDeliveryMode and instead just put it in Interop\Amqp\AmqpProducer? Could then just AmqpDeliveryModeProducer

**Comment by makasim** [comment]
needs PR
