### ISSUE TITLE
Is it possible to change queue fos_elastica_doctrine_orm_sync_index_with_object_change name?

### ISSUE THREAD

**Issue by panslaw** [php-enqueue/enqueue-dev#756]
I use one aws account to develop two projects. They use enqueue-elastica-bundle both. So, my two projects use the same queue to get changed objects and it's make conflicts.

Can I set or change fos_elastica_doctrine_orm_sync_index_with_object_change queue name per project?

**Comment by makasim** [comment]
You should overwrite this service https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/DependencyInjection/EnqueueElasticaExtension.php#L60

with your which contains getSubscribedCommand method updated.

**Comment by panslaw** [comment]
Ok, I'll try but that is not enough. If I'm wrong, correct me. 

I should overwrite also https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/DependencyInjection/EnqueueElasticaExtension.php#L75

because changed objects will be saved into default "fos_elastica_doctrine_orm_sync_index_with_object_change" queue:

https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/Doctrine/SyncIndexWithObjectChangeListener.php#L76

**Comment by makasim** [comment]
You are right,  ideally, it should be possible to configure a queue in the bundle config.

**Comment by panslaw** [comment]
I have one more question. 

Can I override https://github.com/php-enqueue/enqueue-elastica-bundle/blob/master/DependencyInjection/EnqueueElasticaExtension.php#L75 when service id is created dynamically?

**Comment by TZK-** [comment]
Can I know why are you disallowing people to set their own queue names ?
I have the same issue as @panslaw and it is not very convinient to override since every classes which might be intersting are not extendable easily.

**Comment by makasim** [comment]
@TZK-  doesn't that state what you want https://github.com/php-enqueue/enqueue-dev/issues/756#issuecomment-460222108. We are on the same side, just someone has to do.
