### ISSUE TITLE
[Laravel] Queues are not created automatically but only on send or consume. 

### ISSUE THREAD

**Issue by Spartaques** [php-enqueue/enqueue-dev#762]

**Comment by Spartaques** [comment]
I tried to use laravel-enqueue as default queue, but when i exec php artisan queue:work interop i got this error:
https://monosnap.com/file/PWzb9xLSnTS4mB72JJWE1sDsUlEzHs
As i understand, queues not created automatically. I can create queue using rabbitmq management plugin, but this is not the best idea.

**Comment by Spartaques** [comment]
Fixed. Queue was created automatically when i pushed some message to queue. SO QUEUE was cread when message produced but not when i called php artisan queue:work.

**Comment by makasim** [comment]
That would be great to add a kind of setupBroker method to the Laravel queue object so the queue could instruct the broker about required setup.  That would handy for such transports as SQS and AMQP, RabbitMQ

We could go one step further and introduce a setup broker cli command. Could be used in prod

**Comment by makasim** [comment]
As far as I know, Laravel does not have a notion of broker setup API. So we should do a custom solution for Laravel Queue integration. 

The integration of Enqueue Client has that feature and expose a cli command called enqueue:broker-setup. 

Feel free to send a PR that address the issue.
