### ISSUE TITLE
[Laravel] SimpleClient works only with fanout.

### ISSUE THREAD

**Issue by Spartaques** [php-enqueue/enqueue-dev#763]
I have some case when i need to use queue instead of fanout. I need to recent messages when something went wrong. But SimpleClient as i understood correctly creates only fanout exchange.
I need pocibility to adopt this functionality:
https://blog.forma-pro.com/message-bus-to-every-php-application-42a7d3fbb30b 
to Laravel app.

**Comment by makasim** [comment]
The client can send commands directly to the destination queue. Simple client does support that feature yet.
