### ISSUE TITLE
[bundle][asyncEvents] Reenqueue on failure

### ISSUE THREAD

**Issue by nataliaAznar** [php-enqueue/enqueue-dev#773]
I am trying to reenqueue an event when it fails, but it is dispatched as a sync event.
Is there any way to reenqueue an event when it fails?

**Comment by makasim** [comment]
[Sync mode](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/async-event-dispatcher/AsyncListener.php#L58) has to be disabled for the event you want to requeue. 

There is no way to do it for a single event atm

**Comment by nataliaAznar** [comment]
I have already checked that.
My problem is that, in the event, although  it is defined as asynchronous, the sync mode has not been restored when it is executed. Because of this, when I requeue the event, it is dispached as a sync event.
I am trying to inject the AsyncListener in the event, but it seems that is is not defined when de listnere is called:

Cannot autowire service "Listener": argument "$listener" of method "__construct()" references class "Enqueue\AsyncEventDispatcher\AsyncListener" but no such service exists. You should maybe alias this class to the existing "enqueue.events.async_listener" service.

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/pull/777#issuecomment-492535856
