### ISSUE TITLE
Infinite loop when handling an exception (critical bug in my opinion)

### ISSUE THREAD

**Issue by enumag** [php-enqueue/enqueue-dev#774]
I'm using the Symfony bundle. I start my consumer using `bin/console enqueue/consume` and sure enough it works just fine.

However if one of the consumed messages causes an exception, the consumer freezes without even writing anything to console or log - the exception is nowhere to be seen.

I used xdebug to find out what caused it and I believe the reason is that Symfony/Console runs into an infinite loop while trying to print the exception.

The reason why that happens is this code in your bundle: https://github.com/php-enqueue/enqueue-dev/blob/499360ee85dd84c5d0f91917238a2a5b42c5d44a/pkg/enqueue/Consumption/QueueConsumer.php#L320-L331

It effectively creates a pair of exceptions where each has set the other one as the previous:

```php
$e->getPrevious()->getPrevious() === $e // true
```

(or a longer chain of exceptions where the last one has the first one as previous - still effectively a cycle of exceptions)

I don't quite understand what is the idea behind this but obviously when an error handler tries to dump the exception chain this causes an infinite loop because `->getPrevious()` never returns null.

Can you explain what the code in `QueueConsumer::onProcessorException()` is supposed to do? I'm quite sure this isn't intentional. When I remove the code I linked above, everything works as expected.

**Comment by enumag** [comment]
Ping @nicolas-grekas. You're the original [author](https://github.com/symfony/symfony/commit/bb020f4a729b7178ebabd26cbab6bb225deb3f09) of this code in Symfony. What on earth is the reason to create an infinite loop of exceptions?

**Comment by makasim** [comment]
As far as understand this https://github.com/php-enqueue/enqueue-dev/pull/725 fixes the issue. Could you check?

**Comment by enumag** [comment]
@makasim No it doesn't. I'm using v0.9.7 which already has this fix.

Maybe the condition there supposed to be `if ($exception !== $e) {`? Because that's what happened in my case - `$exception` and `$e` are one and the same while `$wrapper` is different.

Also ping @DamienHarper - as the author of #725 you might have an idea.

**Comment by DamienHarper** [comment]
@enumag Sorry I couldn't reply earlier, #725 helped me fix some issues I was experiencing at that time. Recently, I faced again some infinite loops, caused by those self-referencing exceptions, making some of my commands crash again. Though I hadn't enough time to investigate more. 
So thanks for the fix.
