### ISSUE TITLE
[Bundle] Missing commands

### ISSUE THREAD

**Issue by Guikingone** [php-enqueue/enqueue-dev#775]
Hi everyone, 

Small question about the Symfony Bundle, I try to use the bundle in order to send message to a Redis queue, problem is, when I want to debug/list the created topics, the command isn't displayed

Here's the documentation list: https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/cli_commands.md#cli-commands

Here's my terminal:

```
enqueue
  enqueue:consume                                           [enq:c] A client's worker that processes messages. By default it connects to default queue. It select an appropriate message processor based on a message headers
  enqueue:produce                                           Sends an event to the topic
  enqueue:routes                                            [debug:enqueue:routes] A command lists all registered routes.
  enqueue:setup-broker                                      [enq:sb] Setup broker. Configure the broker, creates queues, topics and so on.
  enqueue:transport:consume                                 A worker that consumes message from a broker. To use this broker you have to explicitly set a queue to consume from and a message processor service
```

Any idea about this case? 🤔 

Thanks again for the help :)

**Comment by makasim** [comment]
sorry, I don't get what the problem you face

**Comment by Guikingone** [comment]
I should normally see the `enqueue:topic` command? 

Problem is, I don't see how to debug my topics using the displayed commands 🤔

**Comment by makasim** [comment]
`enqueue:topics` and `enqueue:queues` have been removed. Use `enqueue:routes` instead

**Comment by Guikingone** [comment]
Maybe an update on the documentation could be a good idea?

**Comment by makasim** [comment]
Sure it is
