### ISSUE TITLE
How can I restart the entity manager?

### ISSUE THREAD

**Issue by ahmetilhann** [php-enqueue/enqueue-dev#779]
I am using Symfony version 4.2 . I use other packages I write below. 
```
"php": "^7.1.3",
"ext-ctype": "*",
"ext-iconv": "*",
"enqueue/enqueue-bundle": "^0.9.7",
"enqueue/pheanstalk": "^0.9.7",
"friendsofsymfony/elastica-bundle": "^5.0",
"nelmio/cors-bundle": "^1.5",
"nesbot/carbon": "^2.10",
"symfony/console": "*",
"symfony/flex": "^1.1",
"symfony/framework-bundle": "*",
"symfony/orm-pack": "^1.0",
"symfony/serializer-pack": "^1.0",
"symfony/yaml": "*"
```
I am running the cosume command using a supervisor. I write my supervisor setting below.
```
[program:devlog-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/project-directory/bin/console enqueue:consume --setup-broker
autostart=true
autorestart=true
user=nginx
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/project-directory/worker.log
```
Entity manager is closed after working for a certain period of time. I think I need to start again. But I could not do it in the code. But when the supervisor restarts, everything starts working. How can I solve this problem because I cant always restart supervisor from the beginning.

I'm writing the sample process below.

```
<?php

namespace App\Processor;

use App\Entity\Main\Event;
use Doctrine\ORM\EntityManagerInterface;
use Interop\Queue\Message;
use Interop\Queue\Context;
use Interop\Queue\Processor;
use Enqueue\Client\TopicSubscriberInterface;

class FooProcessor implements Processor, TopicSubscriberInterface
{
    protected $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function process(Message $message, Context $session)
    {
        try {
            $event = new Event();
            $event->setAction('example');

            if (!$this->entityManager->isOpen()) {
                echo "Entity Manger is closed...\n";
                // here i need to restart the entity manager or another solution
            }

            $this->entityManager->persist($event);
            $this->entityManager->flush();
            $this->entityManager->clear();

            echo "Success\n";
            return self::ACK;

        } catch (\Exception $e){
            echo ($e->getMessage())." \n";
            return self::REJECT;
        }
    }

    public static function getSubscribedTopics()
    {
        return ['aFooTopic'];
    }
}
```

**Comment by Steveb-p** [comment]
EntityManager is not expected to restart at this point. ORM team says it can lead to potential desync errors (due to EM being out of sync with actual database state) and it should not be reopened. That's why they don't even provide a way to restart it in original code.

If the reason EntityManager becomes closed is closed connection to database. You can check for connection state and reopen it for long running tasks. That's what I do in my own application. Far from perfect, since at times process requires a restart anyway and you have to be explicit about the reconnection.

**Comment by ahmetilhann** [comment]
> EntityManager is not expected to restart at this point. ORM team says it can lead to potential desync errors (due to EM being out of sync with actual database state) and it should not be reopened. That's why they don't even provide a way to restart it in original code.
> 
> If the reason EntityManager becomes closed is closed connection to database. You can check for connection state and reopen it for long running tasks. That's what I do in my own application. Far from perfect, since at times process requires a restart anyway and you have to be explicit about the reconnection.
> 
> EDIT: Apparently you can also try https://stackoverflow.com/questions/50971579/best-way-to-reset-entity-manager
> 
> > But you can try to call `$this->getDoctrine()->resetManager();` If you need to keep saving things after an exception is thrown.
> 
> where `getDoctrine` should return an instance of `ManagerRegistry` if I understand correctly.
> 
> EDIT2: Also note that according to API spec of Doctrine (https://www.doctrine-project.org/api/persistence/1.0/Doctrine/Common/Persistence/ManagerRegistry.html#method_resetManager) it will be a **new** instance of `EntityManager`.

I tried it but the result didn't change. 
When I started the Supervisor again, I tried something like this.
But did not work again

```
if (!$this->entityManager->isOpen()) {
      shell_exec('supervisorctl reload');
      return self::REQUEUE;
}
```

**Comment by makasim** [comment]
Sorry, this has nothing to do to Enqueue. Feel free to continue a discussion in the closed issue or open an issue on Doctrine repo.

Closing

**Comment by Steveb-p** [comment]
@ahmetilhann why do you even need to interact with `supervisord`? It should - judging from your configuration - restart the process immediately as it **ends**. So all you need to do is allow the process to end.

**Comment by ahmetilhann** [comment]
The problem was solved by changing supervisor settings. I missed the setting.

new supervisor setting

```
[program:devlog-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/metodbox-log-service/bin/console enqueue:consume --setup-broker --env=prod --no-debug --time-limit="now + 5 minutes"
autostart=true
autorestart=true
user=nginx
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/project-directory/worker.log
```

Thanks
