### ISSUE TITLE
Doc example doesn't work

### ISSUE THREAD

**Issue by TomPradat** [php-enqueue/enqueue-dev#783]
In the documentation it's written that you can instanciate a factory (for localhost) with : 

`$factory = new \Enqueue\AmqpLib\AmqpConnectionFactory();`

Though i get an error stating that the Enqueue\Dsn\Dsn class cannot be found. Everythink works fine if i give the factory an empty array.

https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/amqp_bunny.md

**Comment by makasim** [comment]
Do you use composer to install the package?

**Comment by TomPradat** [comment]
Yes i do, i tried to dump the autoloader but still had the problem

**Comment by makasim** [comment]
You are right. `amqp-tools` should require dsn pacakge. In fact it is required but in dev. https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-tools/composer.json#L17

should be moved to require section.

**Comment by TomPradat** [comment]
Yes indeed, do you want me to create a PR or are you handling it ?

**Comment by makasim** [comment]
That would be great if you could send it to us
