### ISSUE TITLE
[Symfony][SQS][Job] Unique Root job still 'running' after children finish

### ISSUE THREAD

**Issue by KDederichs** [php-enqueue/enqueue-dev#786]
Enqueue version 0.9.7

Hey,

I'm running a unique job queue that spawns multiple sub jobs using a command processor.
The problem is that even after all the sub jobs finish, the unique root job is still in the 'running' state and does not finish, thus blocking all other unique jobs with the same name:

![screenshot 2019-02-26 at 13 54 49](https://user-images.githubusercontent.com/24696606/53414075-221ec980-39ce-11e9-99e0-5f648b231d6e.png)

Is there a reason this job does not finish? Can I force it to finish when all its sub jobs are done?

**Comment by KDederichs** [comment]
Update:
It works if I only run a single consumer.
It might be some sort of race condition where the other consumer picks up the ```CALCULATE_ROOT_JOB_STATUS``` event you guys are firing before the other consumer commit the change in status to the database?

**Comment by KDederichs** [comment]
I managed to get around it for now by periodically calling the ```CALCULATE_ROOT_JOB_STATUS``` command myself but that can't be the solution here.

**Comment by KDederichs** [comment]
After lots of frustration it seems to be related to doctrine caching the entity in some way.
So the solution would be to refresh the entity before using it to calculate the root status.
I made you guys a PR to do just that.
@makasim

**Comment by makasim** [comment]
possibly a bug. needs PR
