### ISSUE TITLE
[All] Released packaged should only require other released packages

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#788]
Currently in the 0.9 branch, a lot of packages require `dev` versions of other packages, examples:

https://github.com/php-enqueue/enqueue-dev/blob/7ab383fe6ef0239132d0f9ec72d1beb74aaf1374/pkg/amqp-bunny/composer.json#L12

https://github.com/php-enqueue/enqueue-dev/blob/7ab383fe6ef0239132d0f9ec72d1beb74aaf1374/pkg/amqp-ext/composer.json#L12

https://github.com/php-enqueue/enqueue-dev/blob/7ab383fe6ef0239132d0f9ec72d1beb74aaf1374/pkg/amqp-lib/composer.json#L12

etc. This doesn't allow to install all the packages' release versions but instead, need to install some of them as git clones.

**Comment by makasim** [comment]
That has to be fixed. Would you like to submit a PR?

**Comment by dkarlovi** [comment]
@makasim #790

**Comment by dkarlovi** [comment]
Double checked this in master, it's not there. Then tried to remove the packages fully and reinstall them (so, not updating), it worked as expected.

Closing.
