### ISSUE TITLE
[Symfony] Custom processors not showing up in enqueue:routes

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#789]
I have a processor implementing only `Interop\Queue\Processor`. I add tags to it from a compiler pass, it looks like this:

```
 ---------------- ------------------------------------------------------------------------------------- 
  Option           Value                                                                                
 ---------------- ------------------------------------------------------------------------------------- 
  Service ID       App\Infrastructure\Elastica\Queue\SyncIndexWithEntityChangeProcessor                 
  Class            App\Infrastructure\Elastica\Queue\SyncIndexWithEntityChangeProcessor                 
  Tags             enqueue.processor (topic: doctrine.postPersist.ArticleBundle\Entity\Article)         
                   enqueue.processor (topic: doctrine.postUpdate.ArticleBundle\Entity\Article)          
                   enqueue.processor (topic: doctrine.postRemove.ArticleBundle\Entity\Article)              
  Public           yes                                                                                   
  Synthetic        no                                                                                   
  Lazy             no                                                                                   
  Shared           yes                                                                                  
  Abstract         no                                                                                   
  Autowired        yes                                                                                  
  Autoconfigured   yes                                                                                  
 ---------------- -------------------------------------------------------------------------------------
```

Judging by[ the documentation](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/message_processor.md#register-a-custom-processor), this should be enough for it to be used, but it doesn't show up in `bin/console enqueue:routes` nor does it work.

**Comment by makasim** [comment]
Confirm. It should work as described in the linked doc.

**Comment by makasim** [comment]
Could you please debug this code https://github.com/php-enqueue/enqueue-dev/blob/3775a422a3471ea8c9e9a59c9d295c9287c54ca9/pkg/enqueue/Symfony/Client/DependencyInjection/BuildProcessorRoutesPass.php#L29-L66 ?

**Comment by dkarlovi** [comment]
It seems the order of the compiler passes is wrong, your compiler pass finding the processors triggers before mine, the priority changed between 0.8 and 0.9. I'll try to find more details.

**Comment by dkarlovi** [comment]
OK, so I had my pass at
```
$container->addCompilerPass(new DependencyInjection\Compiler\SearchAggregateTransformerCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 10);
```

You have your at 
```
$container->addCompilerPass(new BuildClientProcessorRoutesPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 100);
```

This obviously changed from before, [you've set it while migrating passes](https://github.com/php-enqueue/enqueue-dev/commit/08a20a5ac222a008019ff953b8193a47b1cb2532).

It might make sense to make sure your passes run last when adding passes with no priority (defaults to 0) because otherwise this doesn't work by default. Maybe -100 instead of 100?

**Comment by makasim** [comment]
I don't remember what is that priority for

**Comment by dkarlovi** [comment]
It determines which passes run first (higher = first).

So, if I'm adding topics for my custom processors from a compiler pass, I must always supply a number higher than 100 and can't use the default.

My proposal is to **set your priority to -100**, that way if I add a compiler pass in userland to add topics, I don't need to supply any priority and it will work with defaults.

**Comment by makasim** [comment]
needs PR
