### ISSUE TITLE
Package size issue

### ISSUE THREAD

**Issue by ahghatol** [php-enqueue/enqueue-dev#792]
We are trying to package this library inside Joomla component but there is a limit on installable package size. 

We just need Amazon SQS, Doctrine DBAL transport. 

The **vendor** and **pkg** folder size is 91 MB and 6.2 MB respectively after running command `composer require enqueue/sqs` and `composer require enqueue/dbal`.

Is there a way to reduce this package size?

**Comment by makasim** [comment]
I've got 20MB on a clean isntallation of dbal and sqs. We've recently excluded some folders like tests from the distribution package. 

I've no idea how to shrink the size more. Feel free to submit a PR if you find one.
