### ISSUE TITLE
[Symfony][RabbitMQ] Enqueue null not working with Enveloppe

### ISSUE THREAD

**Issue by artandor** [php-enqueue/enqueue-dev#793]
I followed [this documentation](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/functional_testing.md) because i wanted to test my producer on an API-platform route.

In my case, i want to run my tests in a Gitlab CI environement, which mean there is no real need in testing the connexion to my broker (RabbitMQ here). Therefore, i've followed this configuration : 

```
# app/config/config_test.yml

enqueue:
    default:
        transport: 'null:'
        client: ~
```

I get an error because the enveloppe is not a supported class of the NullTransport. I need the enveloppe to setup a routing key for rabbitmq.

> Uncaught PHP Exception Enqueue\MessengerAdapter\Exception\MissingMessageMetadataSetterException: "Missing "setRoutingKey" setter for "routingKey" metadata key in "Enqueue\Null\NullMessage" class" at /srv/api/vendor/enqueue/messenger-adapter/QueueInteropTransport.php line 220

**Comment by makasim** [comment]
This is not an issue of Enqueue itself but Enqueue Messenger adapter. Please open an issue there https://github.com/php-enqueue/messenger-adapter
