### ISSUE TITLE
[sns] Sns transport does not support message attributes, needed for message filtering

### ISSUE THREAD

**Issue by aldenw** [php-enqueue/enqueue-dev#800]
Right now I don't see a way to specify message attributes as described [here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sns-2010-03-31.html#publish). This prevents from using the SNS message filtering.

I've made a [pull request](https://github.com/php-enqueue/enqueue-dev/pull/799) with changes that would allow the message attributes, and other fields allowed by the Aws Sns api to be provided with the message. It should be non-breaking.

**Comment by makasim** [comment]
Implemented in https://github.com/php-enqueue/enqueue-dev/pull/799
