### ISSUE TITLE
Configuration for Symfony 4 Messenger and Enqueue SNS/SQS

### ISSUE THREAD

**Issue by scottgutman** [php-enqueue/enqueue-dev#801]
Have been struggling with trying to make this setup work but I am having trouble finding the correct config documentation.  The docs I have seen show sending the messages in code without using the Symfony MessengerBusInterface ->dispatch method.

Is this setup possible, and if so, what do the .env, messanger.yaml, and enqueue.yaml config files look like?

**Comment by makasim** [comment]
open issue here  https://github.com/php-enqueue/messenger-adapter
