### ISSUE TITLE
Give permission for SNS to send messages to SQS

### ISSUE THREAD

**Issue by scottgutman** [php-enqueue/enqueue-dev#802]
After setting up SNS & SQS, I tried to send a message, but SQS never got the message. So I tried to send a message from the AWS GUI and still I was not able to send a message.  In my case, SNS did not have permission to send a message.  After adding the permission, messages sent through worked fine.

Here are the instructions to add a permission: https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html#SendMessageToSQS.sqs.permissions

Here is the code I used to create the topic and queue to start:

```
    $connectionFactoryFactory = new SnsQsConnectionFactory(sprintf(
        'snsqs::?key=%s&secret=%s&region=%s',
        getenv('AWS_ACCESS_KEY_ID'),
        getenv('AWS_SECRET_ACCESS_KEY'),
        getenv('AWS_REGION')
    ));
    $context = $connectionFactoryFactory->createContext();
    $inTopic = $context->createTopic('testQ');
    $context->declareTopic($inTopic);

    $out1Queue = $context->createQueue('testQ');
    $context->declareQueue($out1Queue);

    $context->bind($inTopic, $out1Queue);

```

Is there a way to sent the permissions automatically?

**Comment by makasim** [comment]
There is no such way. Feel free to provide a PR that adds this feature.
