### ISSUE TITLE
Docs issue for multiple queues in Symfony bundle

### ISSUE THREAD

**Issue by Toflar** [php-enqueue/enqueue-dev#806]
Hey folks,

I'm trying to configure the bundle in such a way that I can get 3 queues on redis (to mimic priority support).
So what I would like to have is the following

* 3 producers that all produce to the same transport but a different queue
* 3 workers `bin/console enqueue:consume` that consume from the same transport but a different queue

How do I configure that? I don't get it from the docs. I'll happily send a PR to fix that once I get it 😄

**Comment by makasim** [comment]
There is [client-queue-names](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Symfony/Client/ConsumeCommand.php#L86) argument for that. Please note that it is a client queue name, not a transport one. You can find out which one to use by running `enqueue:routes` command

**Comment by makasim** [comment]
There is similar options for `enqueue:transport:consume` command.

**Comment by Toflar** [comment]
I saw that but by just reading the docs I don‘t know how to configure multiple queues for the same transport. The docs is basically just a `config:dump-reference` which doesn‘t say a lot about usage. It‘s lacking examples!

**Comment by makasim** [comment]
I will add some when got into that topic again. feel free to contribute by improving the doc too. You are the one who understands the best what is not clear and hard to grasp.
