### ISSUE TITLE
Doc issue for functional testing

### ISSUE THREAD

**Issue by sylfabre** [php-enqueue/enqueue-dev#808]
Hi!

I want to add some functional testing to my enqueue implementation using Symfony.
I've read https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/functional_testing.md but I don't get what is the `a_service`?
Where does it come from? What kind of service is expected?

Thanks!

**Comment by Steveb-p** [comment]
The purpose of this example is to show a test checking that a particular "service" does indeed put a message in a topic. `a_service` can be any service that is expected to do that.

**Comment by sylfabre** [comment]
@Steveb-p ok thanks.

As is, it was not obvious that `a_service` with the `$service->do();` call was representing my business logic.

IMO, something like this is easier to understand:
```
// Use your own business logic here:
$service = $this->client->getContainer()->get('one_of_your_services');
// someMethod in your business logic, calling somewhere $producer->send('fooTopic', 'messageBody');
$service->someMethod();

$traces = $this->getProducer()->getTopicTraces('fooTopic');
```

**Comment by Steveb-p** [comment]
There is a note at the beginning of the example.

> Imagine you have a service that internally sends a message and you have to find out was the message sent or not.

But comments alongside the example would make a lot more transparent. Do you mind making a PR with your suggestions?

**Comment by sylfabre** [comment]
@Steveb-p here you are https://github.com/php-enqueue/enqueue-dev/pull/813
