### ISSUE TITLE
[dbal] requeue leads to duplicate entries

### ISSUE THREAD

**Issue by adrianrudnik** [php-enqueue/enqueue-dev#814]
I Just tried to implement a simple JSON submit queue where the endpoint can either respond HTTP status code 200 or fail. For that fail case I wanted to use the requeue option.

Building a very basic approach I always end up with endless new entries in the enqueue table, every retry leading to a new entry. Maybe I'm totally reading the docs wrong:

`Interop\Queue\Processor::REQUEUE` defines itself as `The original message is removed from the queue but a copy is published to the queue again.`. Looking at the code this is exact scenario is not reached, as the function returns prior removing the old message.

https://github.com/php-enqueue/enqueue-dev/blob/947eb72a5cb1139fcdf4b0fda899db8221ba1d13/pkg/dbal/DbalConsumer.php#L112

In addition to this the `Enqueue\Dbal\DbalProducer::send()` never looks for duplicates and updates them, instead always creating a new entry. This also leads to an infinite loop that fills the database with new entries which are directly processed in the same run.

Is this intended behaviour?

**Comment by Steveb-p** [comment]
It does seem that early exit a line before should probably be removed.

https://github.com/php-enqueue/enqueue-dev/blob/947eb72a5cb1139fcdf4b0fda899db8221ba1d13/pkg/dbal/DbalConsumer.php#L99-L113

It was superfluous at the moment it was introduced a year ago (https://github.com/php-enqueue/enqueue-dev/blob/97159fe5e3820096d57685e20d869d9e029b830f/pkg/dbal/DbalConsumer.php#L124-L138) and was probably left over without much thought.

Clearly, it is an error in the library. I'll provide a PR with functional test covering it.

**Comment by Steveb-p** [comment]
@adrianrudnik could you check in your local version if you swap the DbalConsumer code with the one in the PR that it behaves how you'd expect?

**Comment by adrianrudnik** [comment]
@Steveb-p just checked, yes it does, thanks!

**Comment by Steveb-p** [comment]
Tests without the change in code:
```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

...............................................................  63 / 144 ( 43%)
.........F..................................................... 126 / 144 ( 87%)
...............F..                                              144 / 144 (100%)

Time: 33.65 seconds, Memory: 12.00MB

There were 2 failures:

1) Enqueue\Dbal\Tests\Functional\DbalConsumerTest::testShouldRemoveOriginalMessageThatHaveBeenRejectedWithRequeue
Failed asserting that 2 is identical to 1.

...
```
Tests with changes removing the return.
```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

...............................................................  63 / 144 ( 43%)
............................................................... 126 / 144 ( 87%)
..................                                              144 / 144 (100%)

Time: 33.41 seconds, Memory: 12.00MB

OK (144 tests, 261 assertions)
```
