### ISSUE TITLE
Enqueue\AmqpExt\Symfony\RabbitMqAmqpTransportFactory not found

### ISSUE THREAD

**Issue by hiepnt93** [php-enqueue/enqueue-dev#817]
Fatal error: Uncaught Error: Class 'Enqueue\AmqpExt\Symfony\RabbitMqAmqpTransportFactory' not found in /var/www/html/vendor/enqueue/simple-client/SimpleClient.php:107

any know have same issue ?

i checked on that folder and cant find the file

**Comment by makasim** [comment]
It might be a misconfiguration issue. What enqueue version do you use? Have you installed amqp ext transport?
