### ISSUE TITLE
[SQS][Job][Symfony]A new entity was found

### ISSUE THREAD

**Issue by KDederichs** [php-enqueue/enqueue-dev#819]
`
"A new entity was found through the relationship 'Enqueue\JobQueue\Doctrine\Entity\Job#rootJob' that was not configured to cascade persist operations for entity: Enqueue\JobQueue\Doctrine\Entity\Job@0000000005a18d9a000000005e8996cf. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Enqueue\JobQueue\Doctrine\Entity\Job#__toString()' to get a clue."`

I get this error when I run delayed jobs in Symfony sometimes.
Looks like there is a problem when the entity manager was reset during the job execution lifetime (deadlock would be the likely cause). 

I personally do nothing with the job entity except grabbing the root job entity at the very start of the process.
Does the entity maybe need to be remerged?

**Comment by makasim** [comment]
possibly a bug. needs PR 

I do not use job-queue
