### ISSUE TITLE
[Beanstalkd] Unable to use delay

### ISSUE THREAD

**Issue by slaur** [php-enqueue/enqueue-dev#821]
I'm trying to use enqueue/pheanstalk with the symfony bundle.
Messages without delay are processed without error.
If I send a message with delay, the `setDeliveryDelay` method in `PheanstalkProducer` will throw an exception.
![ex](https://user-images.githubusercontent.com/1848190/55877402-3263c000-5b9a-11e9-985a-bf33ed810bcf.png)
Was someone able to use delayed jobs with beanstalkd and enqueue ?

**Comment by makasim** [comment]
The logic is not implemented, feel free to provide a pull request that adds it.

**Comment by slaur** [comment]
Thank you, I'll have a look.

**Comment by slaur** [comment]
Use `$message->setHeader('delay', $delay);` instead of `$message->setDelay($delay);`
