### ISSUE TITLE
[Elastica] The SyncIndexWithObjectChangeProcessor cannot update an entity more than once

### ISSUE THREAD

**Issue by philmoreau** [php-enqueue/enqueue-dev#823]
When many updates to the same entity are queued, the SyncIndexWithObjectChangeProcessor will always keep the first representation of an entity that it fetched from Doctrine, causing all subsequent updates to resend exactly the same data.

This happens because Doctrine's manager keeps a cached version of the entity and reuses that version for subsequent calls to "find". 

The solution is to clear all managed entities so Doctrine will re-fetch the entity from the database.

I will submit a PR.

**Comment by philmoreau** [comment]
https://github.com/php-enqueue/enqueue-elastica-bundle/pull/17

**Comment by makasim** [comment]
The doctrine clear extension could be used.

**Comment by philmoreau** [comment]
I hadn't noticed there was an extension for that, thanks!

Just wondering, is there a reason why the extension's behaviour isn't the default? Wouldn't it make sense to always fetch the entity's latest state, especially since this processor is called when an update is made?

**Comment by makasim** [comment]
Not everyone uses doctrine so enabling the ext by default might cause more trouble than it solves.
