### ISSUE TITLE
[Enhancement] Dead Queue Support for Async Events and Commands

### ISSUE THREAD

**Issue by dextervip** [php-enqueue/enqueue-dev#827]
Hi,

I was wondering if is there any implementation for dead queue on asyc commands and async events. Some of my messages are broken and I wouldn't like to stop my whole queue just because of one bad message but at same time I would like to keep it in other queue to further processing. As I am using supervisord to keep consumer on, it keeps trying the same message forever on loop. Any ideas?

**Comment by makasim** [comment]
One way to address it is to add a consumer extension that does the job.
