### ISSUE TITLE
[Job] Is it save to delete old jobs?

### ISSUE THREAD

**Issue by KDederichs** [php-enqueue/enqueue-dev#829]
As the title says, is it save to delete old entries in the enqueue_job table?
Mine is getting a tad full and the lack of indices is making it slower and slower (since I still have to manually complete jobs, see issue https://github.com/php-enqueue/enqueue-dev/issues/786)

**Comment by makasim** [comment]
If it has a completed status you can remove them. You can add indexes manually. It should work.
