### ISSUE TITLE
Add support for Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by bwegrzyn** [php-enqueue/enqueue-dev#83]
I noticed that there have been several new transports added recently. It would be nice to also support Google Cloud Pub/Sub as it would allow me to drop another dependency from my project.

Thanks for all the hard work!

**Comment by makasim** [comment]
That would be great to add indeed. No ETA though. If we happen to have a customer who needs we'll certainly do it.

**Comment by makasim** [comment]
Meanwhile, you can submit a PR, I'd more than happy to help you, ask any questions.

**Comment by makasim** [comment]
there's a PR: https://github.com/php-enqueue/enqueue-dev/pull/167
