### ISSUE TITLE
[kafka] One consumer for multiple kafka topics

### ISSUE THREAD

**Issue by koderoff** [php-enqueue/enqueue-dev#832]
I have several topics which are being populated by a separate app. Is there a way to consume from all of them by one consumer?

**Comment by Sevavietl** [comment]
As far as I know, you cannot do this using enqueue. 

[php-rdkafka](https://github.com/arnaud-lb/php-rdkafka) (based on [librdkafka](https://github.com/edenhill/librdkafka)) on which [php-enqueue/rdkafka](https://github.com/php-enqueue/rdkafka) is based provides [low-level consuming](https://github.com/arnaud-lb/php-rdkafka#low-level-consuming-from-multiple-topics--partitions) for such cases:

```php
$queue = $rk->newQueue();

$topic1 = $rk->newTopic("topic1");
$topic1->consumeQueueStart(0, RD_KAFKA_OFFSET_BEGINNING, $queue);
$topic1->consumeQueueStart(1, RD_KAFKA_OFFSET_BEGINNING, $queue);

$topic2 = $rk->newTopic("topic2");
$topic2->consumeQueueStart(0, RD_KAFKA_OFFSET_BEGINNING, $queue);

while (true) {
    $msg = $queue->consume(1000);
}
```
Enqueue library implements only high-level consuming.

**Comment by Steveb-p** [comment]
According to example present in the docs: https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.examples-high-level-consumer.html it is possible to use multiple topics in high level consumer, so we might look into allowing this in some form or another.

**Comment by Sevavietl** [comment]
@Steveb-p nice point, my bad.

From the source code, I see no other problems to implement this in the rdkafka transport except than:

1. `RdKafkaConsumer::getQueue()` should return `Queue` and in the current implementation `Queue` is the topic itself (`RdKafkaTopic`).
2. As transport can be configured with DSN only, as I understand, don't you know if there any conventions for specifying multiple topics there? I have never used this approach myself.

What do you think about mentioned caveats?

Thank you in advance for the answers.

**Comment by Steveb-p** [comment]
@Sevavietl I wasn't considering what changes to existing code should be made for it to work, or if it even makes sense considering other implementations (of enqueue queues). To be frank, I was almost sure one cannot use multiple topics in high level consumer myself.

As far as 2. is concerned, dsn should be perfectly capable of handling it. Specifically, `php-enqueue/dsn` can work with arrays like so:
https://github.com/php-enqueue/dsn/blob/5d011c648395307c740d8c0e420f8a9faebce72f/Tests/DsnTest.php#L474-L483

All that would be required is to always treat topic as array and convert single topic into an array if passed.

There might be some more configuration changes that need to be done, I just skimmed through what came to my mind.

**Comment by Sevavietl** [comment]
@Steveb-p thank you for the prompt response. I would be glad to help with this functionality, will try to create the PR

**Comment by Steveb-p** [comment]
@Sevavietl did you have time to look into this? Or can I take it over?

**Comment by Sevavietl** [comment]
@Steveb-p I have looked into, but have not implemented it into PR yet, so if you want you can take it over.
Or, better yet, maybe we can discuss the changes we need to implement this.
I do not know if here is the best place for a long discussion...

**Comment by Steveb-p** [comment]
@Sevavietl I’m available on php-enqueue’s gitter most od the time :)

**Comment by Steveb-p** [comment]
Hi stale-bot, be quiet please ;)

**Comment by diguin** [comment]
I know I'm a little late for the party, but I just faced the same problem. You are able to use a regex as a queue name. You just have to prefix it with ^

**Comment by harley84** [comment]
+1, having the ability to subscribe to multiple topics at once would be very helpful

**Comment by fmiqbal** [comment]
sry, any update on this ?

**Comment by keichinger** [comment]
I would also be interested in asking whether this has been implemented, and if so, if someone could point me into the right direction of where I could find the corresponding docs about this?

I'm just a bit overwhelmed by the existing docs as it seems to me personally, that a lot of existing knowledge is required in order to understand how to use Enqueue and Kafka with full examples kind of lacking :)
