### ISSUE TITLE
TypeError: array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by dhanabalarumugam** [php-enqueue/enqueue-dev#833]
TypeError: array_key_exists() expects parameter 2 to be array, null given

/vendor/enqueue/amqp-lib/AmqpSubscriptionConsumer.php:98

**Comment by Steveb-p** [comment]
This?
https://github.com/php-enqueue/enqueue-dev/blob/e399498922ed4d0a0056208bf10f0f1abfa989d8/pkg/amqp-lib/AmqpSubscriptionConsumer.php#L98

Please confirm which version on `php-enqueue` you're using. You can run `composer info enqueue/*` to get that information without looking through composer.lock file.

**Comment by dhanabalarumugam** [comment]
This is what I'm getting
enqueue/amqp-lib   0.9.8 Message Queue Amqp Transport
enqueue/amqp-tools 0.9.8 Message Queue Amqp Tools
enqueue/dsn        0.9.2 Parse DSN

**Comment by Steveb-p** [comment]
I've looked through the code and yeah, it seems that this particular array was simply not initialized :/

On your local copy you can simply initialize it - in constructor or as part of property declaration - and see if it helps and the library works. I'm not familiar with this code so I can't say for sure for myself.

If it's all that is required and it works properly after that, I'll provide a PR for you.

**Comment by dhanabalarumugam** [comment]
Yeah I have done that way and It worked fine for me.
