### ISSUE TITLE
EventTransformer transport-agnostic?

### ISSUE THREAD

**Issue by winzou** [php-enqueue/enqueue-dev#834]
Hi,

I'm trying to set up a custom EventTransformer, thanks to this part of the doc: https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/async_events.md#event-transformer

The `toMessage` method should return a `Interop\Queue\Message` as per its phpdoc: https://github.com/php-enqueue/enqueue-dev/blob/bf26188ad17068f8d483195a3ccbf84f2dc97962/pkg/async-event-dispatcher/EventTransformer.php#L14

And indeed, the AsyncListener, using the EventTransformer, passes this message directly to the producer `send` method: https://github.com/php-enqueue/enqueue-dev/blob/2ead9b5e18e14a758a49d2dccb391a067bb095e4/pkg/async-event-dispatcher/AsyncListener.php#L84

The thing is that in the documentation, the `toMessage` returns a `Enqueue\Client\Message` instance, which does *not* implement the `Interop\Queue\Message` interface.

Question is: which implementation of `Interop\Queue\Message` should I instance? When I look the implementations, I see `FsMessage`, `AmqpMessage`, etc. It looks like my EventTransformer must be aware of the underlying transport? I may miss something here.

Thanks!

**Comment by makasim** [comment]
> The thing is that in the documentation, the toMessage returns a Enqueue\Client\Message instance, 

This is a typo. `Enqueue\Client\Message` instance could not be used there. 

> Question is: which implementation of Interop\Queue\Message should I instance?

You should inject `Interop\Queue\Context` instance to the transformer and use it to create a proper message instance.

**Comment by winzou** [comment]
Thanks! Indeed I had injected the context and I'm now able to create a message with `$context->createMessage()`. Working like a charm!

One last, unrelated thing, I have created an extension on `onPostConsume` to flush the Doctrine entity manager after async events have been consumed. The extension runs (I can see it in the log) but it does not flush anything in the db. Is there any limitation of flushing during `onPostConsume`?

**Comment by makasim** [comment]
> The extension runs (I can see it in the log) but it does not flush anything in the db. Is there any limitation of flushing during onPostConsume?

There is no any I am aware of. I'd suggest flushing on post message received since post consume depends heavily rely on consuming timeout.

**Comment by winzou** [comment]
Thanks! It was an unrelated issue.
