### ISSUE TITLE
SQS Message ID

### ISSUE THREAD

**Issue by tigerstrikemedia** [php-enqueue/enqueue-dev#837]
The SQS Message handler does not set the AWS `messageID` to the message ID can we add

```
$message->setMessageId( $sqsMessage['MessageId'] );
```

to the `SqsConsumer` `convertMessage()` method ?

Thanks
Ben

**Comment by makasim** [comment]
LGTM

**Comment by makasim** [comment]
Feel free to send us a PR that address the issue
