### ISSUE TITLE
[enqueue-bundle] How to define a Redis DSN to use a unix socket instead of TCP?

### ISSUE THREAD

**Issue by poliander** [php-enqueue/enqueue-dev#840]
From what I can see in the sources the Redis adapter would use a unix socket when DSN scheme is "unix", but DSN is always "redis://..." so it's actually not possible to change the scheme to unix?

Shouldn't be socket connection used e.g. when the scheme is like "redis:///run/redis/redis.sock" or something like that? Currently it will use default fallback 127.0.0.1:6379 for such a DSN

Note: I am referring to the DSN defined in the enqueue Symfony bundle (enqueue.yaml)

**Comment by poliander** [comment]
`
# export ENQUEUE_DSN="unix:///run/redis/redis.sock" ; ./bin/console messenger:consume-messages

In ConnectionFactoryFactory.php line 39:

  A given scheme "unix" is not supported. Maybe it is a custom connection, make sure you registered it with "Enqueue\Resources::addConnection".
`

`# export ENQUEUE_DSN="redis:///run/redis/redis.sock" ; ./bin/console messenger:consume-messages
Array
(
    [scheme] => redis
    [scheme_extensions] => Array
        (
        )

    [host] => 127.0.0.1
    [port] => 6379
    [path] =>
    [database] =>
    [password] =>
    [async] =>
    [persistent] =>
    [lazy] => 1
    [timeout] => 5
    [read_write_timeout] =>
    [predis_options] =>
    [ssl] =>
    [redelivery_delay] => 300
)
`

**Comment by Steveb-p** [comment]
You might be able to achieve socket based connection using `redis+unix://run/redis/redis.sock` DSN string.

It is specified in https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/redis/RedisConnectionFactory.php#L115, so it's possible it's supported already in current release.

**Comment by poliander** [comment]
Thank you very much for your response,

I already tried that but without any success. Today I wrote my own RedisConnectionFactory which contains something like...

```
if (isset($config['path'])) {
  $config['scheme'] = 'unix';
  $config['port'] = null;
}

$this->config = $config;
```

**Comment by Steveb-p** [comment]
I've taken a little more time to look into the code and while `RedisConnectionFactory` can support socket based connections if schema is specified as `unix://`, but `ConnectionFactoryFactory` needs the first part to select which Factory to instantiate (`redis+unix://`).

Then DSN is passed without any changes to `RedisConnectionFactory`, scheme protocol is checked against support schemes (only `redis` will match, `unix` in above example will be considered as "scheme extension") and `unix` part will be ignored.

All in all, `Enqueue\Redis\RedisConnectionFactory::parseDsn` should probably be adjusted to allow this maybe? @makasim can I have your thought on this?

**Comment by makasim** [comment]
> ll in all, Enqueue\Redis\RedisConnectionFactory::parseDsn should probably be adjusted to allow this maybe? @makasim can I have your thought on this?

Yes, you are right. The factory should accept `redis+unix` scheme and use path as path to socket. ignoring host, port etc

**Comment by Steveb-p** [comment]
@makasim I'll provide a PR for it them soon™

**Comment by makasim** [comment]
needs PR

**Comment by RuslanMelnychenko** [comment]
I have this problem now when use Simple client with dsn `redis+phpredis+unix:/home/.socket/redis.sock`...
