### ISSUE TITLE
[Symfony] DebugClassLoader return Enqueue\Consumption\QueueConsumer::bindCallback as invalid.

### ISSUE THREAD

**Issue by vfalduto** [php-enqueue/enqueue-dev#841]
When execute phpUnit we have this warning 

The "Enqueue\Consumption\QueueConsumer::bindCallback()" method will require a new "string|InteropQueue $queueName" argument in the next major version of its parent class "Enqueue\Consumption\QueueConsumerInterface", not defining it is deprecated.

When we compare the class and interface, the only diff is on the phpDoc

**Comment by makasim** [comment]
I cannot reproduce the issue. Feel free to send us a PR that fixes the issue.
