### ISSUE TITLE
[Kafka] Support headers

### ISSUE THREAD

**Issue by Steveb-p** [php-enqueue/enqueue-dev#843]
Kafka messages can contain headers. I've seen some other packages had issues allowing headers to be sent, so I guess they can be introduced to Kafka package as well?

So far I've noticed that changes would be then required to `\Enqueue\RdKafka\RdKafkaConsumer::doReceive` and `\Enqueue\RdKafka\RdKafkaProducer::send` would need to switch between `produce` and `producev` Kafka producer methods. Do you recall any other places that would need adjustments?

EDIT: Noticed that there is a `JsonSerializer` that is responsible for encoding and decoding messages. While I would personally leave `properties` and `body` and still serialize them, I believe we could skip serialization for headers by putting them properly into `producev`. This could potentially allow consumers to skip messages when they are not interested in them, without going through deserialization process?

**Comment by makasim** [comment]
I like the idea of moving headers. We should consider possible BC breaks and try to avoid them.

**Comment by Steveb-p** [comment]
I'd suggest the following:
1. When producing put headers into actual Kafka message headers when `producev` method is available (phprdkafka 3.1.0). Otherwise stick to `produce`.
2. Read headers from Kafka message if they are available. Fall back to headers contained in body if they're empty.

Message properties would remain near body for the time being, unless you want them moved into headers?

Personally, I'd also note that current version of phprdkafka (3.1.0) will produce segfaults when paired with librdkafka (1.0.0). Patch for it is already merged into master so it should be fine in upcoming phprdkafka releases (insert shameless brag about making that patch :D )

**Comment by pedrofpvieira** [comment]
Hi @Steveb-p, @makasim  :)

First, thanks for the awesome job in keeping this lib updated. In my company (Jumia) are using it without any issue so far.

Relatively to this issue, can you please tell me if you, or anyone you know, are already working in some PR?
We could benefit with this change, and if no one is working on it yet, i can develop and submit a PR for this issue. Our main goal in reading the headers on consumers, but i can do the change to producers also. Is just to avoid having multiple people working on this without cooperation.

If it is more convenient you can reach me to my email (pedro.vieira@jumia.com) or skype '@pedro.f.p.vieira'

Thanks :)

Regards

**Comment by Steveb-p** [comment]
@pedrofpvieira I was actually looking at it two weeks ago and had a rough code that should work. It's missing tests however, both automatic (possibly) and manual (I haven't really checked if it works properly).

Take a look at it, maybe modify your app code to use this PR and see if you have any comments / issues with it. I'll test it more during the weekend, hopefully.

**Comment by Steveb-p** [comment]
@pedrofpvieira I've added you as collaborator to the fork containing the PR, in case you wanted to work on it :)

**Comment by pedrofpvieira** [comment]
Cool @Steveb-p, thank you. I Will check it anda give Feedback to you when possible :)

**Comment by Steveb-p** [comment]
@pedrofpvieira I've separated the consumption part to a separate PR, since it should be pretty much straightforward to use. The producing part is the one that might cause issues so we'll look into it and discuss further.

**Comment by Steveb-p** [comment]
Be silent, bot! I'll work on it. I promise! :)

**Comment by makasim** [comment]
@Steveb-p fyi: `pinned` label could be added. bot would skip the issue.
