### ISSUE TITLE
Service locator does not have a processor with name

### ISSUE THREAD

**Issue by athlan** [php-enqueue/enqueue-dev#848]
I would like to consume messages sent outside of application. Thus I declare the following processor.

References:
* https://github.com/php-enqueue/enqueue-dev/issues/451#issuecomment-395439984
* https://enqueue.readthedocs.io/en/stable/bundle/message_processor/

```php
<?php

namespace App\Order\Delivery\Enqueue;

use Enqueue\Client\CommandSubscriberInterface;
use Enqueue\Consumption\QueueSubscriberInterface;
use Interop\Queue\Context;
use Interop\Queue\Message;
use Interop\Queue\Processor;

class PaymentServiceEventsProcessor implements Processor, CommandSubscriberInterface, QueueSubscriberInterface
{
    const QUEUE = 'paymentservice.events.q';

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedCommand(): array
    {
        return [
            'processorName' => 'PaymentServiceEventsProcessor',
            'queueName' => self::QUEUE,
            'queueNameHardcoded' => true,
            'exclusive' => true,
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function getSubscribedQueues(): array
    {
        return [self::QUEUE];
    }

    /**
     * @inheritdoc
     */
    public function process(Message $message, Context $context)
    {
        echo 'test';
    }
}
```

services.yaml
```
    PaymentServiceEventsProcessor:
        class: App\Order\Delivery\Enqueue\PaymentServiceEventsProcessor
        public: true
        tags:
            - { name: 'enqueue.client.processor' }
```

After runnng:
```
bin/console enqueue:transport:consume PaymentServiceEventsProcessor
```

I get an exception:
```
Service locator does not have a processor with name "PaymentServiceEventsProcessor".
```

Tagging service additionally with `enqueue.client.message_processor` either both does not make processor discoverable.

Question 1: Here's a question: what is misconfigured here according to the documentation?
Question 2: There's mentioned `Enqueue\Psr\PsrProcessor` interface indocumentation. Is that valid since in repository https://github.com/php-enqueue/psr-queue is said that repo has moved and there are different abstrations in there like `Interop\Queue\Processor`?

**Comment by makasim** [comment]
You should also add [another tag](https://github.com/php-enqueue/enqueue-dev/blob/446eb4042f18fd7c645aaf64c24d6bf7078e885b/pkg/enqueue/Symfony/DependencyInjection/BuildProcessorRegistryPass.php#L30)

**Comment by makasim** [comment]
> Question 2: There's mentioned Enqueue\Psr\PsrProcessor interface indocumentation. Is that valid since in repository

No, it is not. It should be https://github.com/queue-interop/queue-interop/blob/master/src/Message.php

**Comment by athlan** [comment]
Thank you for quick reply a lot!

It seems that documentation under https://enqueue.readthedocs.io/en/stable/bundle/message_processor/ is outdated comparing to https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/message_processor.md.

Are they related? Is it an option to update it - means that it's out of sync only or it's completely different repo?

**Comment by makasim** [comment]
I've no time to keep readthedocs up to date. It is completely out of date. I decided to shut it down.

**Comment by athlan** [comment]
Ok, thank you for the follow up

czw., 16 maj 2019, 08:05 użytkownik Max Kotliar <notifications@github.com>
napisał:
