### ISSUE TITLE
SimpleClient with ConsumerMonitoringExtension

### ISSUE THREAD

**Issue by akrz** [php-enqueue/enqueue-dev#853]
So, how can I use the ConsumerMonitoringExtension with the SimpleClient API?

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/simple-client/SimpleClient.php#L188

**Comment by akrz** [comment]
Alright, I was able to use it like this (make sure to use the ChainExtension from **Consumption** namespace):
```php
$statsStorage = (new GenericStatsStorageFactory())->create('influxdb://127.0.0.1:8086?db=foo');
$runtimeExtension = new Enqueue\Consumption\ChainExtension([
    new ConsumerMonitoringExtension($statsStorage)
]);

$client->consume($runtimeExtension);
````

Is there a way to track consumer metrics using amqp-ext? The docs states:

> "Call this code from time to time between processing messages."

But the consume method for amqp-ext says:

> // this is a blocking call, it'll consume message until it is interrupted 
> $client->consume();

So, how can I call from time to time to send metrics?

**Comment by makasim** [comment]
Set a none zero timeout
