### ISSUE TITLE
[consumption] Context should be closed when exiting

### ISSUE THREAD

**Issue by Steveb-p** [php-enqueue/enqueue-dev#857]
In the particular case of Kafka package, when consumption ends, explicit connection closure is necessary to allow new process to immediately pick up consumption.

Otherwise there is a delay before messages become consumed again before Kafka broker realizes that connection was dropped permanently and reassigns partitions to new consumer.

This might be solved at a later date in phprdkafka library, since it probably is it's responsibility to call `rd_kafka_unsubscribe` internally when objects are destroyed - but as it currently stands the above holds true.

It is doable by creating an extension for `EndExtensionInterface`. Is this the desired approach? What impact would it have on other transports @makasim?

**Comment by makasim** [comment]
Can [SubscriptionConsumer](https://github.com/queue-interop/queue-interop/blob/master/src/SubscriptionConsumer.php) be applied?

**Comment by makasim** [comment]
For Consumer, we can add a note to the docs that the unsubscribe method should be called to speed up things.

**Comment by Steveb-p** [comment]
I've actually tested that with a consumer with 10 seconds timeout and it seemed that despite calling `unsubscribe` on context there was a delay before next process picks up. Which means it's either a Kafka specific issue (more librdkafka) or it did not disconnect properly. I don't know what version of related libraries I was on, I'll check on monday at work.

**Comment by Steveb-p** [comment]
According to https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence#high-level-kafkaconsumer calling `unsubscribe` is unnecessary. We might want to consider placing "proper termination sequence" code inside enqueue, but I'll have to check what actual effect it will have on an application.
