### ISSUE TITLE
Move docs to github pages

### ISSUE THREAD

**Issue by Steveb-p** [php-enqueue/enqueue-dev#864]
Documentation in current form, while works great, requires traversing "source code" of repository. It might be beneficial to use gh-pages to show documentation only.

It should be little cost to enable it. As a matter of fact, @makasim you can already do so in repository settings by going to https://github.com/php-enqueue/enqueue-dev/settings and choosing `/docs` from master as gh-pages source. Conveniently .md files can be used and Github uses Jekyll to build the site.

![image](https://user-images.githubusercontent.com/3183926/58371991-3fa0f800-7f17-11e9-8dda-4b0e9be6f1ee.png)

I've taken the liberty and enabled it on my own repository and added a custom theme, which allows creating sidebar menu (for a relatively complex docs structure should be a nice addition - see 2. refence below). Link to template is available so you can see if "white" colour scheme is more to your liking.

See: https://steveb-p.github.io/enqueue-dev/

References:
https://help.github.com/en/articles/user-organization-and-project-pages
https://pmarsceill.github.io/just-the-docs/

When enabled, gh-pages will show under:
https://enqueue-php.github.com/enqueue-dev
(unless you make a organization repository names `enqueue-php`)

**Comment by Steveb-p** [comment]
I made an oopsie and accidentally commited to the main repository... :(

Since those are not really important changes I didn't try to revert them or force push :(

**Comment by Steveb-p** [comment]
I f... up and accidentally pushed into this repository instead of my own (for template testing for enqueue github pages). I've force pushed master back into previous state, but you might want @makasim to enable strict checks against pushing to master:

![image](https://user-images.githubusercontent.com/3183926/58373098-ac70be00-7f28-11e9-976b-e7ff15c4bd01.png)

**Comment by makasim** [comment]
Few people have access to the repo. The restriction would make their life harder. It does not bother me much, at least now. Let's keep it as is.

**Comment by makasim** [comment]
Good idea with gh pages. I'll give it a try.

**Comment by Steveb-p** [comment]
@makasim If you don't mind I'll simply give you colabolator status on the fork, so you'll be able to check how it looks without affecting current master branch (since afaik you can either have gh-pages branch, master branch in root, or master branch in `/docs`). I've also added instructions on how to run documentation locally with docker.

**Comment by Steveb-p** [comment]
@makasim You'll probably need to enable github pages in https://github.com/php-enqueue/php-enqueue settings for github to pick up the pages. It should show `master` branch specifically, without /docs subdirectory.

**Comment by makasim** [comment]
fixed
