### ISSUE TITLE
Install probot/stale

### ISSUE THREAD

**Issue by Steveb-p** [php-enqueue/enqueue-dev#876]
@makasim As discussed in a different issue.

I've sent a request to `php-enqueue` to install the bot. If it didn't show up as notification, you can add it manually using https://github.com/apps/stale/ install link on top right.
You probably want to install it only to `enqueue-dev` repository, which can be selected as one of the options there.

![image](https://user-images.githubusercontent.com/3183926/58427600-60e12000-80a0-11e9-9bad-c1512e005cee.png)

All that is needed afterwards is inserting `.github/stale.yml` file with your prefered configuration. We discussed 30 days for marking as stale, example file has 60. Otherwise it should do just fine.

See: https://github.com/probot/stale

**Comment by makasim** [comment]
done

**Comment by Steveb-p** [comment]
I've seen bot running rampant, closing issues left, right and center :D

:+1:
