### ISSUE TITLE
Supporting lazy queues with the rabbit MQ driver

### ISSUE THREAD

**Issue by mrchrisadams** [php-enqueue/enqueue-dev#904]
Hi there.

I'm working with Enqueue, and using RabbitMQ as the underlying queue for messages, and I'm looking for some pointers on supporting [Lazy Queues](https://www.rabbitmq.com/lazy-queues.html) with Enqueue.

### What Lazy queues are and what they are useful.

The best practice recommendations for RabbitMQ that I see, recommend you keep queues short, but there are some cases where you might want support long queues.

> Since RabbitMQ 3.6.0, the broker has the concept of Lazy Queues - queues that move their contents to disk as early as practically possible, and only load them in RAM when requested by consumers, therefore the lazy denomination.
> One of the main goals of lazy queues is to be able to support very long queues (many millions of messages).

I have a use case where I need to put a lot work onto a queue (i.e. a few million messages, for workers to run through), and if you're using rabbit 3.6 or later, you can do this by passing in  arguments like this `$queue->setArguments(['x-queue-mode' => 'lazy']);` when creating a  queue.

### Creating a lazy RabbitMQ driver

I know we have a [RabbitMQ driver](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/Driver/RabbitMqDriver.php), activated by using a connection string like `amqp+rabbitmq` as our DSN.

```
class RabbitMqDriver extends AmqpDriver
{
    /**
     * @return AmqpQueue
     */
    protected function doCreateQueue(string $transportQueueName): InteropQueue
    {
        $queue = parent::doCreateQueue($transportQueueName);
        $queue->setArguments(['x-max-priority' => 4]);
        return $queue;
    }
}

```

I'm proposing something like passing in a connection string like `amqp+rabbitmqlazy` for our DSN or similar, and a _lazy_ driver like so:

```
class LazyRabbitMqDriver extends AmqpDriver
{
    /**
     * @return AmqpQueue
     */
    protected function doCreateQueue(string $transportQueueName): InteropQueue
    {
        $queue = parent::doCreateQueue($transportQueueName);
        $queue->setArguments(['x-max-priority' => 4]);
        $queue->setArguments(['x-queue-mode' => 'lazy']);
        return $queue;
    }
}
```

### Specific Questions

 - 1) Does lazy refer to something else here? I see [`lazy` referred to in the config reference in the docs](https://github.com/php-enqueue/enqueue-dev/blob/742a0af0cb6986e68f7109647a9effcdbc16a582/docs/bundle/config_reference.md
), but I see no mention in the code base of `x-queue-mode`,  nor as [a supported feature](
https://github.com/php-enqueue/enqueue-dev/blob/742a0af0cb6986e68f7109647a9effcdbc16a582/docs/client/supported_brokers.md)
 so I suspect it's something different.

- 2) Where do I set up the extension and the driver to load in? Would I add it to [Resources.php in enqueue/Client/](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/Resources.php#L60-L65)

**Comment by Steveb-p** [comment]
@mrchrisadams why not configuration option instead for RabbitMQ driver specifically?

**Comment by mrchrisadams** [comment]
@Steveb-p mainly because I wasn't sure how to pass them in. I'd prefer doing that way, but it looks like the term `lazy` was already in use and I couldn't work out how to do it.

I'm totally happy to try that instead tho 👍

**Comment by mrchrisadams** [comment]
@Steveb-p how would I query for for configuration options in the RabbitMQDriver?

Would I query the config a bit like so?

```php

class RabbitMqDriver extends AmqpDriver
{
    /**
     * @return AmqpQueue
     */
    protected function doCreateQueue(string $transportQueueName): InteropQueue
    {
        $config = this->getConfig();
        $lazy = config['lazy'];

        $queue = parent::doCreateQueue($transportQueueName);
        $queue->setArguments(['x-max-priority' => 4]);

        if($lazy == 'true') {
          $queue->setArguments(['x-queue-mode' => 'lazy']);
        }

        return $queue;
    }
}
```

**Comment by Steveb-p** [comment]
Judging from what I've skimmed through in code `lazy` is currently responsible for creating a connection instance without actually connecting (until needed).

I'd prefer adding an option to existing driver since that's what it is - an option :)
Unfortunately, `createQueue` only accepts string as argument and I'm not sure you'd want every queue created from enqueue using that `Context` to create a lazy queue.

Regarding your new comment:
```php
/**
     * @return AmqpQueue
     */
    protected function doCreateQueue(string $transportQueueName): InteropQueue
    {
        $config = this->getConfig();
        $lazy = config->isLazy();

        $queue = parent::doCreateQueue($transportQueueName);
        $queue->setArguments(['x-max-priority' => 4]);

        if ($lazy) {
          $queue->setArguments(['x-queue-mode' => 'lazy']);
        }

        return $queue;
    }
```

Pretty much like this. But as I said, I'm not sure if every queue created from this context should be lazy. But there is no way to really adjust queue creation after Context has been initialized.

**Comment by mrchrisadams** [comment]
OK, thanks @Steveb-p. 

I've made a starter here, assuming that an end user is on RabbitMQ 3.6 or higher.

I'm not sure how we'd address the issue of automatically making every queue lazy here, but I'm open to suggestions, for supporting different kinds of queues here, and if you have preferences about how you prefer tests for this to be written, please let me know - PHP isn't my main programming language,

Cheers
