### ISSUE TITLE
[Symfony] autowire consumption extensions

### ISSUE THREAD

**Issue by dkarlovi** [php-enqueue/enqueue-dev#910]
Adding `tag: enqueue.consumption.extension` is currently required since the `*ExtensionInterface` interfaces are not added for autowiring.

Should be easy enough to fix.

**Comment by makasim** [comment]
Usually, developers do not need the whole ExtensionInterface just some methods, so a developer might implement only some of the extension interfaces. 

So to make autowire work we need a kind of marker interface that all consumption extension interfaces implement.

**Comment by dkarlovi** [comment]
@makasim IMO it's fine to autowire all the individual interfaces, no? That's why I've added the `*` prefix.

**Comment by makasim** [comment]
How many times a tag would be added if a real extension implements two interfaces?

**Comment by dkarlovi** [comment]
Not sure, I'd expect Symfony to deduplicate them if they're exactly the same, otherwise it's their bug.

**Comment by Steveb-p** [comment]
We could try using `CompilerPass` to look over tagged services, mayyybe.

> Not sure, I'd expect Symfony to deduplicate them if they're exactly the same, otherwise it's their bug.

Symfony does not make any assumptions regarding tag duplication. If you do duplicate, it's your fault.

**Comment by dkarlovi** [comment]
> Symfony does not make any assumptions regarding tag duplication. If you do duplicate, it's your fault.

I mean, when auto-wiring interfaces. Since it's under their control, it wouldn't make sense to add multiple tags where they're not needed and then conclude that it's your fault.

**Comment by Steveb-p** [comment]
> > Symfony does not make any assumptions regarding tag duplication. If you do duplicate, it's your fault.
> 
> I mean, when auto-wiring interfaces. Since it's under their control, it wouldn't make sense to add multiple tags where they're not needed and then conclude that it's your fault.

You're probably right. I case of autowiring I would assume the same.

**Comment by dkarlovi** [comment]
Well, nothing else to do but try and PR this repo, optionally filling a bug with Symfony if we're wrong in our assumptions. :)
