### ISSUE TITLE
Multiple Queues in Symfony

### ISSUE THREAD

**Issue by lostfocus** [php-enqueue/enqueue-dev#919]
There are a couple of open _and_ closed issues regarding the documentation when it comes to multiple queues with the Symfony bundle. I'm absolutely willing to write a nice .md-file to document how it works if someone could just point me in the right direction.

Let's say I have two topics I want to publish to: `hello` and `goodbye` - so far that's easy:

`Enqueue\Client\ProducerInterface $producer` in the dependency injection part of my service and then:

```
$helloWorld = new Enqueue\Client\Message(['object' => 'world']);
$producer->sendEvent('hello',$helloWorld);
```

and

```
$goodbyeWorld = new Enqueue\Client\Message(['object' => 'world']);
$producer->sendEvent('goodbye',$goodbyeWorld);
```

Now when I look into my queue, I can see that both messages are in the queue `enqueue.app.default` and when I run the queue runner with `bin/console enqueue:consume --time-limit="now+5minutes" -vvv` I can see that the processors find the messages and do their thing.

Now what I'd like to do is to execute `bin/console enqueue:consume --time-limit="now+5minutes" -vvv hello` and `bin/console enqueue:consume --time-limit="now+5minutes" -vvv goodbye` separately - and I figure that works only when they're not both in the `enqueue.app.default` queue. 

_At what point can I tell the message or the producer which queue to use?_

As I said - just point me in the right direction and I'm happy to write a nice explanation for the documentation.

**Comment by Steveb-p** [comment]
@lostfocus https://github.com/php-enqueue/enqueue-dev/tree/master/docs/bundle should be a good place for it. It will be converted into https://github.com/php-enqueue/enqueue-dev/tree/master/docs/bundle once it's merged.

Also see https://php-enqueue.github.io#contributing-to-this-documentation if you want to see how it will look locally. You can use local Jekyll of course if you don't like docker with shared directories.

**Comment by makasim** [comment]
You can configure a queue on processor registration. It could be an attribute of service tag, a parameter of queue subscriber, a parameter of command subscriber. All end up in https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Client/Route.php.

Some examples could be found here: https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/message_processor.md

**Comment by lostfocus** [comment]
Thanks. That will be my weekend project then.
