### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by inverse** [php-enqueue/enqueue-dev#925]
Would it be possible to link to the nice documentation easier. This one:

> https://php-enqueue.github.io/

1. Having this on the repo description would be great.
2. Linking to it from https://enqueue.forma-pro.com/ on the "Documentation" button at the top.

**Comment by makasim** [comment]
I've no access to the site anymore.

**Comment by inverse** [comment]
Can we update this repo at least to include the link to the documentation then?

**Comment by Steveb-p** [comment]
> Can we update this repo at least to include the link to the documentation then?

I'm pretty sure @makasim can do that, maybe he had missed it (it's about documentation link **in repository description** btw :smile:)

Also added a hyperlink to enqueue logo in #926.

**Comment by inverse** [comment]
@Steveb-p thanks! That helps :)
