### ISSUE TITLE
Change Queue Name

### ISSUE THREAD

**Issue by MariusFollert95** [php-enqueue/enqueue-dev#934]
Hi,

is it possible to change the SQS Queue default name ( enqueue_dot_app_dot_default) of the router queue to a custom name? 

Best regards,
Dominik

**Comment by makasim** [comment]
Yes, it should be possible. What framework do you use?

**Comment by dmaier95** [comment]
Thanks for your fast reply. Symfony 3.4

**Comment by MariusFollert95** [comment]
Thanks for your fast reply. Symfony 3.4

**Comment by makasim** [comment]
There is `default_queue` name. See https://php-enqueue.github.io/bundle/config_reference/
