### ISSUE TITLE
[question] Is that possible to have message without headers and properties? 

### ISSUE THREAD

**Issue by kolinko-ant** [php-enqueue/enqueue-dev#937]
Hi guys,

My case is that we already have kafka running with some producers. Message payload is just json object. I was trying to create a consumer using symfony messenger + enqueue kafka transport. And then I realised that implementation is tight to the message interface that should contain body, properties, headers. 

Is there a way to overwrite this logic, so I can just have plain message data like json object which I then decode to array?

**Comment by aryzhenko** [comment]
Bump

The same question. We also need ability to send RAW JSON to kafka topic. But it always wrapped with Message.

**Comment by amcosta88** [comment]
Same question too...

**Comment by Steveb-p** [comment]
Enqueue makes some assumptions regarding how message looks and what fields it has, so theoretically that would be a no - at least not without disabling enqueue internal message routing or exchanging some of the internal parts.

You may make it work by replacing the serializer on the `RdKafkaContext`.

However, I'll be working on creating a more abstract library in the near future for use in Symfony Messenger Kafka transport without reliance on enqueue, so if you could wait a bit, I might offer a working solution for you.
