### ISSUE TITLE
Redelivery fixed 20 minutes

### ISSUE THREAD

**Issue by TheJenne18** [php-enqueue/enqueue-dev#938]
When an enqueue job fails, I see it is by default delayed for 20 minutes.

Is there a possibility to get this value from the .yaml config?

https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/dbal/DbalConsumer.php#L47

**Comment by daemonfire300** [comment]
@TheJenne18 Hi, what do you mean by "fails", i.e., your processor returns (a) reject or (b) requeue? Is that a DBAL transport specific feature?

**Comment by TheJenne18** [comment]
@daemonfire300 I mail reject and requeue. They both delay this for 20 minutes.
