### ISSUE TITLE
Multiple bindCallback() cause huge CPU load

### ISSUE THREAD

**Issue by benrogmans** [php-enqueue/enqueue-dev#944]
I'm following the documentation and I'm using the Filesystem transport. When binding a single callback to $queueConsumer, the PHP process uses 0.3% of CPU.

As soon as I bind more than 1 callback to $queueConsumer, my PHP process starts using 99.9% of the CPU. The consumers are not even processing messages at this point - there are no producers running yet.

I have followed this example (with multiple bindCallback()):
```
<?php
use Interop\Queue\Message;
use Interop\Queue\Processor;
use Interop\Queue\Context;
use Enqueue\Consumption\QueueConsumer;

/** @var Context $context */

$queueConsumer = new QueueConsumer($context);

$queueConsumer->bindCallback('foo_queue', function(Message $message) {
    // process message

    return Processor::ACK;
});
$queueConsumer->bindCallback('bar_queue', function(Message $message) {
    // process message

    return Processor::ACK;
});

$queueConsumer->consume();
```

As a workaround we are now running the consumers each in their own php process, but since we have quite a lot of consumers/callbacks we would prefer to bind multiple callback functions within a single php process. Any help or tips where to debug would be greatly appreciated. This library looks awesome by the way.

**Comment by benrogmans** [comment]
I’d like to keep this issue open. Is it a known problem?

**Comment by Steveb-p** [comment]
> I’d like to keep this issue open. Is it a known problem?

@benrogmans Sorry, I haven't had time to diagnose this. Could you provide a code sample, when this issue occurs so we can maybe look into converting into a test case eventually?
