### ISSUE TITLE
[Kafka] Non-replaceable serializer

### ISSUE THREAD

**Issue by TiMESPLiNTER** [php-enqueue/enqueue-dev#948]
Why am I forced to use the `JsonSerializer` which doesn't allow me to provide any other message payload than one in the format:

```json
{
    "headers": [],
    "properties": [],
    "body": "..."
}
```

It would be great to have kind of a  `NullSerializer()`  which does on the  `toMessage()`  method nothing else then returning the KafkaMessage with the payload from the RdKafkaMessage which it got as a parameter.

Because as it is now I have no possibility to consume a message from kafka which is not in the format showed above. Or do I miss something? What's the reason for this  ̀JsonSerializer` being in place right now?

**Comment by Steveb-p** [comment]
@TiMESPLiNTER The reason for this is that enqueue does duplicate routing mechanisms similar to the ones that already exist in Kafka (which was realized when we we're discussing documentation issues in #838). Original implementation relies on headers to decide which `Processor` should handle the message.

IMO using Kafka topics as routes is desired, but atm I'm not working with Kafka where I work (unfortunately, at least until I'm reassigned / get back to apps that use it) so my time is limited.

I'm also pretty sure that Symfony adapter that uses enqueue does replace serializer with it's own one, but I haven't looked there for some time and don't remember.

**Comment by TiMESPLiNTER** [comment]
@Steveb-p actually both serializers are used. First the one provided by Enqueue and then the one defined in the messenger component for Symfony. If I send the message in the format which is enformed by the Enqueue JsonSerializer I end up with it in the Messenger serializer of the Symfony messenger component.

I would need to somehow be able to override Enqueue's serializer as I have no need for it. Is that possible as of today? I didn't find any possibility because it seems to be hard-wired to the context. [1] Or replace it. And I would really propose to replace the default in the next major version and make it configurable.

[1]: https://github.com/php-enqueue/rdkafka/blob/master/RdKafkaContext.php#L56

**Comment by Steveb-p** [comment]
@TiMESPLiNTER `RdKafkaContext` and `RdKafkaConsumer` have `setSerializer` method so you can replace it with whatever you'd prefer. You can replace by calling `RdKafkaContext::setSerializer`. Check `Serializer` interface: 

https://github.com/php-enqueue/enqueue-dev/blob/acb978a893d407f7835b3a1c00dd48f43407d86b/pkg/rdkafka/Serializer.php#L1-L12

It doesn't _feel_ ideal, but should do as a workaround.
