### ISSUE TITLE
[amqp] Upgrade php-amqplib to v2.9

### ISSUE THREAD

**Issue by gnumoksha** [php-enqueue/enqueue-dev#951]
From https://github.com/queue-interop/amqp-interop/issues/16

I'm getting the error `stream_select(): unable to select [4]: Interrupted system call (max_fd=6)` on my consumers. This error [was fixed in version 2.9 of php-amqplib](https://github.com/php-amqplib/php-amqplib/issues/670) however [php-enqueue requires version 2.8](https://github.com/php-enqueue/amqp-lib/blob/master/composer.json).

**Comment by Steveb-p** [comment]
```json
"php-amqplib/php-amqplib": "^2.8",
```
Composer file you linked states that any version higher that 2.8, but below 3.0 is compatible.

**Comment by gnumoksha** [comment]
Yeah, at first I've misunderstood composer syntax, this is why I've changed the title to "upgrade". It seems to me that php-enqueue should require a version free of bugs (i.e. >=2.9)

**Comment by Steveb-p** [comment]
Technically `enqueue` is compatible with 2.8, but considering that this is a major bug in that extension I believe we should do an exception.

@makasim WDYT?

**Comment by ramunasd** [comment]
library version upgraded in #967

**Comment by gnumoksha** [comment]
Thank you all
