### ISSUE TITLE
Simple client multiple queue

### ISSUE THREAD

**Issue by jes490** [php-enqueue/enqueue-dev#952]
Hi guys! Thank you for the package! 

I have one question about SimpleClient. Is there any way to send messages to different queues? Right now it sends them to default router queue. If there any workarounds?

**Comment by balabis** [comment]
Hi, maybe this will be of any help -- https://github.com/php-enqueue/enqueue-dev/pull/920/files?short_path=5f13fe8#diff-5f13fe81bfb2cabd8a023b0c4fbc91fa
