### ISSUE TITLE
Configuration to setup-broker exchange type direct

### ISSUE THREAD

**Issue by florianajir** [php-enqueue/enqueue-dev#962]
Hello,

I try to make working the setup-broker command with my rabbitmq architecture which need exchange of type direct but I don't find how to change the type from the default "fanout" mode.

Is there a way ?

**Comment by makasim** [comment]
Enqueue Client is a highly opinionated solution with the goal to provide the most simple solution for default use cases. If you need something more custom or advanced I advise step one layer down and using a transport library directly. That gives you much more freedom on what you can do with it. Including the use of direct exchange.
