### ISSUE TITLE
Add options to send headers with enqueue:produce command

### ISSUE THREAD

**Issue by TiMESPLiNTER** [php-enqueue/enqueue-dev#963]
There is currently no possibility to send headers with the  `enqueue:produce` command. It would be nice to add an option to specify headers:

```
$ bin/console enqueue:produce '{"foo": "message content"}' --topic=... --header='Content-Type: application/json' --header='Action: create' 
```

**Comment by Steveb-p** [comment]
This issue has an ongoing PR Mr. Stale :smile:
