### ISSUE TITLE
[STOMP] Configuration Connection before connect

### ISSUE THREAD

**Issue by versh23** [php-enqueue/enqueue-dev#968]
Hello

I want to add ServerAliveObserver and writeTimeout , but it is not possible to add this without connect to broker
https://github.com/php-enqueue/stomp/blob/master/StompConnectionFactory.php#L97

I can do something like this

```
        $factory = new StompConnectionFactory($config);
        $context = $factory->createContext();

        $stomp = $context->getStomp();
        $stomp->disconnect();
        $connection = $stomp->getConnection();

        $connection->getObservers()->addObserver(new ServerAliveObserver());
```

But it is not good for me.

Can we add posibility to add callable to config and run before `->connect() `?

Or may be something else ? What do you @makasim  think about it ?  I can make PR

**Comment by makasim** [comment]
The solution could be to pass an instance of stomp client to the connection factory. Just like we did for Redis transport: https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/redis/RedisConnectionFactory.php#L58-L63

**Comment by versh23** [comment]
its good for redis, but is too complexity to create BufferedClient for stomp by hand.
May be add a some config parameters like a 
 - write_timeout
 - heart_beat
 - use_heart_emmiter
 - use_server_alive_observer

like a https://github.com/php-enqueue/amqp-lib/blob/master/AmqpConnectionFactory.php#L104-L106

**Comment by versh23** [comment]
ping @makasim

**Comment by Steveb-p** [comment]
@versh23 makasim is hard to reach recently, or doesn't have much time. Sorry.

Could you please provide a PR? I'm no expert in STOMP so can't really help with reviewing PRs from technical perspective, but I'll look at it in general.

**Comment by versh23** [comment]
@Steveb-p i make PR
