### ISSUE TITLE
Multiple workers listening on different queues

### ISSUE THREAD

**Issue by leigh-ols** [php-enqueue/enqueue-dev#969]
Not entirely sure i'm in the right place. This could be a symfony bundle issue.

We're using the Symfony bundle with beanstalkd.

We have two environments running on one server, staging and production.

We therefore have two workers running, one for the staging and one for the production environment. Each running off of their respective codebase.  They are both using the same beanstalkd.

To prevent them picking up on each others commands we adjust the subscribed command based on the current environment:

```
class PackageProcessor implements Processor, CommandSubscriberInterface
{
...
    public static function getSubscribedCommand()
    {
        // I dont' like this use of $GLOBALS here, but it's kind of unavoidable
        // for now!
        return 'package_process_'.$GLOBALS['kernel']->getEnvironment();
    }
}
```

This ensures that the correct worker gets the correct jobs (in theory).

However the issue we are running into is that with both workers running. the results are very inconsistent. Quite frequently, neither worker picks up a job. The job is sent off, but never received by its respective worker.

I've come here in hopes of some enlightenment from those who know the more inner workings of the code base. Is there something obvious i'm missing somewhere along the line that would cause the two to conflict?

Thanks for any help!

**Comment by makasim** [comment]
Use Symfony service tag (https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Symfony/Client/DependencyInjection/BuildProcessorRoutesPass.php#L29) instead of command subscriber.

**Comment by makasim** [comment]
The other  solution is to configure enqueue clients to use different queue prefixes: 

https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/config_reference.md

play with prefix or app_name options.

**Comment by leigh-ols** [comment]
Thanks @makasim  for the suggested workarounds. I'll look into the queue prefixes and app_name options today.

Do you have any insights on to what is causing the issue as it stands?

**Comment by leigh-ols** [comment]
Using the environment as a prefix appears to have entirely solved the issue. Really appreciate the help.

Still curious as to exactly what was happening with the subscribed command method though.
