### ISSUE TITLE
[rdkafka] RdKafka\Conf::setDefaultTopicConf() is deprecated

### ISSUE THREAD

**Issue by anam-hossain** [php-enqueue/enqueue-dev#970]
PHP rd-kafka 4.0 throwing the following exception:

```
In RdKafkaContext.php line 193:
                                                              
  Function RdKafka\Conf::setDefaultTopicConf() is deprecated  
```

https://github.com/php-enqueue/rdkafka/blob/master/RdKafkaContext.php#L218

**Comment by robert-schmidt** [comment]
I'm experiencing the same issue :(

**Comment by Sadegh-Ameri** [comment]
I'm also experiencing the same issue

**Comment by iBasit** [comment]
same issue on latest checkout

**Comment by Gilgamesh-y** [comment]
same issue on latest checkout

**Comment by Rolice** [comment]
Hello, I have also ended up on the same issue. It seems that the newer version of RDKafka deprecates this function. The `librdkafka` and `rdkafka` were installed with the OS package manager and `pecl`.

In the composer package, I find the usage here: https://github.com/php-enqueue/enqueue-dev/blob/3fba3a8919641acdc8d7d4a7552671aa01773833/pkg/rdkafka/RdKafkaContext.php#L218

Do you have any plans to release a new version to support newer versions of RDKafka?
Thanks!

**Comment by Steveb-p** [comment]
Yes @Rolice.

Sorry, I'm just busy and my draft was not stable enough to share.

**Comment by nickpoulos** [comment]
Was this issue ever resolved? I am running into this error as well.
