### ISSUE TITLE
[Kafka] Question: What are the message properties?

### ISSUE THREAD

**Issue by anam-hossain** [php-enqueue/enqueue-dev#971]
`rdkafka/RdKafkaMessage.php` has a concept called `properties`.  The [JsonSerializer](https://github.com/php-enqueue/rdkafka/blob/master/JsonSerializer.php#L39) throws an exception if properties are missing in the Kafka message? 

What are the message properties? What should be passed as properties?

```php

    public function setProperties(array $properties): void
    {
        $this->properties = $properties;
    }
    public function getProperties(): array
    {
        return $this->properties;
    }
    public function setProperty(string $name, $value): void
    {
        $this->properties[$name] = $value;
    }
    public function getProperty(string $name, $default = null)
    {
        return array_key_exists($name, $this->properties) ? $this->properties[$name] : $default;
    }
```

https://github.com/php-enqueue/rdkafka/blob/master/RdKafkaMessage.php#L64,L84
https://github.com/php-enqueue/rdkafka/blob/master/JsonSerializer.php

**Comment by Steveb-p** [comment]
@anam-hossain depending on your use case they might not affect you at all. They are used by `enqueue-bundle` internally to adjust message routing if I recall correctly.

If you're using `enqueue-kafka` to read messages coming from another application that has no relationship to `enqueue`, then you can safely replace `JsonSerializer` with a different `Serializer` that converts that `RdKafkaMessage` body into a `Message` with empty (`[]`) properties.

**Comment by anam-hossain** [comment]
@Steveb-p Thank you.
