### ISSUE TITLE
Set connection name in RabbitMQ connection tab

### ISSUE THREAD

**Issue by Webonaute** [php-enqueue/enqueue-dev#978]
hi.

is it possible to set a connection name who appear in connection tab in RabbitMQ.

I would like to add the version of our api running the consumer and the environment name

**Comment by Webonaute** [comment]
example: 
![Screen Shot 2019-11-05 at 4 36 07 PM](https://user-images.githubusercontent.com/1700815/68248277-7b71da80-ffea-11e9-8e4d-b4fd434c51e6.png)

Here is an example I see when I'm connect to rabbitmq management tool.

<rabbit@loyal-skunk-01.3.1270.0>

**Comment by Webonaute** [comment]
More info, seem that there is a ClientProperties with connection_name we can set somewhere but I can't find how to hook up. in AMQP Extension look like LIBRARY_PROPERTIES need to be overwrite with extra property.

**Comment by Webonaute** [comment]
still looking for this

**Comment by Steveb-p** [comment]
@Webonaute I'm no expert in AMQP, but what I've found when looking through it's repository (which you mentioned somewhat) is that `LIBRRARY_PROPERTIES` is a static property of all connections:
https://github.com/madrussa/php-amqplib/blob/2518832c34941bf0e8600d64b8b84c4c4d587250/PhpAmqpLib/Connection/AbstractConnection.php#L19

Try changing it before connection is established and see if it does anything for you. Then we can discuss a PR to introduce this in a more user-friendly manner into some library options.

**Comment by Webonaute** [comment]
please considere adding this change https://github.com/supersmile2009/amqp-ext/commit/08a1326a82dabc7ea4873afbff0dcb8a5b55a815
