### ISSUE TITLE
[amqp-lib] return queue name from AmqpContext::declareQueue

### ISSUE THREAD

**Issue by vria** [php-enqueue/enqueue-dev#980]
Hello,

is there any reason to igonre the name of a queue returned by `AMQPChannel::queue_declare` [here](https://github.com/php-enqueue/amqp-lib/blob/11e4b3eb8df5ad9506fd048a0922303483a3e3a1/AmqpContext.php#L165) ?
I need to create transient "callback" queues and I would like to rely on RabbitMQ name generation:

```php
$replyToQueue = $context->createQueue('');
$replyToQueue->addFlag(AmqpDestination::FLAG_AUTODELETE);
list($queueName, ) = $context->declareQueue($replyToQueue);
```

What do you think to modify the value returned by `AmqpContext::declareQueue` ?

**Comment by makasim** [comment]
Would this method be of help https://github.com/php-enqueue/amqp-lib/blob/11e4b3eb8df5ad9506fd048a0922303483a3e3a1/AmqpContext.php#L130 ?

**Comment by vria** [comment]
No, I prefer autodeleted queues because I subscribe to it in a different process. At this moment the initial connection gets closed and a exlusive queue gets deleted.

**Comment by makasim** [comment]
@vria I see. The `declareQueue` method has to be updated
