### ISSUE TITLE
Incompatibility with doctrine/doctrine-bundle v2

### ISSUE THREAD

**Issue by likeuntomurphy** [php-enqueue/enqueue-dev#984]
The enqueue/enqueue package is incompatible with Doctrine bundle v2 when used with Symfony because `Symfony\Bridge\Doctrine\RegistryInterface` is no longer aliased to the  `doctrine` service (https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md#service-aliases).

> Argument 1 passed to Enqueue\Doctrine\DoctrineConnectionFactoryFactory::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\Bundle\DoctrineBundle\Registry given

I downgraded the Doctrine bundle to 1.6, but then the `ServiceEntityRepository` class from the v2 Doctrine bundle is unavailable, and I am relying on it.

I don’t know what the milestones are for the enqueue package, so I don’t really know what the exact solution is to maintain BC. For the time being, I am planning on forking the repo and changing the typehint from `Symfony\Bridge\Doctrine\RegistryInterface` to `Doctrine\Common\Persistence\ManagerRegistry`.

**Comment by Steveb-p** [comment]
From what I see removal of this interface is the only major thing that makes Doctrine bundle 2.0 incompatible. You can fork and make PR with necessary changes to make it work.
